/**
 * Copyright 2023-present DreamNum Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { IFunctionInfo } from '@univerjs/engine-formula';
import { FUNCTION_NAMES_LOOKUP, FunctionType } from '@univerjs/engine-formula';

export const FUNCTION_LIST_LOOKUP: IFunctionInfo[] = [
    {
        functionName: FUNCTION_NAMES_LOOKUP.ADDRESS,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.ADDRESS.description',
        abstract: 'sheets-formula.functionList.ADDRESS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ADDRESS.functionParameter.row_num.name',
                detail: 'sheets-formula.functionList.ADDRESS.functionParameter.row_num.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ADDRESS.functionParameter.column_num.name',
                detail: 'sheets-formula.functionList.ADDRESS.functionParameter.column_num.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ADDRESS.functionParameter.abs_num.name',
                detail: 'sheets-formula.functionList.ADDRESS.functionParameter.abs_num.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ADDRESS.functionParameter.a1.name',
                detail: 'sheets-formula.functionList.ADDRESS.functionParameter.a1.detail',
                example: 'TRUE',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ADDRESS.functionParameter.sheet_text.name',
                detail: 'sheets-formula.functionList.ADDRESS.functionParameter.sheet_text.detail',
                example: '"Sheet2"',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.AREAS,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.AREAS.description',
        abstract: 'sheets-formula.functionList.AREAS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.AREAS.functionParameter.reference.name',
                detail: 'sheets-formula.functionList.AREAS.functionParameter.reference.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.CHOOSE,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.CHOOSE.description',
        abstract: 'sheets-formula.functionList.CHOOSE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CHOOSE.functionParameter.indexNum.name',
                detail: 'sheets-formula.functionList.CHOOSE.functionParameter.indexNum.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CHOOSE.functionParameter.value1.name',
                detail: 'sheets-formula.functionList.CHOOSE.functionParameter.value1.detail',
                example: '"Hello"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CHOOSE.functionParameter.value2.name',
                detail: 'sheets-formula.functionList.CHOOSE.functionParameter.value2.detail',
                example: '"Univer"',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.CHOOSECOLS,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.CHOOSECOLS.description',
        abstract: 'sheets-formula.functionList.CHOOSECOLS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CHOOSECOLS.functionParameter.array.name',
                detail: 'sheets-formula.functionList.CHOOSECOLS.functionParameter.array.detail',
                example: 'A1:C2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CHOOSECOLS.functionParameter.colNum1.name',
                detail: 'sheets-formula.functionList.CHOOSECOLS.functionParameter.colNum1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CHOOSECOLS.functionParameter.colNum2.name',
                detail: 'sheets-formula.functionList.CHOOSECOLS.functionParameter.colNum2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.CHOOSEROWS,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.CHOOSEROWS.description',
        abstract: 'sheets-formula.functionList.CHOOSEROWS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CHOOSEROWS.functionParameter.array.name',
                detail: 'sheets-formula.functionList.CHOOSEROWS.functionParameter.array.detail',
                example: 'A1:C2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CHOOSEROWS.functionParameter.rowNum1.name',
                detail: 'sheets-formula.functionList.CHOOSEROWS.functionParameter.rowNum1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CHOOSEROWS.functionParameter.rowNum2.name',
                detail: 'sheets-formula.functionList.CHOOSEROWS.functionParameter.rowNum2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.COLUMN,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.COLUMN.description',
        abstract: 'sheets-formula.functionList.COLUMN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.COLUMN.functionParameter.reference.name',
                detail: 'sheets-formula.functionList.COLUMN.functionParameter.reference.detail',
                example: 'A1:A20',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.COLUMNS,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.COLUMNS.description',
        abstract: 'sheets-formula.functionList.COLUMNS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.COLUMNS.functionParameter.array.name',
                detail: 'sheets-formula.functionList.COLUMNS.functionParameter.array.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.DROP,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.DROP.description',
        abstract: 'sheets-formula.functionList.DROP.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.DROP.functionParameter.array.name',
                detail: 'sheets-formula.functionList.DROP.functionParameter.array.detail',
                example: 'A2:C4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.DROP.functionParameter.rows.name',
                detail: 'sheets-formula.functionList.DROP.functionParameter.rows.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.DROP.functionParameter.columns.name',
                detail: 'sheets-formula.functionList.DROP.functionParameter.columns.detail',
                example: '2',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.EXPAND,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.EXPAND.description',
        abstract: 'sheets-formula.functionList.EXPAND.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.EXPAND.functionParameter.array.name',
                detail: 'sheets-formula.functionList.EXPAND.functionParameter.array.detail',
                example: 'A2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.EXPAND.functionParameter.rows.name',
                detail: 'sheets-formula.functionList.EXPAND.functionParameter.rows.detail',
                example: '3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.EXPAND.functionParameter.columns.name',
                detail: 'sheets-formula.functionList.EXPAND.functionParameter.columns.detail',
                example: '3',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.EXPAND.functionParameter.padWith.name',
                detail: 'sheets-formula.functionList.EXPAND.functionParameter.padWith.detail',
                example: '"-"',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.FILTER,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.FILTER.description',
        abstract: 'sheets-formula.functionList.FILTER.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FILTER.functionParameter.array.name',
                detail: 'sheets-formula.functionList.FILTER.functionParameter.array.detail',
                example: 'A5:D20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FILTER.functionParameter.include.name',
                detail: 'sheets-formula.functionList.FILTER.functionParameter.include.detail',
                example: '(C5:C20="Apple")*(A5:A20="East")',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FILTER.functionParameter.ifEmpty.name',
                detail: 'sheets-formula.functionList.FILTER.functionParameter.ifEmpty.detail',
                example: '""',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.FORMULATEXT,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.FORMULATEXT.description',
        abstract: 'sheets-formula.functionList.FORMULATEXT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FORMULATEXT.functionParameter.reference.name',
                detail: 'sheets-formula.functionList.FORMULATEXT.functionParameter.reference.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.GETPIVOTDATA,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.GETPIVOTDATA.description',
        abstract: 'sheets-formula.functionList.GETPIVOTDATA.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.GETPIVOTDATA.functionParameter.dataField.name',
                detail: 'sheets-formula.functionList.GETPIVOTDATA.functionParameter.dataField.detail',
                example: '"Sales"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.GETPIVOTDATA.functionParameter.pivotTable.name',
                detail: 'sheets-formula.functionList.GETPIVOTDATA.functionParameter.pivotTable.detail',
                example: 'A3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.GETPIVOTDATA.functionParameter.field1.name',
                detail: 'sheets-formula.functionList.GETPIVOTDATA.functionParameter.field1.detail',
                example: '"Month"',
                require: 0,
                repeat: 1,
            },
            {
                name: 'sheets-formula.functionList.GETPIVOTDATA.functionParameter.item1.name',
                detail: 'sheets-formula.functionList.GETPIVOTDATA.functionParameter.item1.detail',
                example: '"March"',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.HLOOKUP,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.HLOOKUP.description',
        abstract: 'sheets-formula.functionList.HLOOKUP.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.HLOOKUP.functionParameter.lookupValue.name',
                detail: 'sheets-formula.functionList.HLOOKUP.functionParameter.lookupValue.detail',
                example: 'A1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.HLOOKUP.functionParameter.tableArray.name',
                detail: 'sheets-formula.functionList.HLOOKUP.functionParameter.tableArray.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.HLOOKUP.functionParameter.rowIndexNum.name',
                detail: 'sheets-formula.functionList.HLOOKUP.functionParameter.rowIndexNum.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.HLOOKUP.functionParameter.rangeLookup.name',
                detail: 'sheets-formula.functionList.HLOOKUP.functionParameter.rangeLookup.detail',
                example: 'false',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.HSTACK,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.HSTACK.description',
        abstract: 'sheets-formula.functionList.HSTACK.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.HSTACK.functionParameter.array1.name',
                detail: 'sheets-formula.functionList.HSTACK.functionParameter.array1.detail',
                example: 'A2:C3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.HSTACK.functionParameter.array2.name',
                detail: 'sheets-formula.functionList.HSTACK.functionParameter.array2.detail',
                example: 'E2:G3',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.HYPERLINK,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.HYPERLINK.description',
        abstract: 'sheets-formula.functionList.HYPERLINK.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.HYPERLINK.functionParameter.url.name',
                detail: 'sheets-formula.functionList.HYPERLINK.functionParameter.url.detail',
                example: '"https://univer.ai/"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.HYPERLINK.functionParameter.linkLabel.name',
                detail: 'sheets-formula.functionList.HYPERLINK.functionParameter.linkLabel.detail',
                example: '"Univer"',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.IMAGE,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.IMAGE.description',
        abstract: 'sheets-formula.functionList.IMAGE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.IMAGE.functionParameter.source.name',
                detail: 'sheets-formula.functionList.IMAGE.functionParameter.source.detail',
                example: '"https://github.com/dream-num.png"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.IMAGE.functionParameter.altText.name',
                detail: 'sheets-formula.functionList.IMAGE.functionParameter.altText.detail',
                example: '"Univer Logo"',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.IMAGE.functionParameter.sizing.name',
                detail: 'sheets-formula.functionList.IMAGE.functionParameter.sizing.detail',
                example: '3',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.IMAGE.functionParameter.height.name',
                detail: 'sheets-formula.functionList.IMAGE.functionParameter.height.detail',
                example: '100',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.IMAGE.functionParameter.width.name',
                detail: 'sheets-formula.functionList.IMAGE.functionParameter.width.detail',
                example: '100',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.INDEX,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.INDEX.description',
        abstract: 'sheets-formula.functionList.INDEX.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.INDEX.functionParameter.reference.name',
                detail: 'sheets-formula.functionList.INDEX.functionParameter.reference.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.INDEX.functionParameter.rowNum.name',
                detail: 'sheets-formula.functionList.INDEX.functionParameter.rowNum.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.INDEX.functionParameter.columnNum.name',
                detail: 'sheets-formula.functionList.INDEX.functionParameter.columnNum.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.INDEX.functionParameter.areaNum.name',
                detail: 'sheets-formula.functionList.INDEX.functionParameter.areaNum.detail',
                example: '2',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.INDIRECT,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.INDIRECT.description',
        abstract: 'sheets-formula.functionList.INDIRECT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.INDIRECT.functionParameter.refText.name',
                detail: 'sheets-formula.functionList.INDIRECT.functionParameter.refText.detail',
                example: '"A1"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.INDIRECT.functionParameter.a1.name',
                detail: 'sheets-formula.functionList.INDIRECT.functionParameter.a1.detail',
                example: 'TRUE',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.LOOKUP,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.LOOKUP.description',
        abstract: 'sheets-formula.functionList.LOOKUP.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.LOOKUP.functionParameter.lookupValue.name',
                detail: 'sheets-formula.functionList.LOOKUP.functionParameter.lookupValue.detail',
                example: 'A1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.LOOKUP.functionParameter.lookupVectorOrArray.name',
                detail: 'sheets-formula.functionList.LOOKUP.functionParameter.lookupVectorOrArray.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.LOOKUP.functionParameter.resultVector.name',
                detail: 'sheets-formula.functionList.LOOKUP.functionParameter.resultVector.detail',
                example: 'A1:A20',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.MATCH,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.MATCH.description',
        abstract: 'sheets-formula.functionList.MATCH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.MATCH.functionParameter.lookupValue.name',
                detail: 'sheets-formula.functionList.MATCH.functionParameter.lookupValue.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.MATCH.functionParameter.lookupArray.name',
                detail: 'sheets-formula.functionList.MATCH.functionParameter.lookupArray.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.MATCH.functionParameter.matchType.name',
                detail: 'sheets-formula.functionList.MATCH.functionParameter.matchType.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.OFFSET,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.OFFSET.description',
        abstract: 'sheets-formula.functionList.OFFSET.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.OFFSET.functionParameter.reference.name',
                detail: 'sheets-formula.functionList.OFFSET.functionParameter.reference.detail',
                example: 'A1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.OFFSET.functionParameter.rows.name',
                detail: 'sheets-formula.functionList.OFFSET.functionParameter.rows.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.OFFSET.functionParameter.cols.name',
                detail: 'sheets-formula.functionList.OFFSET.functionParameter.cols.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.OFFSET.functionParameter.height.name',
                detail: 'sheets-formula.functionList.OFFSET.functionParameter.height.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.OFFSET.functionParameter.width.name',
                detail: 'sheets-formula.functionList.OFFSET.functionParameter.width.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.ROW,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.ROW.description',
        abstract: 'sheets-formula.functionList.ROW.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ROW.functionParameter.reference.name',
                detail: 'sheets-formula.functionList.ROW.functionParameter.reference.detail',
                example: 'A1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.ROWS,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.ROWS.description',
        abstract: 'sheets-formula.functionList.ROWS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ROWS.functionParameter.array.name',
                detail: 'sheets-formula.functionList.ROWS.functionParameter.array.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.RTD,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.RTD.description',
        abstract: 'sheets-formula.functionList.RTD.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.RTD.functionParameter.progId.name',
                detail: 'sheets-formula.functionList.RTD.functionParameter.progId.detail',
                example: '"mycomaddin.progid"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RTD.functionParameter.server.name',
                detail: 'sheets-formula.functionList.RTD.functionParameter.server.detail',
                example: '""',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RTD.functionParameter.topic1.name',
                detail: 'sheets-formula.functionList.RTD.functionParameter.topic1.detail',
                example: '"Topic"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RTD.functionParameter.topic2.name',
                detail: 'sheets-formula.functionList.RTD.functionParameter.topic2.detail',
                example: '"Item"',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.SORT,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.SORT.description',
        abstract: 'sheets-formula.functionList.SORT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SORT.functionParameter.array.name',
                detail: 'sheets-formula.functionList.SORT.functionParameter.array.detail',
                example: 'A2:A17',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SORT.functionParameter.sortIndex.name',
                detail: 'sheets-formula.functionList.SORT.functionParameter.sortIndex.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SORT.functionParameter.sortOrder.name',
                detail: 'sheets-formula.functionList.SORT.functionParameter.sortOrder.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SORT.functionParameter.byCol.name',
                detail: 'sheets-formula.functionList.SORT.functionParameter.byCol.detail',
                example: 'false',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.SORTBY,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.SORTBY.description',
        abstract: 'sheets-formula.functionList.SORTBY.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SORTBY.functionParameter.array.name',
                detail: 'sheets-formula.functionList.SORTBY.functionParameter.array.detail',
                example: 'D2:D9',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SORTBY.functionParameter.byArray1.name',
                detail: 'sheets-formula.functionList.SORTBY.functionParameter.byArray1.detail',
                example: 'E2:E9',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SORTBY.functionParameter.sortOrder1.name',
                detail: 'sheets-formula.functionList.SORTBY.functionParameter.sortOrder1.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SORTBY.functionParameter.byArray2.name',
                detail: 'sheets-formula.functionList.SORTBY.functionParameter.byArray2.detail',
                example: 'E2:E9',
                require: 0,
                repeat: 1,
            },
            {
                name: 'sheets-formula.functionList.SORTBY.functionParameter.sortOrder2.name',
                detail: 'sheets-formula.functionList.SORTBY.functionParameter.sortOrder2.detail',
                example: '1',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.TAKE,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.TAKE.description',
        abstract: 'sheets-formula.functionList.TAKE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TAKE.functionParameter.array.name',
                detail: 'sheets-formula.functionList.TAKE.functionParameter.array.detail',
                example: 'A2:C4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TAKE.functionParameter.rows.name',
                detail: 'sheets-formula.functionList.TAKE.functionParameter.rows.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TAKE.functionParameter.columns.name',
                detail: 'sheets-formula.functionList.TAKE.functionParameter.columns.detail',
                example: '2',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.TOCOL,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.TOCOL.description',
        abstract: 'sheets-formula.functionList.TOCOL.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TOCOL.functionParameter.array.name',
                detail: 'sheets-formula.functionList.TOCOL.functionParameter.array.detail',
                example: 'A2:D4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TOCOL.functionParameter.ignore.name',
                detail: 'sheets-formula.functionList.TOCOL.functionParameter.ignore.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TOCOL.functionParameter.scanByColumn.name',
                detail: 'sheets-formula.functionList.TOCOL.functionParameter.scanByColumn.detail',
                example: 'TRUE',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.TOROW,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.TOROW.description',
        abstract: 'sheets-formula.functionList.TOROW.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TOROW.functionParameter.array.name',
                detail: 'sheets-formula.functionList.TOROW.functionParameter.array.detail',
                example: 'A2:D4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TOROW.functionParameter.ignore.name',
                detail: 'sheets-formula.functionList.TOROW.functionParameter.ignore.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TOROW.functionParameter.scanByColumn.name',
                detail: 'sheets-formula.functionList.TOROW.functionParameter.scanByColumn.detail',
                example: 'TRUE',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.TRANSPOSE,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.TRANSPOSE.description',
        abstract: 'sheets-formula.functionList.TRANSPOSE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TRANSPOSE.functionParameter.array.name',
                detail: 'sheets-formula.functionList.TRANSPOSE.functionParameter.array.detail',
                example: 'A2:F9',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.UNIQUE,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.UNIQUE.description',
        abstract: 'sheets-formula.functionList.UNIQUE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.UNIQUE.functionParameter.array.name',
                detail: 'sheets-formula.functionList.UNIQUE.functionParameter.array.detail',
                example: 'A2:A12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.UNIQUE.functionParameter.byCol.name',
                detail: 'sheets-formula.functionList.UNIQUE.functionParameter.byCol.detail',
                example: 'false',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.UNIQUE.functionParameter.exactlyOnce.name',
                detail: 'sheets-formula.functionList.UNIQUE.functionParameter.exactlyOnce.detail',
                example: 'false',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.VLOOKUP,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.VLOOKUP.description',
        abstract: 'sheets-formula.functionList.VLOOKUP.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.VLOOKUP.functionParameter.lookupValue.name',
                detail: 'sheets-formula.functionList.VLOOKUP.functionParameter.lookupValue.detail',
                example: 'B2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.VLOOKUP.functionParameter.tableArray.name',
                detail: 'sheets-formula.functionList.VLOOKUP.functionParameter.tableArray.detail',
                example: 'C2:E7',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.VLOOKUP.functionParameter.colIndexNum.name',
                detail: 'sheets-formula.functionList.VLOOKUP.functionParameter.colIndexNum.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.VLOOKUP.functionParameter.rangeLookup.name',
                detail: 'sheets-formula.functionList.VLOOKUP.functionParameter.rangeLookup.detail',
                example: 'TRUE',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.VSTACK,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.VSTACK.description',
        abstract: 'sheets-formula.functionList.VSTACK.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.VSTACK.functionParameter.array1.name',
                detail: 'sheets-formula.functionList.VSTACK.functionParameter.array1.detail',
                example: 'A2:C3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.VSTACK.functionParameter.array2.name',
                detail: 'sheets-formula.functionList.VSTACK.functionParameter.array2.detail',
                example: 'E2:G3',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.WRAPCOLS,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.WRAPCOLS.description',
        abstract: 'sheets-formula.functionList.WRAPCOLS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.WRAPCOLS.functionParameter.vector.name',
                detail: 'sheets-formula.functionList.WRAPCOLS.functionParameter.vector.detail',
                example: 'A2:G2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.WRAPCOLS.functionParameter.wrapCount.name',
                detail: 'sheets-formula.functionList.WRAPCOLS.functionParameter.wrapCount.detail',
                example: '3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.WRAPCOLS.functionParameter.padWith.name',
                detail: 'sheets-formula.functionList.WRAPCOLS.functionParameter.padWith.detail',
                example: '"x"',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.WRAPROWS,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.WRAPROWS.description',
        abstract: 'sheets-formula.functionList.WRAPROWS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.WRAPROWS.functionParameter.vector.name',
                detail: 'sheets-formula.functionList.WRAPROWS.functionParameter.vector.detail',
                example: 'A2:G2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.WRAPROWS.functionParameter.wrapCount.name',
                detail: 'sheets-formula.functionList.WRAPROWS.functionParameter.wrapCount.detail',
                example: '3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.WRAPROWS.functionParameter.padWith.name',
                detail: 'sheets-formula.functionList.WRAPROWS.functionParameter.padWith.detail',
                example: '"x"',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.XLOOKUP,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.XLOOKUP.description',
        abstract: 'sheets-formula.functionList.XLOOKUP.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.XLOOKUP.functionParameter.lookupValue.name',
                detail: 'sheets-formula.functionList.XLOOKUP.functionParameter.lookupValue.detail',
                example: 'A1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.XLOOKUP.functionParameter.lookupArray.name',
                detail: 'sheets-formula.functionList.XLOOKUP.functionParameter.lookupArray.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.XLOOKUP.functionParameter.returnArray.name',
                detail: 'sheets-formula.functionList.XLOOKUP.functionParameter.returnArray.detail',
                example: 'B1:B20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.XLOOKUP.functionParameter.ifNotFound.name',
                detail: 'sheets-formula.functionList.XLOOKUP.functionParameter.ifNotFound.detail',
                example: 'default',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.XLOOKUP.functionParameter.matchMode.name',
                detail: 'sheets-formula.functionList.XLOOKUP.functionParameter.matchMode.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.XLOOKUP.functionParameter.searchMode.name',
                detail: 'sheets-formula.functionList.XLOOKUP.functionParameter.searchMode.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_LOOKUP.XMATCH,
        functionType: FunctionType.Lookup,
        description: 'sheets-formula.functionList.XMATCH.description',
        abstract: 'sheets-formula.functionList.XMATCH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.XMATCH.functionParameter.lookupValue.name',
                detail: 'sheets-formula.functionList.XMATCH.functionParameter.lookupValue.detail',
                example: 'B1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.XMATCH.functionParameter.lookupArray.name',
                detail: 'sheets-formula.functionList.XMATCH.functionParameter.lookupArray.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.XMATCH.functionParameter.matchMode.name',
                detail: 'sheets-formula.functionList.XMATCH.functionParameter.matchMode.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.XMATCH.functionParameter.searchMode.name',
                detail: 'sheets-formula.functionList.XMATCH.functionParameter.searchMode.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
];
