/**
 * Copyright 2023-present DreamNum Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { IFunctionInfo } from '@univerjs/engine-formula';
import { FUNCTION_NAMES_MATH, FunctionType } from '@univerjs/engine-formula';

export const FUNCTION_LIST_MATH: IFunctionInfo[] = [
    {
        functionName: FUNCTION_NAMES_MATH.ABS,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ABS.description',
        abstract: 'sheets-formula.functionList.ABS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ABS.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ABS.functionParameter.number.detail',
                example: '-2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ACOS,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ACOS.description',
        abstract: 'sheets-formula.functionList.ACOS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ACOS.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ACOS.functionParameter.number.detail',
                example: '0',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ACOSH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ACOSH.description',
        abstract: 'sheets-formula.functionList.ACOSH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ACOSH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ACOSH.functionParameter.number.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ACOT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ACOT.description',
        abstract: 'sheets-formula.functionList.ACOT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ACOT.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ACOT.functionParameter.number.detail',
                example: '0',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ACOTH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ACOTH.description',
        abstract: 'sheets-formula.functionList.ACOTH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ACOTH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ACOTH.functionParameter.number.detail',
                example: '6',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.AGGREGATE,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.AGGREGATE.description',
        abstract: 'sheets-formula.functionList.AGGREGATE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.AGGREGATE.functionParameter.functionNum.name',
                detail: 'sheets-formula.functionList.AGGREGATE.functionParameter.functionNum.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.AGGREGATE.functionParameter.options.name',
                detail: 'sheets-formula.functionList.AGGREGATE.functionParameter.options.detail',
                example: '6',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.AGGREGATE.functionParameter.ref1.name',
                detail: 'sheets-formula.functionList.AGGREGATE.functionParameter.ref1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.AGGREGATE.functionParameter.ref2.name',
                detail: 'sheets-formula.functionList.AGGREGATE.functionParameter.ref2.detail',
                example: 'B1:B20',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ARABIC,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ARABIC.description',
        abstract: 'sheets-formula.functionList.ARABIC.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ARABIC.functionParameter.text.name',
                detail: 'sheets-formula.functionList.ARABIC.functionParameter.text.detail',
                example: '"LVII"',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ASIN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ASIN.description',
        abstract: 'sheets-formula.functionList.ASIN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ASIN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ASIN.functionParameter.number.detail',
                example: '0',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ASINH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ASINH.description',
        abstract: 'sheets-formula.functionList.ASINH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ASINH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ASINH.functionParameter.number.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ATAN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ATAN.description',
        abstract: 'sheets-formula.functionList.ATAN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ATAN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ATAN.functionParameter.number.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ATAN2,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ATAN2.description',
        abstract: 'sheets-formula.functionList.ATAN2.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ATAN2.functionParameter.xNum.name',
                detail: 'sheets-formula.functionList.ATAN2.functionParameter.xNum.detail',
                example: '4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ATAN2.functionParameter.yNum.name',
                detail: 'sheets-formula.functionList.ATAN2.functionParameter.yNum.detail',
                example: '3',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ATANH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ATANH.description',
        abstract: 'sheets-formula.functionList.ATANH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ATANH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ATANH.functionParameter.number.detail',
                example: '0.1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.BASE,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.BASE.description',
        abstract: 'sheets-formula.functionList.BASE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.BASE.functionParameter.number.name',
                detail: 'sheets-formula.functionList.BASE.functionParameter.number.detail',
                example: '15',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BASE.functionParameter.radix.name',
                detail: 'sheets-formula.functionList.BASE.functionParameter.radix.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BASE.functionParameter.minLength.name',
                detail: 'sheets-formula.functionList.BASE.functionParameter.minLength.detail',
                example: '10',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.CEILING,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.CEILING.description',
        abstract: 'sheets-formula.functionList.CEILING.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CEILING.functionParameter.number.name',
                detail: 'sheets-formula.functionList.CEILING.functionParameter.number.detail',
                example: '2.5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CEILING.functionParameter.significance.name',
                detail: 'sheets-formula.functionList.CEILING.functionParameter.significance.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.CEILING_MATH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.CEILING_MATH.description',
        abstract: 'sheets-formula.functionList.CEILING_MATH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CEILING_MATH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.CEILING_MATH.functionParameter.number.detail',
                example: '-5.5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CEILING_MATH.functionParameter.significance.name',
                detail: 'sheets-formula.functionList.CEILING_MATH.functionParameter.significance.detail',
                example: '2',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CEILING_MATH.functionParameter.mode.name',
                detail: 'sheets-formula.functionList.CEILING_MATH.functionParameter.mode.detail',
                example: '-1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.CEILING_PRECISE,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.CEILING_PRECISE.description',
        abstract: 'sheets-formula.functionList.CEILING_PRECISE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CEILING_PRECISE.functionParameter.number.name',
                detail: 'sheets-formula.functionList.CEILING_PRECISE.functionParameter.number.detail',
                example: '4.3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CEILING_PRECISE.functionParameter.significance.name',
                detail: 'sheets-formula.functionList.CEILING_PRECISE.functionParameter.significance.detail',
                example: '2',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.COMBIN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.COMBIN.description',
        abstract: 'sheets-formula.functionList.COMBIN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.COMBIN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.COMBIN.functionParameter.number.detail',
                example: '8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.COMBIN.functionParameter.numberChosen.name',
                detail: 'sheets-formula.functionList.COMBIN.functionParameter.numberChosen.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.COMBINA,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.COMBINA.description',
        abstract: 'sheets-formula.functionList.COMBINA.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.COMBINA.functionParameter.number.name',
                detail: 'sheets-formula.functionList.COMBINA.functionParameter.number.detail',
                example: '8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.COMBINA.functionParameter.numberChosen.name',
                detail: 'sheets-formula.functionList.COMBINA.functionParameter.numberChosen.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.COS,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.COS.description',
        abstract: 'sheets-formula.functionList.COS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.COS.functionParameter.number.name',
                detail: 'sheets-formula.functionList.COS.functionParameter.number.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.COSH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.COSH.description',
        abstract: 'sheets-formula.functionList.COSH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.COSH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.COSH.functionParameter.number.detail',
                example: '4',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.COT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.COT.description',
        abstract: 'sheets-formula.functionList.COT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.COT.functionParameter.number.name',
                detail: 'sheets-formula.functionList.COT.functionParameter.number.detail',
                example: '30',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.COTH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.COTH.description',
        abstract: 'sheets-formula.functionList.COTH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.COTH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.COTH.functionParameter.number.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.CSC,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.CSC.description',
        abstract: 'sheets-formula.functionList.CSC.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CSC.functionParameter.number.name',
                detail: 'sheets-formula.functionList.CSC.functionParameter.number.detail',
                example: '15',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.CSCH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.CSCH.description',
        abstract: 'sheets-formula.functionList.CSCH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CSCH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.CSCH.functionParameter.number.detail',
                example: '1.5',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.DECIMAL,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.DECIMAL.description',
        abstract: 'sheets-formula.functionList.DECIMAL.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.DECIMAL.functionParameter.text.name',
                detail: 'sheets-formula.functionList.DECIMAL.functionParameter.text.detail',
                example: '"FF"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.DECIMAL.functionParameter.radix.name',
                detail: 'sheets-formula.functionList.DECIMAL.functionParameter.radix.detail',
                example: '16',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.DEGREES,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.DEGREES.description',
        abstract: 'sheets-formula.functionList.DEGREES.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.DEGREES.functionParameter.angle.name',
                detail: 'sheets-formula.functionList.DEGREES.functionParameter.angle.detail',
                example: 'PI()',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.EVEN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.EVEN.description',
        abstract: 'sheets-formula.functionList.EVEN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.EVEN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.EVEN.functionParameter.number.detail',
                example: '1.5',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.EXP,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.EXP.description',
        abstract: 'sheets-formula.functionList.EXP.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.EXP.functionParameter.number.name',
                detail: 'sheets-formula.functionList.EXP.functionParameter.number.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.FACT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.FACT.description',
        abstract: 'sheets-formula.functionList.FACT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FACT.functionParameter.number.name',
                detail: 'sheets-formula.functionList.FACT.functionParameter.number.detail',
                example: '5',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.FACTDOUBLE,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.FACTDOUBLE.description',
        abstract: 'sheets-formula.functionList.FACTDOUBLE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FACTDOUBLE.functionParameter.number.name',
                detail: 'sheets-formula.functionList.FACTDOUBLE.functionParameter.number.detail',
                example: '6',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.FLOOR,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.FLOOR.description',
        abstract: 'sheets-formula.functionList.FLOOR.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FLOOR.functionParameter.number.name',
                detail: 'sheets-formula.functionList.FLOOR.functionParameter.number.detail',
                example: '3.7',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FLOOR.functionParameter.significance.name',
                detail: 'sheets-formula.functionList.FLOOR.functionParameter.significance.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.FLOOR_MATH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.FLOOR_MATH.description',
        abstract: 'sheets-formula.functionList.FLOOR_MATH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FLOOR_MATH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.FLOOR_MATH.functionParameter.number.detail',
                example: '-5.5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FLOOR_MATH.functionParameter.significance.name',
                detail: 'sheets-formula.functionList.FLOOR_MATH.functionParameter.significance.detail',
                example: '2',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FLOOR_MATH.functionParameter.mode.name',
                detail: 'sheets-formula.functionList.FLOOR_MATH.functionParameter.mode.detail',
                example: '-1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.FLOOR_PRECISE,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.FLOOR_PRECISE.description',
        abstract: 'sheets-formula.functionList.FLOOR_PRECISE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FLOOR_PRECISE.functionParameter.number.name',
                detail: 'sheets-formula.functionList.FLOOR_PRECISE.functionParameter.number.detail',
                example: '-3.2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FLOOR_PRECISE.functionParameter.significance.name',
                detail: 'sheets-formula.functionList.FLOOR_PRECISE.functionParameter.significance.detail',
                example: '-1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.GCD,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.GCD.description',
        abstract: 'sheets-formula.functionList.GCD.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.GCD.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.GCD.functionParameter.number1.detail',
                example: '5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.GCD.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.GCD.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.INT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.INT.description',
        abstract: 'sheets-formula.functionList.INT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.INT.functionParameter.number.name',
                detail: 'sheets-formula.functionList.INT.functionParameter.number.detail',
                example: '8.9',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ISO_CEILING,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ISO_CEILING.description',
        abstract: 'sheets-formula.functionList.ISO_CEILING.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ISO_CEILING.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ISO_CEILING.functionParameter.number.detail',
                example: '-4.3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ISO_CEILING.functionParameter.significance.name',
                detail: 'sheets-formula.functionList.ISO_CEILING.functionParameter.significance.detail',
                example: '2',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.LCM,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.LCM.description',
        abstract: 'sheets-formula.functionList.LCM.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.LCM.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.LCM.functionParameter.number1.detail',
                example: '5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.LCM.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.LCM.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.LN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.LN.description',
        abstract: 'sheets-formula.functionList.LN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.LN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.LN.functionParameter.number.detail',
                example: 'EXP(3)',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.LOG,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.LOG.description',
        abstract: 'sheets-formula.functionList.LOG.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.LOG.functionParameter.number.name',
                detail: 'sheets-formula.functionList.LOG.functionParameter.number.detail',
                example: '8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.LOG.functionParameter.base.name',
                detail: 'sheets-formula.functionList.LOG.functionParameter.base.detail',
                example: '2',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.LOG10,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.LOG10.description',
        abstract: 'sheets-formula.functionList.LOG10.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.LOG10.functionParameter.number.name',
                detail: 'sheets-formula.functionList.LOG10.functionParameter.number.detail',
                example: '100000',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.MDETERM,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.MDETERM.description',
        abstract: 'sheets-formula.functionList.MDETERM.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.MDETERM.functionParameter.array.name',
                detail: 'sheets-formula.functionList.MDETERM.functionParameter.array.detail',
                example: 'A1:C3',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.MINVERSE,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.MINVERSE.description',
        abstract: 'sheets-formula.functionList.MINVERSE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.MINVERSE.functionParameter.array.name',
                detail: 'sheets-formula.functionList.MINVERSE.functionParameter.array.detail',
                example: 'A1:C3',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.MMULT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.MMULT.description',
        abstract: 'sheets-formula.functionList.MMULT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.MMULT.functionParameter.array1.name',
                detail: 'sheets-formula.functionList.MMULT.functionParameter.array1.detail',
                example: 'A2:B3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.MMULT.functionParameter.array2.name',
                detail: 'sheets-formula.functionList.MMULT.functionParameter.array2.detail',
                example: 'A5:B6',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.MOD,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.MOD.description',
        abstract: 'sheets-formula.functionList.MOD.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.MOD.functionParameter.number.name',
                detail: 'sheets-formula.functionList.MOD.functionParameter.number.detail',
                example: '3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.MOD.functionParameter.divisor.name',
                detail: 'sheets-formula.functionList.MOD.functionParameter.divisor.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.MROUND,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.MROUND.description',
        abstract: 'sheets-formula.functionList.MROUND.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.MROUND.functionParameter.number.name',
                detail: 'sheets-formula.functionList.MROUND.functionParameter.number.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.MROUND.functionParameter.multiple.name',
                detail: 'sheets-formula.functionList.MROUND.functionParameter.multiple.detail',
                example: '3',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.MULTINOMIAL,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.MULTINOMIAL.description',
        abstract: 'sheets-formula.functionList.MULTINOMIAL.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.MULTINOMIAL.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.MULTINOMIAL.functionParameter.number1.detail',
                example: '5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.MULTINOMIAL.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.MULTINOMIAL.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.MUNIT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.MUNIT.description',
        abstract: 'sheets-formula.functionList.MUNIT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.MUNIT.functionParameter.dimension.name',
                detail: 'sheets-formula.functionList.MUNIT.functionParameter.dimension.detail',
                example: '3',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ODD,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ODD.description',
        abstract: 'sheets-formula.functionList.ODD.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ODD.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ODD.functionParameter.number.detail',
                example: '1.5',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.PI,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.PI.description',
        abstract: 'sheets-formula.functionList.PI.abstract',
        functionParameter: [
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.POWER,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.POWER.description',
        abstract: 'sheets-formula.functionList.POWER.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.POWER.functionParameter.number.name',
                detail: 'sheets-formula.functionList.POWER.functionParameter.number.detail',
                example: '5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.POWER.functionParameter.power.name',
                detail: 'sheets-formula.functionList.POWER.functionParameter.power.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.PRODUCT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.PRODUCT.description',
        abstract: 'sheets-formula.functionList.PRODUCT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.PRODUCT.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.PRODUCT.functionParameter.number1.detail',
                example: 'A1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.PRODUCT.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.PRODUCT.functionParameter.number2.detail',
                example: 'A2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.QUOTIENT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.QUOTIENT.description',
        abstract: 'sheets-formula.functionList.QUOTIENT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.QUOTIENT.functionParameter.numerator.name',
                detail: 'sheets-formula.functionList.QUOTIENT.functionParameter.numerator.detail',
                example: '5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.QUOTIENT.functionParameter.denominator.name',
                detail: 'sheets-formula.functionList.QUOTIENT.functionParameter.denominator.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.RADIANS,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.RADIANS.description',
        abstract: 'sheets-formula.functionList.RADIANS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.RADIANS.functionParameter.angle.name',
                detail: 'sheets-formula.functionList.RADIANS.functionParameter.angle.detail',
                example: '270',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.RAND,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.RAND.description',
        abstract: 'sheets-formula.functionList.RAND.abstract',
        functionParameter: [
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.RANDARRAY,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.RANDARRAY.description',
        abstract: 'sheets-formula.functionList.RANDARRAY.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.RANDARRAY.functionParameter.rows.name',
                detail: 'sheets-formula.functionList.RANDARRAY.functionParameter.rows.detail',
                example: '5',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RANDARRAY.functionParameter.columns.name',
                detail: 'sheets-formula.functionList.RANDARRAY.functionParameter.columns.detail',
                example: '3',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RANDARRAY.functionParameter.min.name',
                detail: 'sheets-formula.functionList.RANDARRAY.functionParameter.min.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RANDARRAY.functionParameter.max.name',
                detail: 'sheets-formula.functionList.RANDARRAY.functionParameter.max.detail',
                example: '100',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RANDARRAY.functionParameter.wholeNumber.name',
                detail: 'sheets-formula.functionList.RANDARRAY.functionParameter.wholeNumber.detail',
                example: 'TRUE',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.RANDBETWEEN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.RANDBETWEEN.description',
        abstract: 'sheets-formula.functionList.RANDBETWEEN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.RANDBETWEEN.functionParameter.bottom.name',
                detail: 'sheets-formula.functionList.RANDBETWEEN.functionParameter.bottom.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RANDBETWEEN.functionParameter.top.name',
                detail: 'sheets-formula.functionList.RANDBETWEEN.functionParameter.top.detail',
                example: '100',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ROMAN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ROMAN.description',
        abstract: 'sheets-formula.functionList.ROMAN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ROMAN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ROMAN.functionParameter.number.detail',
                example: '499',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ROMAN.functionParameter.form.name',
                detail: 'sheets-formula.functionList.ROMAN.functionParameter.form.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ROUND,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ROUND.description',
        abstract: 'sheets-formula.functionList.ROUND.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ROUND.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ROUND.functionParameter.number.detail',
                example: '2.15',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ROUND.functionParameter.numDigits.name',
                detail: 'sheets-formula.functionList.ROUND.functionParameter.numDigits.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ROUNDBANK,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ROUNDBANK.description',
        abstract: 'sheets-formula.functionList.ROUNDBANK.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ROUNDBANK.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ROUNDBANK.functionParameter.number.detail',
                example: '2.345',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ROUNDBANK.functionParameter.numDigits.name',
                detail: 'sheets-formula.functionList.ROUNDBANK.functionParameter.numDigits.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ROUNDDOWN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ROUNDDOWN.description',
        abstract: 'sheets-formula.functionList.ROUNDDOWN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ROUNDDOWN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ROUNDDOWN.functionParameter.number.detail',
                example: '3.2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ROUNDDOWN.functionParameter.numDigits.name',
                detail: 'sheets-formula.functionList.ROUNDDOWN.functionParameter.numDigits.detail',
                example: '0',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.ROUNDUP,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.ROUNDUP.description',
        abstract: 'sheets-formula.functionList.ROUNDUP.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ROUNDUP.functionParameter.number.name',
                detail: 'sheets-formula.functionList.ROUNDUP.functionParameter.number.detail',
                example: '3.2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ROUNDUP.functionParameter.numDigits.name',
                detail: 'sheets-formula.functionList.ROUNDUP.functionParameter.numDigits.detail',
                example: '0',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SEC,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SEC.description',
        abstract: 'sheets-formula.functionList.SEC.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SEC.functionParameter.number.name',
                detail: 'sheets-formula.functionList.SEC.functionParameter.number.detail',
                example: '30',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SECH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SECH.description',
        abstract: 'sheets-formula.functionList.SECH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SECH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.SECH.functionParameter.number.detail',
                example: '30',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SERIESSUM,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SERIESSUM.description',
        abstract: 'sheets-formula.functionList.SERIESSUM.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SERIESSUM.functionParameter.x.name',
                detail: 'sheets-formula.functionList.SERIESSUM.functionParameter.x.detail',
                example: '0.785398163',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SERIESSUM.functionParameter.n.name',
                detail: 'sheets-formula.functionList.SERIESSUM.functionParameter.n.detail',
                example: '0',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SERIESSUM.functionParameter.m.name',
                detail: 'sheets-formula.functionList.SERIESSUM.functionParameter.m.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SERIESSUM.functionParameter.coefficients.name',
                detail: 'sheets-formula.functionList.SERIESSUM.functionParameter.coefficients.detail',
                example: 'A1:A4',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SEQUENCE,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SEQUENCE.description',
        abstract: 'sheets-formula.functionList.SEQUENCE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SEQUENCE.functionParameter.rows.name',
                detail: 'sheets-formula.functionList.SEQUENCE.functionParameter.rows.detail',
                example: '4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SEQUENCE.functionParameter.columns.name',
                detail: 'sheets-formula.functionList.SEQUENCE.functionParameter.columns.detail',
                example: '5',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SEQUENCE.functionParameter.start.name',
                detail: 'sheets-formula.functionList.SEQUENCE.functionParameter.start.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SEQUENCE.functionParameter.step.name',
                detail: 'sheets-formula.functionList.SEQUENCE.functionParameter.step.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SIGN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SIGN.description',
        abstract: 'sheets-formula.functionList.SIGN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SIGN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.SIGN.functionParameter.number.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SIN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SIN.description',
        abstract: 'sheets-formula.functionList.SIN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SIN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.SIN.functionParameter.number.detail',
                example: '30*PI()/180',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SINH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SINH.description',
        abstract: 'sheets-formula.functionList.SINH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SINH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.SINH.functionParameter.number.detail',
                example: '0.0342*1.03',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SQRT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SQRT.description',
        abstract: 'sheets-formula.functionList.SQRT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SQRT.functionParameter.number.name',
                detail: 'sheets-formula.functionList.SQRT.functionParameter.number.detail',
                example: '16',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SQRTPI,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SQRTPI.description',
        abstract: 'sheets-formula.functionList.SQRTPI.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SQRTPI.functionParameter.number.name',
                detail: 'sheets-formula.functionList.SQRTPI.functionParameter.number.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SUBTOTAL,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SUBTOTAL.description',
        abstract: 'sheets-formula.functionList.SUBTOTAL.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SUBTOTAL.functionParameter.functionNum.name',
                detail: 'sheets-formula.functionList.SUBTOTAL.functionParameter.functionNum.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUBTOTAL.functionParameter.ref1.name',
                detail: 'sheets-formula.functionList.SUBTOTAL.functionParameter.ref1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUBTOTAL.functionParameter.ref2.name',
                detail: 'sheets-formula.functionList.SUBTOTAL.functionParameter.ref2.detail',
                example: 'B1:B20',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SUM,
        aliasFunctionName: 'sheets-formula.functionList.SUM.aliasFunctionName',
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SUM.description',
        abstract: 'sheets-formula.functionList.SUM.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SUM.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.SUM.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUM.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.SUM.functionParameter.number2.detail',
                example: 'B2:B10',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SUMIF,
        aliasFunctionName: 'sheets-formula.functionList.SUMIF.aliasFunctionName',
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SUMIF.description',
        abstract: 'sheets-formula.functionList.SUMIF.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SUMIF.functionParameter.range.name',
                detail: 'sheets-formula.functionList.SUMIF.functionParameter.range.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMIF.functionParameter.criteria.name',
                detail: 'sheets-formula.functionList.SUMIF.functionParameter.criteria.detail',
                example: '">5"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMIF.functionParameter.sumRange.name',
                detail: 'sheets-formula.functionList.SUMIF.functionParameter.sumRange.detail',
                example: 'B1:B20',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SUMIFS,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SUMIFS.description',
        abstract: 'sheets-formula.functionList.SUMIFS.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SUMIFS.functionParameter.sumRange.name',
                detail: 'sheets-formula.functionList.SUMIFS.functionParameter.sumRange.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMIFS.functionParameter.criteriaRange1.name',
                detail: 'sheets-formula.functionList.SUMIFS.functionParameter.criteriaRange1.detail',
                example: 'B1:B20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMIFS.functionParameter.criteria1.name',
                detail: 'sheets-formula.functionList.SUMIFS.functionParameter.criteria1.detail',
                example: '">10"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMIFS.functionParameter.criteriaRange2.name',
                detail: 'sheets-formula.functionList.SUMIFS.functionParameter.criteriaRange2.detail',
                example: 'C1:C20',
                require: 0,
                repeat: 1,
            },
            {
                name: 'sheets-formula.functionList.SUMIFS.functionParameter.criteria2.name',
                detail: 'sheets-formula.functionList.SUMIFS.functionParameter.criteria2.detail',
                example: '"<20"',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SUMPRODUCT,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SUMPRODUCT.description',
        abstract: 'sheets-formula.functionList.SUMPRODUCT.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SUMPRODUCT.functionParameter.array1.name',
                detail: 'sheets-formula.functionList.SUMPRODUCT.functionParameter.array1.detail',
                example: 'C2:C5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMPRODUCT.functionParameter.array2.name',
                detail: 'sheets-formula.functionList.SUMPRODUCT.functionParameter.array2.detail',
                example: 'D2:D5',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SUMSQ,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SUMSQ.description',
        abstract: 'sheets-formula.functionList.SUMSQ.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SUMSQ.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.SUMSQ.functionParameter.number1.detail',
                example: '3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMSQ.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.SUMSQ.functionParameter.number2.detail',
                example: '4',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SUMX2MY2,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SUMX2MY2.description',
        abstract: 'sheets-formula.functionList.SUMX2MY2.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SUMX2MY2.functionParameter.arrayX.name',
                detail: 'sheets-formula.functionList.SUMX2MY2.functionParameter.arrayX.detail',
                example: 'A2:A8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMX2MY2.functionParameter.arrayY.name',
                detail: 'sheets-formula.functionList.SUMX2MY2.functionParameter.arrayY.detail',
                example: 'B2:B8',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SUMX2PY2,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SUMX2PY2.description',
        abstract: 'sheets-formula.functionList.SUMX2PY2.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SUMX2PY2.functionParameter.arrayX.name',
                detail: 'sheets-formula.functionList.SUMX2PY2.functionParameter.arrayX.detail',
                example: 'A2:A8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMX2PY2.functionParameter.arrayY.name',
                detail: 'sheets-formula.functionList.SUMX2PY2.functionParameter.arrayY.detail',
                example: 'B2:B8',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.SUMXMY2,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.SUMXMY2.description',
        abstract: 'sheets-formula.functionList.SUMXMY2.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.SUMXMY2.functionParameter.arrayX.name',
                detail: 'sheets-formula.functionList.SUMXMY2.functionParameter.arrayX.detail',
                example: 'A2:A8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.SUMXMY2.functionParameter.arrayY.name',
                detail: 'sheets-formula.functionList.SUMXMY2.functionParameter.arrayY.detail',
                example: 'B2:B8',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.TAN,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.TAN.description',
        abstract: 'sheets-formula.functionList.TAN.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TAN.functionParameter.number.name',
                detail: 'sheets-formula.functionList.TAN.functionParameter.number.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.TANH,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.TANH.description',
        abstract: 'sheets-formula.functionList.TANH.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TANH.functionParameter.number.name',
                detail: 'sheets-formula.functionList.TANH.functionParameter.number.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_MATH.TRUNC,
        functionType: FunctionType.Math,
        description: 'sheets-formula.functionList.TRUNC.description',
        abstract: 'sheets-formula.functionList.TRUNC.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TRUNC.functionParameter.number.name',
                detail: 'sheets-formula.functionList.TRUNC.functionParameter.number.detail',
                example: '0.45',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TRUNC.functionParameter.numDigits.name',
                detail: 'sheets-formula.functionList.TRUNC.functionParameter.numDigits.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
];
