const INDEX_FUNCTION_NAME = 'INDEX';

const OFFSET_FUNCTION_NAME = 'OFFSET';

const INDIRECT_FUNCTION_NAME = 'INDIRECT';

export const REFERENCE_FUNCTION_SET = new Set([INDEX_FUNCTION_NAME, OFFSET_FUNCTION_NAME, INDIRECT_FUNCTION_NAME]);
