export const DEFAULT_TOKEN_TYPE_PARAMETER = 'P';

export const DEFAULT_TOKEN_TYPE_ROOT = 'R';

export const DEFAULT_TOKEN_TYPE_LAMBDA_PARAMETER = 'L';

export const DEFAULT_TOKEN_TYPE_LAMBDA_RUNTIME_PARAMETER = 'LR';
