coverage:
    status:
        project:
            default:
                target: 80%
                threshold: 1.1%
                base: auto
                if_ci_failed: error
                informational: false
                only_pulls: false
        patch:
            default:
                target: 40%
                threshold: 0
                base: auto
                if_ci_failed: error
                informational: false
                only_pulls: true
