packages:
    - common/*
    - examples
    - mockdata
    - presets
    - presets/packages/*
    - packages/*
    - tests/*
publicHoistPattern:
    - '@storybook/react'
overrides:
    '@types/react': 19.2.17
    '@types/react-dom': 19.2.3
    basic-ftp: 5.2.0
    react: 19.2.7
    react-dom: 19.2.7
