packages:
    - common/*
    - examples
    - mockdata
    - presets
    - presets/packages/*
    - packages/*
    - tests/*
publicHoistPattern:
    - '@storybook/react'
overrides:
    '@types/react': 19.2.17
    '@types/react-dom': 19.2.3
    react: 19.2.7
    react-dom: 19.2.7
# Before `pnpm >=11` in the packageManager, this file is not allowed to be modified.
