export const DEFAULT_TOKEN_TYPE_PARAMETER = 'P_1';

export const DEFAULT_TOKEN_TYPE_ROOT = 'R_1';

export const DEFAULT_TOKEN_TYPE_LAMBDA_PARAMETER = 'L_1';

export const DEFAULT_TOKEN_TYPE_LAMBDA_RUNTIME_PARAMETER = 'LR_1';

export const DEFAULT_TOKEN_TYPE_LAMBDA_OMIT_PARAMETER = 'LO_1';

export const DEFAULT_TOKEN_LET_FUNCTION_NAME = 'LET';

export const DEFAULT_TOKEN_LAMBDA_FUNCTION_NAME = 'LAMBDA';
