import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import type { SidebarConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';
import rootTsConfig from '../../tsconfig.json';

// const typedocSidebar = rootTsConfig.references
//     .filter((ref) => ref.path.startsWith('./packages/'))
//     .map((ref) => {
//         const name = ref.path.replace('./packages/', '')

//         return {
//             type: 'category',
//             label: `@univerjs/${name}`,
//             link: {
//                 type: 'doc',
//                 id: `api/${name}/index`
//             },
//             items: require(`./docs/api/${name}/typedoc-sidebar.cjs`)
//         }
//     }) as SidebarConfig

const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],
    // typedocSidebar,
};

export default sidebars;
