import fs from 'node:fs';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import type { SidebarConfig } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';
import rootTsConfig from '../../tsconfig.json';

const typedocSidebar = rootTsConfig.references
    .filter((ref) => {
        // read package.json
        try {
            const pkg = fs.readFileSync(`../../${ref.path}/package.json`, 'utf-8');
            const { private: p } = JSON.parse(pkg);
            return !p;
        } catch (e) {
            console.error(e)
        }
    })
    .map((ref) => {
        const name = ref.path.replace('./packages/', '')

        return {
            type: 'category',
            label: `@univerjs/${name}`,
            link: {
                type: 'doc',
                id: `api/${name}/index`
            },
            items: require(`./docs/api/${name}/typedoc-sidebar.cjs`)
        }
    }) as SidebarConfig

const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
    typedocSidebar,
};

export default sidebars;
