/**
 * Copyright 2023-present DreamNum Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { IFunctionInfo } from '@univerjs/engine-formula';
import { FUNCTION_NAMES_COMPATIBILITY, FunctionType } from '@univerjs/engine-formula';

export const FUNCTION_LIST_COMPATIBILITY: IFunctionInfo[] = [
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.BETADIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.BETADIST.description',
        abstract: 'sheets-formula.functionList.BETADIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.BETADIST.functionParameter.x.name',
                detail: 'sheets-formula.functionList.BETADIST.functionParameter.x.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BETADIST.functionParameter.alpha.name',
                detail: 'sheets-formula.functionList.BETADIST.functionParameter.alpha.detail',
                example: '8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BETADIST.functionParameter.beta.name',
                detail: 'sheets-formula.functionList.BETADIST.functionParameter.beta.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BETADIST.functionParameter.A.name',
                detail: 'sheets-formula.functionList.BETADIST.functionParameter.A.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BETADIST.functionParameter.B.name',
                detail: 'sheets-formula.functionList.BETADIST.functionParameter.B.detail',
                example: '3',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.BETAINV,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.BETAINV.description',
        abstract: 'sheets-formula.functionList.BETAINV.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.BETAINV.functionParameter.probability.name',
                detail: 'sheets-formula.functionList.BETAINV.functionParameter.probability.detail',
                example: '0.685470581',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BETAINV.functionParameter.alpha.name',
                detail: 'sheets-formula.functionList.BETAINV.functionParameter.alpha.detail',
                example: '8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BETAINV.functionParameter.beta.name',
                detail: 'sheets-formula.functionList.BETAINV.functionParameter.beta.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BETAINV.functionParameter.A.name',
                detail: 'sheets-formula.functionList.BETAINV.functionParameter.A.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BETAINV.functionParameter.B.name',
                detail: 'sheets-formula.functionList.BETAINV.functionParameter.B.detail',
                example: '3',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.BINOMDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.BINOMDIST.description',
        abstract: 'sheets-formula.functionList.BINOMDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.BINOMDIST.functionParameter.numberS.name',
                detail: 'sheets-formula.functionList.BINOMDIST.functionParameter.numberS.detail',
                example: '6',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BINOMDIST.functionParameter.trials.name',
                detail: 'sheets-formula.functionList.BINOMDIST.functionParameter.trials.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BINOMDIST.functionParameter.probabilityS.name',
                detail: 'sheets-formula.functionList.BINOMDIST.functionParameter.probabilityS.detail',
                example: '0.5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.BINOMDIST.functionParameter.cumulative.name',
                detail: 'sheets-formula.functionList.BINOMDIST.functionParameter.cumulative.detail',
                example: 'false',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.CHIDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.CHIDIST.description',
        abstract: 'sheets-formula.functionList.CHIDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CHIDIST.functionParameter.x.name',
                detail: 'sheets-formula.functionList.CHIDIST.functionParameter.x.detail',
                example: '0.5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CHIDIST.functionParameter.degFreedom.name',
                detail: 'sheets-formula.functionList.CHIDIST.functionParameter.degFreedom.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.CHIINV,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.CHIINV.description',
        abstract: 'sheets-formula.functionList.CHIINV.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CHIINV.functionParameter.probability.name',
                detail: 'sheets-formula.functionList.CHIINV.functionParameter.probability.detail',
                example: '0.93',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CHIINV.functionParameter.degFreedom.name',
                detail: 'sheets-formula.functionList.CHIINV.functionParameter.degFreedom.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.CHITEST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.CHITEST.description',
        abstract: 'sheets-formula.functionList.CHITEST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CHITEST.functionParameter.actualRange.name',
                detail: 'sheets-formula.functionList.CHITEST.functionParameter.actualRange.detail',
                example: 'A1:A4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CHITEST.functionParameter.expectedRange.name',
                detail: 'sheets-formula.functionList.CHITEST.functionParameter.expectedRange.detail',
                example: 'B1:B4',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.CONFIDENCE,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.CONFIDENCE.description',
        abstract: 'sheets-formula.functionList.CONFIDENCE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CONFIDENCE.functionParameter.alpha.name',
                detail: 'sheets-formula.functionList.CONFIDENCE.functionParameter.alpha.detail',
                example: '0.05',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CONFIDENCE.functionParameter.standardDev.name',
                detail: 'sheets-formula.functionList.CONFIDENCE.functionParameter.standardDev.detail',
                example: '2.5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CONFIDENCE.functionParameter.size.name',
                detail: 'sheets-formula.functionList.CONFIDENCE.functionParameter.size.detail',
                example: '50',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.COVAR,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.COVAR.description',
        abstract: 'sheets-formula.functionList.COVAR.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.COVAR.functionParameter.array1.name',
                detail: 'sheets-formula.functionList.COVAR.functionParameter.array1.detail',
                example: 'A1:A4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.COVAR.functionParameter.array2.name',
                detail: 'sheets-formula.functionList.COVAR.functionParameter.array2.detail',
                example: 'B1:B4',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.CRITBINOM,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.CRITBINOM.description',
        abstract: 'sheets-formula.functionList.CRITBINOM.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.CRITBINOM.functionParameter.trials.name',
                detail: 'sheets-formula.functionList.CRITBINOM.functionParameter.trials.detail',
                example: '6',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CRITBINOM.functionParameter.probabilityS.name',
                detail: 'sheets-formula.functionList.CRITBINOM.functionParameter.probabilityS.detail',
                example: '0.5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.CRITBINOM.functionParameter.alpha.name',
                detail: 'sheets-formula.functionList.CRITBINOM.functionParameter.alpha.detail',
                example: '0.75',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.EXPONDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.EXPONDIST.description',
        abstract: 'sheets-formula.functionList.EXPONDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.EXPONDIST.functionParameter.x.name',
                detail: 'sheets-formula.functionList.EXPONDIST.functionParameter.x.detail',
                example: '0.2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.EXPONDIST.functionParameter.lambda.name',
                detail: 'sheets-formula.functionList.EXPONDIST.functionParameter.lambda.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.EXPONDIST.functionParameter.cumulative.name',
                detail: 'sheets-formula.functionList.EXPONDIST.functionParameter.cumulative.detail',
                example: 'true',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.FDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.FDIST.description',
        abstract: 'sheets-formula.functionList.FDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FDIST.functionParameter.x.name',
                detail: 'sheets-formula.functionList.FDIST.functionParameter.x.detail',
                example: '15.2069',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FDIST.functionParameter.degFreedom1.name',
                detail: 'sheets-formula.functionList.FDIST.functionParameter.degFreedom1.detail',
                example: '6',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FDIST.functionParameter.degFreedom2.name',
                detail: 'sheets-formula.functionList.FDIST.functionParameter.degFreedom2.detail',
                example: '4',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.FINV,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.FINV.description',
        abstract: 'sheets-formula.functionList.FINV.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FINV.functionParameter.probability.name',
                detail: 'sheets-formula.functionList.FINV.functionParameter.probability.detail',
                example: '0.01',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FINV.functionParameter.degFreedom1.name',
                detail: 'sheets-formula.functionList.FINV.functionParameter.degFreedom1.detail',
                example: '6',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FINV.functionParameter.degFreedom2.name',
                detail: 'sheets-formula.functionList.FINV.functionParameter.degFreedom2.detail',
                example: '4',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.FTEST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.FTEST.description',
        abstract: 'sheets-formula.functionList.FTEST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.FTEST.functionParameter.array1.name',
                detail: 'sheets-formula.functionList.FTEST.functionParameter.array1.detail',
                example: 'A1:A4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.FTEST.functionParameter.array2.name',
                detail: 'sheets-formula.functionList.FTEST.functionParameter.array2.detail',
                example: 'B1:B4',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.GAMMADIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.GAMMADIST.description',
        abstract: 'sheets-formula.functionList.GAMMADIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.GAMMADIST.functionParameter.x.name',
                detail: 'sheets-formula.functionList.GAMMADIST.functionParameter.x.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.GAMMADIST.functionParameter.alpha.name',
                detail: 'sheets-formula.functionList.GAMMADIST.functionParameter.alpha.detail',
                example: '8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.GAMMADIST.functionParameter.beta.name',
                detail: 'sheets-formula.functionList.GAMMADIST.functionParameter.beta.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.GAMMADIST.functionParameter.cumulative.name',
                detail: 'sheets-formula.functionList.GAMMADIST.functionParameter.cumulative.detail',
                example: 'true',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.GAMMAINV,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.GAMMAINV.description',
        abstract: 'sheets-formula.functionList.GAMMAINV.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.GAMMAINV.functionParameter.probability.name',
                detail: 'sheets-formula.functionList.GAMMAINV.functionParameter.probability.detail',
                example: '0.068094',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.GAMMAINV.functionParameter.alpha.name',
                detail: 'sheets-formula.functionList.GAMMAINV.functionParameter.alpha.detail',
                example: '9',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.GAMMAINV.functionParameter.beta.name',
                detail: 'sheets-formula.functionList.GAMMAINV.functionParameter.beta.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.HYPGEOMDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.HYPGEOMDIST.description',
        abstract: 'sheets-formula.functionList.HYPGEOMDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.HYPGEOMDIST.functionParameter.sampleS.name',
                detail: 'sheets-formula.functionList.HYPGEOMDIST.functionParameter.sampleS.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.HYPGEOMDIST.functionParameter.numberSample.name',
                detail: 'sheets-formula.functionList.HYPGEOMDIST.functionParameter.numberSample.detail',
                example: '4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.HYPGEOMDIST.functionParameter.populationS.name',
                detail: 'sheets-formula.functionList.HYPGEOMDIST.functionParameter.populationS.detail',
                example: '8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.HYPGEOMDIST.functionParameter.numberPop.name',
                detail: 'sheets-formula.functionList.HYPGEOMDIST.functionParameter.numberPop.detail',
                example: '20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.LOGINV,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.LOGINV.description',
        abstract: 'sheets-formula.functionList.LOGINV.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.LOGINV.functionParameter.probability.name',
                detail: 'sheets-formula.functionList.LOGINV.functionParameter.probability.detail',
                example: '0.908789',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.LOGINV.functionParameter.mean.name',
                detail: 'sheets-formula.functionList.LOGINV.functionParameter.mean.detail',
                example: '40',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.LOGINV.functionParameter.standardDev.name',
                detail: 'sheets-formula.functionList.LOGINV.functionParameter.standardDev.detail',
                example: '1.5',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.LOGNORMDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.LOGNORMDIST.description',
        abstract: 'sheets-formula.functionList.LOGNORMDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.LOGNORMDIST.functionParameter.x.name',
                detail: 'sheets-formula.functionList.LOGNORMDIST.functionParameter.x.detail',
                example: '42',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.LOGNORMDIST.functionParameter.mean.name',
                detail: 'sheets-formula.functionList.LOGNORMDIST.functionParameter.mean.detail',
                example: '40',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.LOGNORMDIST.functionParameter.standardDev.name',
                detail: 'sheets-formula.functionList.LOGNORMDIST.functionParameter.standardDev.detail',
                example: '1.5',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.MODE,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.MODE.description',
        abstract: 'sheets-formula.functionList.MODE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.MODE.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.MODE.functionParameter.number1.detail',
                example: 'A1:A4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.MODE.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.MODE.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.NEGBINOMDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.NEGBINOMDIST.description',
        abstract: 'sheets-formula.functionList.NEGBINOMDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.NEGBINOMDIST.functionParameter.numberF.name',
                detail: 'sheets-formula.functionList.NEGBINOMDIST.functionParameter.numberF.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.NEGBINOMDIST.functionParameter.numberS.name',
                detail: 'sheets-formula.functionList.NEGBINOMDIST.functionParameter.numberS.detail',
                example: '5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.NEGBINOMDIST.functionParameter.probabilityS.name',
                detail: 'sheets-formula.functionList.NEGBINOMDIST.functionParameter.probabilityS.detail',
                example: '0.25',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.NORMDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.NORMDIST.description',
        abstract: 'sheets-formula.functionList.NORMDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.NORMDIST.functionParameter.x.name',
                detail: 'sheets-formula.functionList.NORMDIST.functionParameter.x.detail',
                example: '42',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.NORMDIST.functionParameter.mean.name',
                detail: 'sheets-formula.functionList.NORMDIST.functionParameter.mean.detail',
                example: '40',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.NORMDIST.functionParameter.standardDev.name',
                detail: 'sheets-formula.functionList.NORMDIST.functionParameter.standardDev.detail',
                example: '1.5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.NORMDIST.functionParameter.cumulative.name',
                detail: 'sheets-formula.functionList.NORMDIST.functionParameter.cumulative.detail',
                example: 'true',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.NORMINV,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.NORMINV.description',
        abstract: 'sheets-formula.functionList.NORMINV.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.NORMINV.functionParameter.probability.name',
                detail: 'sheets-formula.functionList.NORMINV.functionParameter.probability.detail',
                example: '0.908789',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.NORMINV.functionParameter.mean.name',
                detail: 'sheets-formula.functionList.NORMINV.functionParameter.mean.detail',
                example: '40',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.NORMINV.functionParameter.standardDev.name',
                detail: 'sheets-formula.functionList.NORMINV.functionParameter.standardDev.detail',
                example: '1.5',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.NORMSDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.NORMSDIST.description',
        abstract: 'sheets-formula.functionList.NORMSDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.NORMSDIST.functionParameter.z.name',
                detail: 'sheets-formula.functionList.NORMSDIST.functionParameter.z.detail',
                example: '1.333333',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.NORMSINV,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.NORMSINV.description',
        abstract: 'sheets-formula.functionList.NORMSINV.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.NORMSINV.functionParameter.probability.name',
                detail: 'sheets-formula.functionList.NORMSINV.functionParameter.probability.detail',
                example: '0.908789',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.PERCENTILE,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.PERCENTILE.description',
        abstract: 'sheets-formula.functionList.PERCENTILE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.PERCENTILE.functionParameter.array.name',
                detail: 'sheets-formula.functionList.PERCENTILE.functionParameter.array.detail',
                example: 'A1:A4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.PERCENTILE.functionParameter.k.name',
                detail: 'sheets-formula.functionList.PERCENTILE.functionParameter.k.detail',
                example: '0.3',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.PERCENTRANK,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.PERCENTRANK.description',
        abstract: 'sheets-formula.functionList.PERCENTRANK.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.PERCENTRANK.functionParameter.array.name',
                detail: 'sheets-formula.functionList.PERCENTRANK.functionParameter.array.detail',
                example: 'A1:A4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.PERCENTRANK.functionParameter.x.name',
                detail: 'sheets-formula.functionList.PERCENTRANK.functionParameter.x.detail',
                example: '1.5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.PERCENTRANK.functionParameter.significance.name',
                detail: 'sheets-formula.functionList.PERCENTRANK.functionParameter.significance.detail',
                example: '3',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.POISSON,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.POISSON.description',
        abstract: 'sheets-formula.functionList.POISSON.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.POISSON.functionParameter.x.name',
                detail: 'sheets-formula.functionList.POISSON.functionParameter.x.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.POISSON.functionParameter.mean.name',
                detail: 'sheets-formula.functionList.POISSON.functionParameter.mean.detail',
                example: '5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.POISSON.functionParameter.cumulative.name',
                detail: 'sheets-formula.functionList.POISSON.functionParameter.cumulative.detail',
                example: 'true',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.QUARTILE,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.QUARTILE.description',
        abstract: 'sheets-formula.functionList.QUARTILE.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.QUARTILE.functionParameter.array.name',
                detail: 'sheets-formula.functionList.QUARTILE.functionParameter.array.detail',
                example: 'A1:A4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.QUARTILE.functionParameter.quart.name',
                detail: 'sheets-formula.functionList.QUARTILE.functionParameter.quart.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.RANK,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.RANK.description',
        abstract: 'sheets-formula.functionList.RANK.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.RANK.functionParameter.number.name',
                detail: 'sheets-formula.functionList.RANK.functionParameter.number.detail',
                example: 'A3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RANK.functionParameter.ref.name',
                detail: 'sheets-formula.functionList.RANK.functionParameter.ref.detail',
                example: 'A2:A6',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.RANK.functionParameter.order.name',
                detail: 'sheets-formula.functionList.RANK.functionParameter.order.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.STDEV,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.STDEV.description',
        abstract: 'sheets-formula.functionList.STDEV.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.STDEV.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.STDEV.functionParameter.number1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.STDEV.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.STDEV.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.STDEVP,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.STDEVP.description',
        abstract: 'sheets-formula.functionList.STDEVP.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.STDEVP.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.STDEVP.functionParameter.number1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.STDEVP.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.STDEVP.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.TDIST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.TDIST.description',
        abstract: 'sheets-formula.functionList.TDIST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TDIST.functionParameter.x.name',
                detail: 'sheets-formula.functionList.TDIST.functionParameter.x.detail',
                example: '8',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TDIST.functionParameter.degFreedom.name',
                detail: 'sheets-formula.functionList.TDIST.functionParameter.degFreedom.detail',
                example: '3',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TDIST.functionParameter.tails.name',
                detail: 'sheets-formula.functionList.TDIST.functionParameter.tails.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.TINV,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.TINV.description',
        abstract: 'sheets-formula.functionList.TINV.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TINV.functionParameter.probability.name',
                detail: 'sheets-formula.functionList.TINV.functionParameter.probability.detail',
                example: '0.75',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TINV.functionParameter.degFreedom.name',
                detail: 'sheets-formula.functionList.TINV.functionParameter.degFreedom.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.TTEST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.TTEST.description',
        abstract: 'sheets-formula.functionList.TTEST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.TTEST.functionParameter.array1.name',
                detail: 'sheets-formula.functionList.TTEST.functionParameter.array1.detail',
                example: 'A1:A4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TTEST.functionParameter.array2.name',
                detail: 'sheets-formula.functionList.TTEST.functionParameter.array2.detail',
                example: 'B1:B4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TTEST.functionParameter.tails.name',
                detail: 'sheets-formula.functionList.TTEST.functionParameter.tails.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.TTEST.functionParameter.type.name',
                detail: 'sheets-formula.functionList.TTEST.functionParameter.type.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.VAR,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.VAR.description',
        abstract: 'sheets-formula.functionList.VAR.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.VAR.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.VAR.functionParameter.number1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.VAR.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.VAR.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.VARP,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.VARP.description',
        abstract: 'sheets-formula.functionList.VARP.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.VARP.functionParameter.number1.name',
                detail: 'sheets-formula.functionList.VARP.functionParameter.number1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.VARP.functionParameter.number2.name',
                detail: 'sheets-formula.functionList.VARP.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.WEIBULL,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.WEIBULL.description',
        abstract: 'sheets-formula.functionList.WEIBULL.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.WEIBULL.functionParameter.x.name',
                detail: 'sheets-formula.functionList.WEIBULL.functionParameter.x.detail',
                example: '105',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.WEIBULL.functionParameter.alpha.name',
                detail: 'sheets-formula.functionList.WEIBULL.functionParameter.alpha.detail',
                example: '20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.WEIBULL.functionParameter.beta.name',
                detail: 'sheets-formula.functionList.WEIBULL.functionParameter.beta.detail',
                example: '100',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.WEIBULL.functionParameter.cumulative.name',
                detail: 'sheets-formula.functionList.WEIBULL.functionParameter.cumulative.detail',
                example: 'true',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_COMPATIBILITY.ZTEST,
        functionType: FunctionType.Compatibility,
        description: 'sheets-formula.functionList.ZTEST.description',
        abstract: 'sheets-formula.functionList.ZTEST.abstract',
        functionParameter: [
            {
                name: 'sheets-formula.functionList.ZTEST.functionParameter.array.name',
                detail: 'sheets-formula.functionList.ZTEST.functionParameter.array.detail',
                example: 'A2:A11',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ZTEST.functionParameter.x.name',
                detail: 'sheets-formula.functionList.ZTEST.functionParameter.x.detail',
                example: '4',
                require: 1,
                repeat: 0,
            },
            {
                name: 'sheets-formula.functionList.ZTEST.functionParameter.sigma.name',
                detail: 'sheets-formula.functionList.ZTEST.functionParameter.sigma.detail',
                example: '10',
                require: 0,
                repeat: 0,
            },
        ],
    },
];
