/**
 * Copyright 2023-present DreamNum Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { FUNCTION_NAMES_FINANCIAL, FunctionType, type IFunctionInfo } from '@univerjs/engine-formula';

export const FUNCTION_LIST_FINANCIAL: IFunctionInfo[] = [
    {
        functionName: FUNCTION_NAMES_FINANCIAL.ACCRINT,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.ACCRINT.description',
        abstract: 'formula.functionList.ACCRINT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.ACCRINT.functionParameter.issue.name',
                detail: 'formula.functionList.ACCRINT.functionParameter.issue.detail',
                example: '39508',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINT.functionParameter.firstInterest.name',
                detail: 'formula.functionList.ACCRINT.functionParameter.firstInterest.detail',
                example: '39691',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINT.functionParameter.settlement.name',
                detail: 'formula.functionList.ACCRINT.functionParameter.settlement.detail',
                example: '39569',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINT.functionParameter.rate.name',
                detail: 'formula.functionList.ACCRINT.functionParameter.rate.detail',
                example: '0.1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINT.functionParameter.par.name',
                detail: 'formula.functionList.ACCRINT.functionParameter.par.detail',
                example: '1000',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINT.functionParameter.frequency.name',
                detail: 'formula.functionList.ACCRINT.functionParameter.frequency.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINT.functionParameter.basis.name',
                detail: 'formula.functionList.ACCRINT.functionParameter.basis.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINT.functionParameter.calcMethod.name',
                detail: 'formula.functionList.ACCRINT.functionParameter.calcMethod.detail',
                example: 'true',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.ACCRINTM,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.ACCRINTM.description',
        abstract: 'formula.functionList.ACCRINTM.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.ACCRINTM.functionParameter.issue.name',
                detail: 'formula.functionList.ACCRINTM.functionParameter.issue.detail',
                example: '"2008-4-1"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINTM.functionParameter.settlement.name',
                detail: 'formula.functionList.ACCRINTM.functionParameter.settlement.detail',
                example: '"2008-6-15"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINTM.functionParameter.rate.name',
                detail: 'formula.functionList.ACCRINTM.functionParameter.rate.detail',
                example: '0.1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINTM.functionParameter.par.name',
                detail: 'formula.functionList.ACCRINTM.functionParameter.par.detail',
                example: '1000',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ACCRINTM.functionParameter.basis.name',
                detail: 'formula.functionList.ACCRINTM.functionParameter.basis.detail',
                example: '3',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.AMORDEGRC,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.AMORDEGRC.description',
        abstract: 'formula.functionList.AMORDEGRC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.AMORDEGRC.functionParameter.number1.name',
                detail: 'formula.functionList.AMORDEGRC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AMORDEGRC.functionParameter.number2.name',
                detail: 'formula.functionList.AMORDEGRC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.AMORLINC,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.AMORLINC.description',
        abstract: 'formula.functionList.AMORLINC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.AMORLINC.functionParameter.cost.name',
                detail: 'formula.functionList.AMORLINC.functionParameter.cost.detail',
                example: '2400',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AMORLINC.functionParameter.datePurchased.name',
                detail: 'formula.functionList.AMORLINC.functionParameter.datePurchased.detail',
                example: '39679',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AMORLINC.functionParameter.firstPeriod.name',
                detail: 'formula.functionList.AMORLINC.functionParameter.firstPeriod.detail',
                example: '39813',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AMORLINC.functionParameter.salvage.name',
                detail: 'formula.functionList.AMORLINC.functionParameter.salvage.detail',
                example: '300',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AMORLINC.functionParameter.period.name',
                detail: 'formula.functionList.AMORLINC.functionParameter.period.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AMORLINC.functionParameter.rate.name',
                detail: 'formula.functionList.AMORLINC.functionParameter.rate.detail',
                example: '0.15',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AMORLINC.functionParameter.basis.name',
                detail: 'formula.functionList.AMORLINC.functionParameter.basis.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.COUPDAYBS,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.COUPDAYBS.description',
        abstract: 'formula.functionList.COUPDAYBS.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUPDAYBS.functionParameter.settlement.name',
                detail: 'formula.functionList.COUPDAYBS.functionParameter.settlement.detail',
                example: '"2011-1-25"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPDAYBS.functionParameter.maturity.name',
                detail: 'formula.functionList.COUPDAYBS.functionParameter.maturity.detail',
                example: '"2011-11-15"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPDAYBS.functionParameter.frequency.name',
                detail: 'formula.functionList.COUPDAYBS.functionParameter.frequency.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPDAYBS.functionParameter.basis.name',
                detail: 'formula.functionList.COUPDAYBS.functionParameter.basis.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.COUPDAYS,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.COUPDAYS.description',
        abstract: 'formula.functionList.COUPDAYS.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUPDAYS.functionParameter.settlement.name',
                detail: 'formula.functionList.COUPDAYS.functionParameter.settlement.detail',
                example: '"2011-1-25"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPDAYS.functionParameter.maturity.name',
                detail: 'formula.functionList.COUPDAYS.functionParameter.maturity.detail',
                example: '"2011-11-15"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPDAYS.functionParameter.frequency.name',
                detail: 'formula.functionList.COUPDAYS.functionParameter.frequency.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPDAYS.functionParameter.basis.name',
                detail: 'formula.functionList.COUPDAYS.functionParameter.basis.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.COUPDAYSNC,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.COUPDAYSNC.description',
        abstract: 'formula.functionList.COUPDAYSNC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUPDAYSNC.functionParameter.settlement.name',
                detail: 'formula.functionList.COUPDAYSNC.functionParameter.settlement.detail',
                example: '"2011-1-25"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPDAYSNC.functionParameter.maturity.name',
                detail: 'formula.functionList.COUPDAYSNC.functionParameter.maturity.detail',
                example: '"2011-11-15"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPDAYSNC.functionParameter.frequency.name',
                detail: 'formula.functionList.COUPDAYSNC.functionParameter.frequency.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPDAYSNC.functionParameter.basis.name',
                detail: 'formula.functionList.COUPDAYSNC.functionParameter.basis.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.COUPNCD,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.COUPNCD.description',
        abstract: 'formula.functionList.COUPNCD.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUPNCD.functionParameter.settlement.name',
                detail: 'formula.functionList.COUPNCD.functionParameter.settlement.detail',
                example: '"2011-1-25"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPNCD.functionParameter.maturity.name',
                detail: 'formula.functionList.COUPNCD.functionParameter.maturity.detail',
                example: '"2011-11-15"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPNCD.functionParameter.frequency.name',
                detail: 'formula.functionList.COUPNCD.functionParameter.frequency.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPNCD.functionParameter.basis.name',
                detail: 'formula.functionList.COUPNCD.functionParameter.basis.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.COUPNUM,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.COUPNUM.description',
        abstract: 'formula.functionList.COUPNUM.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUPNUM.functionParameter.settlement.name',
                detail: 'formula.functionList.COUPNUM.functionParameter.settlement.detail',
                example: '"2011-1-25"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPNUM.functionParameter.maturity.name',
                detail: 'formula.functionList.COUPNUM.functionParameter.maturity.detail',
                example: '"2011-11-15"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPNUM.functionParameter.frequency.name',
                detail: 'formula.functionList.COUPNUM.functionParameter.frequency.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPNUM.functionParameter.basis.name',
                detail: 'formula.functionList.COUPNUM.functionParameter.basis.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.COUPPCD,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.COUPPCD.description',
        abstract: 'formula.functionList.COUPPCD.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUPPCD.functionParameter.settlement.name',
                detail: 'formula.functionList.COUPPCD.functionParameter.settlement.detail',
                example: '"2011-1-25"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPPCD.functionParameter.maturity.name',
                detail: 'formula.functionList.COUPPCD.functionParameter.maturity.detail',
                example: '"2011-11-15"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPPCD.functionParameter.frequency.name',
                detail: 'formula.functionList.COUPPCD.functionParameter.frequency.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUPPCD.functionParameter.basis.name',
                detail: 'formula.functionList.COUPPCD.functionParameter.basis.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.CUMIPMT,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.CUMIPMT.description',
        abstract: 'formula.functionList.CUMIPMT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CUMIPMT.functionParameter.rate.name',
                detail: 'formula.functionList.CUMIPMT.functionParameter.rate.detail',
                example: '0.09/12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMIPMT.functionParameter.nper.name',
                detail: 'formula.functionList.CUMIPMT.functionParameter.nper.detail',
                example: '30*12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMIPMT.functionParameter.pv.name',
                detail: 'formula.functionList.CUMIPMT.functionParameter.pv.detail',
                example: '125000',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMIPMT.functionParameter.startPeriod.name',
                detail: 'formula.functionList.CUMIPMT.functionParameter.startPeriod.detail',
                example: '13',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMIPMT.functionParameter.endPeriod.name',
                detail: 'formula.functionList.CUMIPMT.functionParameter.endPeriod.detail',
                example: '24',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMIPMT.functionParameter.type.name',
                detail: 'formula.functionList.CUMIPMT.functionParameter.type.detail',
                example: '0',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.CUMPRINC,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.CUMPRINC.description',
        abstract: 'formula.functionList.CUMPRINC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CUMPRINC.functionParameter.rate.name',
                detail: 'formula.functionList.CUMPRINC.functionParameter.rate.detail',
                example: '0.09/12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMPRINC.functionParameter.nper.name',
                detail: 'formula.functionList.CUMPRINC.functionParameter.nper.detail',
                example: '30*12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMPRINC.functionParameter.pv.name',
                detail: 'formula.functionList.CUMPRINC.functionParameter.pv.detail',
                example: '125000',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMPRINC.functionParameter.startPeriod.name',
                detail: 'formula.functionList.CUMPRINC.functionParameter.startPeriod.detail',
                example: '13',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMPRINC.functionParameter.endPeriod.name',
                detail: 'formula.functionList.CUMPRINC.functionParameter.endPeriod.detail',
                example: '24',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CUMPRINC.functionParameter.type.name',
                detail: 'formula.functionList.CUMPRINC.functionParameter.type.detail',
                example: '0',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.DB,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.DB.description',
        abstract: 'formula.functionList.DB.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.DB.functionParameter.number1.name',
                detail: 'formula.functionList.DB.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.DB.functionParameter.number2.name',
                detail: 'formula.functionList.DB.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.DDB,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.DDB.description',
        abstract: 'formula.functionList.DDB.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.DDB.functionParameter.number1.name',
                detail: 'formula.functionList.DDB.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.DDB.functionParameter.number2.name',
                detail: 'formula.functionList.DDB.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.DISC,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.DISC.description',
        abstract: 'formula.functionList.DISC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.DISC.functionParameter.number1.name',
                detail: 'formula.functionList.DISC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.DISC.functionParameter.number2.name',
                detail: 'formula.functionList.DISC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.DOLLARDE,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.DOLLARDE.description',
        abstract: 'formula.functionList.DOLLARDE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.DOLLARDE.functionParameter.number1.name',
                detail: 'formula.functionList.DOLLARDE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.DOLLARDE.functionParameter.number2.name',
                detail: 'formula.functionList.DOLLARDE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.DOLLARFR,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.DOLLARFR.description',
        abstract: 'formula.functionList.DOLLARFR.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.DOLLARFR.functionParameter.number1.name',
                detail: 'formula.functionList.DOLLARFR.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.DOLLARFR.functionParameter.number2.name',
                detail: 'formula.functionList.DOLLARFR.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.DURATION,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.DURATION.description',
        abstract: 'formula.functionList.DURATION.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.DURATION.functionParameter.number1.name',
                detail: 'formula.functionList.DURATION.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.DURATION.functionParameter.number2.name',
                detail: 'formula.functionList.DURATION.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.EFFECT,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.EFFECT.description',
        abstract: 'formula.functionList.EFFECT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.EFFECT.functionParameter.number1.name',
                detail: 'formula.functionList.EFFECT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.EFFECT.functionParameter.number2.name',
                detail: 'formula.functionList.EFFECT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.FV,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.FV.description',
        abstract: 'formula.functionList.FV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FV.functionParameter.rate.name',
                detail: 'formula.functionList.FV.functionParameter.rate.detail',
                example: '0.06/12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FV.functionParameter.nper.name',
                detail: 'formula.functionList.FV.functionParameter.nper.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FV.functionParameter.pmt.name',
                detail: 'formula.functionList.FV.functionParameter.pmt.detail',
                example: '-200',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FV.functionParameter.pv.name',
                detail: 'formula.functionList.FV.functionParameter.pv.detail',
                example: '-500',
                require: 0,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FV.functionParameter.type.name',
                detail: 'formula.functionList.FV.functionParameter.type.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.FVSCHEDULE,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.FVSCHEDULE.description',
        abstract: 'formula.functionList.FVSCHEDULE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FVSCHEDULE.functionParameter.number1.name',
                detail: 'formula.functionList.FVSCHEDULE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FVSCHEDULE.functionParameter.number2.name',
                detail: 'formula.functionList.FVSCHEDULE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.INTRATE,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.INTRATE.description',
        abstract: 'formula.functionList.INTRATE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.INTRATE.functionParameter.number1.name',
                detail: 'formula.functionList.INTRATE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.INTRATE.functionParameter.number2.name',
                detail: 'formula.functionList.INTRATE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.IPMT,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.IPMT.description',
        abstract: 'formula.functionList.IPMT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.IPMT.functionParameter.rate.name',
                detail: 'formula.functionList.IPMT.functionParameter.rate.detail',
                example: '0.1/12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.IPMT.functionParameter.per.name',
                detail: 'formula.functionList.IPMT.functionParameter.per.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.IPMT.functionParameter.nper.name',
                detail: 'formula.functionList.IPMT.functionParameter.nper.detail',
                example: '3*12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.IPMT.functionParameter.pv.name',
                detail: 'formula.functionList.IPMT.functionParameter.pv.detail',
                example: '80000',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.IPMT.functionParameter.fv.name',
                detail: 'formula.functionList.IPMT.functionParameter.fv.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
            {
                name: 'formula.functionList.IPMT.functionParameter.type.name',
                detail: 'formula.functionList.IPMT.functionParameter.type.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.IRR,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.IRR.description',
        abstract: 'formula.functionList.IRR.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.IRR.functionParameter.number1.name',
                detail: 'formula.functionList.IRR.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.IRR.functionParameter.number2.name',
                detail: 'formula.functionList.IRR.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.ISPMT,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.ISPMT.description',
        abstract: 'formula.functionList.ISPMT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.ISPMT.functionParameter.rate.name',
                detail: 'formula.functionList.ISPMT.functionParameter.rate.detail',
                example: '0.1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ISPMT.functionParameter.per.name',
                detail: 'formula.functionList.ISPMT.functionParameter.per.detail',
                example: '2',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ISPMT.functionParameter.nper.name',
                detail: 'formula.functionList.ISPMT.functionParameter.nper.detail',
                example: '5',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ISPMT.functionParameter.pv.name',
                detail: 'formula.functionList.ISPMT.functionParameter.pv.detail',
                example: '1000',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.MDURATION,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.MDURATION.description',
        abstract: 'formula.functionList.MDURATION.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MDURATION.functionParameter.number1.name',
                detail: 'formula.functionList.MDURATION.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MDURATION.functionParameter.number2.name',
                detail: 'formula.functionList.MDURATION.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.MIRR,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.MIRR.description',
        abstract: 'formula.functionList.MIRR.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MIRR.functionParameter.number1.name',
                detail: 'formula.functionList.MIRR.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MIRR.functionParameter.number2.name',
                detail: 'formula.functionList.MIRR.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.NOMINAL,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.NOMINAL.description',
        abstract: 'formula.functionList.NOMINAL.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.NOMINAL.functionParameter.number1.name',
                detail: 'formula.functionList.NOMINAL.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NOMINAL.functionParameter.number2.name',
                detail: 'formula.functionList.NOMINAL.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.NPER,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.NPER.description',
        abstract: 'formula.functionList.NPER.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.NPER.functionParameter.rate.name',
                detail: 'formula.functionList.NPER.functionParameter.rate.detail',
                example: '0.12/12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NPER.functionParameter.pmt.name',
                detail: 'formula.functionList.NPER.functionParameter.pmt.detail',
                example: '-100',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NPER.functionParameter.pv.name',
                detail: 'formula.functionList.NPER.functionParameter.pv.detail',
                example: '-1000',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NPER.functionParameter.fv.name',
                detail: 'formula.functionList.NPER.functionParameter.fv.detail',
                example: '10000',
                require: 0,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NPER.functionParameter.type.name',
                detail: 'formula.functionList.NPER.functionParameter.type.detail',
                example: '1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.NPV,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.NPV.description',
        abstract: 'formula.functionList.NPV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.NPV.functionParameter.number1.name',
                detail: 'formula.functionList.NPV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NPV.functionParameter.number2.name',
                detail: 'formula.functionList.NPV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.ODDFPRICE,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.ODDFPRICE.description',
        abstract: 'formula.functionList.ODDFPRICE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.ODDFPRICE.functionParameter.number1.name',
                detail: 'formula.functionList.ODDFPRICE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ODDFPRICE.functionParameter.number2.name',
                detail: 'formula.functionList.ODDFPRICE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.ODDFYIELD,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.ODDFYIELD.description',
        abstract: 'formula.functionList.ODDFYIELD.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.ODDFYIELD.functionParameter.number1.name',
                detail: 'formula.functionList.ODDFYIELD.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ODDFYIELD.functionParameter.number2.name',
                detail: 'formula.functionList.ODDFYIELD.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.ODDLPRICE,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.ODDLPRICE.description',
        abstract: 'formula.functionList.ODDLPRICE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.ODDLPRICE.functionParameter.number1.name',
                detail: 'formula.functionList.ODDLPRICE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ODDLPRICE.functionParameter.number2.name',
                detail: 'formula.functionList.ODDLPRICE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.ODDLYIELD,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.ODDLYIELD.description',
        abstract: 'formula.functionList.ODDLYIELD.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.ODDLYIELD.functionParameter.number1.name',
                detail: 'formula.functionList.ODDLYIELD.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.ODDLYIELD.functionParameter.number2.name',
                detail: 'formula.functionList.ODDLYIELD.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.PDURATION,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.PDURATION.description',
        abstract: 'formula.functionList.PDURATION.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PDURATION.functionParameter.number1.name',
                detail: 'formula.functionList.PDURATION.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PDURATION.functionParameter.number2.name',
                detail: 'formula.functionList.PDURATION.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.PMT,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.PMT.description',
        abstract: 'formula.functionList.PMT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PMT.functionParameter.rate.name',
                detail: 'formula.functionList.PMT.functionParameter.rate.detail',
                example: '0.08/12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PMT.functionParameter.nper.name',
                detail: 'formula.functionList.PMT.functionParameter.nper.detail',
                example: '10',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PMT.functionParameter.pv.name',
                detail: 'formula.functionList.PMT.functionParameter.pv.detail',
                example: '10000',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PMT.functionParameter.fv.name',
                detail: 'formula.functionList.PMT.functionParameter.fv.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PMT.functionParameter.type.name',
                detail: 'formula.functionList.PMT.functionParameter.type.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.PPMT,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.PPMT.description',
        abstract: 'formula.functionList.PPMT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PPMT.functionParameter.rate.name',
                detail: 'formula.functionList.PPMT.functionParameter.rate.detail',
                example: '0.1/12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PPMT.functionParameter.per.name',
                detail: 'formula.functionList.PPMT.functionParameter.per.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PPMT.functionParameter.nper.name',
                detail: 'formula.functionList.PPMT.functionParameter.nper.detail',
                example: '3*12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PPMT.functionParameter.pv.name',
                detail: 'formula.functionList.PPMT.functionParameter.pv.detail',
                example: '80000',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PPMT.functionParameter.fv.name',
                detail: 'formula.functionList.PPMT.functionParameter.fv.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PPMT.functionParameter.type.name',
                detail: 'formula.functionList.PPMT.functionParameter.type.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.PRICE,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.PRICE.description',
        abstract: 'formula.functionList.PRICE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PRICE.functionParameter.number1.name',
                detail: 'formula.functionList.PRICE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PRICE.functionParameter.number2.name',
                detail: 'formula.functionList.PRICE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.PRICEDISC,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.PRICEDISC.description',
        abstract: 'formula.functionList.PRICEDISC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PRICEDISC.functionParameter.number1.name',
                detail: 'formula.functionList.PRICEDISC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PRICEDISC.functionParameter.number2.name',
                detail: 'formula.functionList.PRICEDISC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.PRICEMAT,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.PRICEMAT.description',
        abstract: 'formula.functionList.PRICEMAT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PRICEMAT.functionParameter.number1.name',
                detail: 'formula.functionList.PRICEMAT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PRICEMAT.functionParameter.number2.name',
                detail: 'formula.functionList.PRICEMAT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.PV,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.PV.description',
        abstract: 'formula.functionList.PV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PV.functionParameter.rate.name',
                detail: 'formula.functionList.PV.functionParameter.rate.detail',
                example: '0.02',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PV.functionParameter.nper.name',
                detail: 'formula.functionList.PV.functionParameter.nper.detail',
                example: '12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PV.functionParameter.pmt.name',
                detail: 'formula.functionList.PV.functionParameter.pmt.detail',
                example: '100',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PV.functionParameter.fv.name',
                detail: 'formula.functionList.PV.functionParameter.fv.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PV.functionParameter.type.name',
                detail: 'formula.functionList.PV.functionParameter.type.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.RATE,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.RATE.description',
        abstract: 'formula.functionList.RATE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.RATE.functionParameter.nper.name',
                detail: 'formula.functionList.RATE.functionParameter.nper.detail',
                example: '4*12',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RATE.functionParameter.pmt.name',
                detail: 'formula.functionList.RATE.functionParameter.pmt.detail',
                example: '-200',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RATE.functionParameter.pv.name',
                detail: 'formula.functionList.RATE.functionParameter.pv.detail',
                example: '8000',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RATE.functionParameter.fv.name',
                detail: 'formula.functionList.RATE.functionParameter.fv.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RATE.functionParameter.type.name',
                detail: 'formula.functionList.RATE.functionParameter.type.detail',
                example: '0',
                require: 0,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RATE.functionParameter.guess.name',
                detail: 'formula.functionList.RATE.functionParameter.guess.detail',
                example: '0.1',
                require: 0,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.RECEIVED,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.RECEIVED.description',
        abstract: 'formula.functionList.RECEIVED.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.RECEIVED.functionParameter.number1.name',
                detail: 'formula.functionList.RECEIVED.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RECEIVED.functionParameter.number2.name',
                detail: 'formula.functionList.RECEIVED.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.RRI,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.RRI.description',
        abstract: 'formula.functionList.RRI.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.RRI.functionParameter.number1.name',
                detail: 'formula.functionList.RRI.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RRI.functionParameter.number2.name',
                detail: 'formula.functionList.RRI.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.SLN,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.SLN.description',
        abstract: 'formula.functionList.SLN.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.SLN.functionParameter.number1.name',
                detail: 'formula.functionList.SLN.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.SLN.functionParameter.number2.name',
                detail: 'formula.functionList.SLN.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.SYD,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.SYD.description',
        abstract: 'formula.functionList.SYD.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.SYD.functionParameter.number1.name',
                detail: 'formula.functionList.SYD.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.SYD.functionParameter.number2.name',
                detail: 'formula.functionList.SYD.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.TBILLEQ,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.TBILLEQ.description',
        abstract: 'formula.functionList.TBILLEQ.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.TBILLEQ.functionParameter.number1.name',
                detail: 'formula.functionList.TBILLEQ.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.TBILLEQ.functionParameter.number2.name',
                detail: 'formula.functionList.TBILLEQ.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.TBILLPRICE,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.TBILLPRICE.description',
        abstract: 'formula.functionList.TBILLPRICE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.TBILLPRICE.functionParameter.number1.name',
                detail: 'formula.functionList.TBILLPRICE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.TBILLPRICE.functionParameter.number2.name',
                detail: 'formula.functionList.TBILLPRICE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.TBILLYIELD,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.TBILLYIELD.description',
        abstract: 'formula.functionList.TBILLYIELD.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.TBILLYIELD.functionParameter.number1.name',
                detail: 'formula.functionList.TBILLYIELD.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.TBILLYIELD.functionParameter.number2.name',
                detail: 'formula.functionList.TBILLYIELD.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.VDB,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.VDB.description',
        abstract: 'formula.functionList.VDB.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.VDB.functionParameter.number1.name',
                detail: 'formula.functionList.VDB.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.VDB.functionParameter.number2.name',
                detail: 'formula.functionList.VDB.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.XIRR,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.XIRR.description',
        abstract: 'formula.functionList.XIRR.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.XIRR.functionParameter.number1.name',
                detail: 'formula.functionList.XIRR.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.XIRR.functionParameter.number2.name',
                detail: 'formula.functionList.XIRR.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.XNPV,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.XNPV.description',
        abstract: 'formula.functionList.XNPV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.XNPV.functionParameter.number1.name',
                detail: 'formula.functionList.XNPV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.XNPV.functionParameter.number2.name',
                detail: 'formula.functionList.XNPV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.YIELD,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.YIELD.description',
        abstract: 'formula.functionList.YIELD.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.YIELD.functionParameter.number1.name',
                detail: 'formula.functionList.YIELD.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.YIELD.functionParameter.number2.name',
                detail: 'formula.functionList.YIELD.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.YIELDDISC,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.YIELDDISC.description',
        abstract: 'formula.functionList.YIELDDISC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.YIELDDISC.functionParameter.number1.name',
                detail: 'formula.functionList.YIELDDISC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.YIELDDISC.functionParameter.number2.name',
                detail: 'formula.functionList.YIELDDISC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_FINANCIAL.YIELDMAT,
        functionType: FunctionType.Financial,
        description: 'formula.functionList.YIELDMAT.description',
        abstract: 'formula.functionList.YIELDMAT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.YIELDMAT.functionParameter.number1.name',
                detail: 'formula.functionList.YIELDMAT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.YIELDMAT.functionParameter.number2.name',
                detail: 'formula.functionList.YIELDMAT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
];
