/**
 * Copyright 2023-present DreamNum Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { IFunctionInfo } from '@univerjs/engine-formula';
import { FUNCTION_NAMES_STATISTICAL, FunctionType } from '@univerjs/engine-formula';

export const FUNCTION_LIST_STATISTICAL: IFunctionInfo[] = [
    {
        functionName: FUNCTION_NAMES_STATISTICAL.AVEDEV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.AVEDEV.description',
        abstract: 'formula.functionList.AVEDEV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.AVEDEV.functionParameter.number1.name',
                detail: 'formula.functionList.AVEDEV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AVEDEV.functionParameter.number2.name',
                detail: 'formula.functionList.AVEDEV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.AVERAGE,
        aliasFunctionName: 'formula.functionList.AVERAGE.aliasFunctionName',
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.AVERAGE.description',
        abstract: 'formula.functionList.AVERAGE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.AVERAGE.functionParameter.number1.name',
                detail: 'formula.functionList.AVERAGE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AVERAGE.functionParameter.number2.name',
                detail: 'formula.functionList.AVERAGE.functionParameter.number2.detail',
                example: 'B2:B10',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.AVERAGEA,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.AVERAGEA.description',
        abstract: 'formula.functionList.AVERAGEA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.AVERAGEA.functionParameter.number1.name',
                detail: 'formula.functionList.AVERAGEA.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AVERAGEA.functionParameter.number2.name',
                detail: 'formula.functionList.AVERAGEA.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.AVERAGEIF,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.AVERAGEIF.description',
        abstract: 'formula.functionList.AVERAGEIF.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.AVERAGEIF.functionParameter.number1.name',
                detail: 'formula.functionList.AVERAGEIF.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AVERAGEIF.functionParameter.number2.name',
                detail: 'formula.functionList.AVERAGEIF.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.AVERAGEIFS,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.AVERAGEIFS.description',
        abstract: 'formula.functionList.AVERAGEIFS.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.AVERAGEIFS.functionParameter.number1.name',
                detail: 'formula.functionList.AVERAGEIFS.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.AVERAGEIFS.functionParameter.number2.name',
                detail: 'formula.functionList.AVERAGEIFS.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.BETA_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.BETA_DIST.description',
        abstract: 'formula.functionList.BETA_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.BETA_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.BETA_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.BETA_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.BETA_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.BETA_INV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.BETA_INV.description',
        abstract: 'formula.functionList.BETA_INV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.BETA_INV.functionParameter.number1.name',
                detail: 'formula.functionList.BETA_INV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.BETA_INV.functionParameter.number2.name',
                detail: 'formula.functionList.BETA_INV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.BINOM_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.BINOM_DIST.description',
        abstract: 'formula.functionList.BINOM_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.BINOM_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.BINOM_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.BINOM_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.BINOM_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.BINOM_DIST_RANGE,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.BINOM_DIST_RANGE.description',
        abstract: 'formula.functionList.BINOM_DIST_RANGE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.BINOM_DIST_RANGE.functionParameter.number1.name',
                detail: 'formula.functionList.BINOM_DIST_RANGE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.BINOM_DIST_RANGE.functionParameter.number2.name',
                detail: 'formula.functionList.BINOM_DIST_RANGE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.BINOM_INV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.BINOM_INV.description',
        abstract: 'formula.functionList.BINOM_INV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.BINOM_INV.functionParameter.number1.name',
                detail: 'formula.functionList.BINOM_INV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.BINOM_INV.functionParameter.number2.name',
                detail: 'formula.functionList.BINOM_INV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.CHISQ_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.CHISQ_DIST.description',
        abstract: 'formula.functionList.CHISQ_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CHISQ_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.CHISQ_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CHISQ_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.CHISQ_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.CHISQ_DIST_RT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.CHISQ_DIST_RT.description',
        abstract: 'formula.functionList.CHISQ_DIST_RT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CHISQ_DIST_RT.functionParameter.number1.name',
                detail: 'formula.functionList.CHISQ_DIST_RT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CHISQ_DIST_RT.functionParameter.number2.name',
                detail: 'formula.functionList.CHISQ_DIST_RT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.CHISQ_INV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.CHISQ_INV.description',
        abstract: 'formula.functionList.CHISQ_INV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CHISQ_INV.functionParameter.number1.name',
                detail: 'formula.functionList.CHISQ_INV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CHISQ_INV.functionParameter.number2.name',
                detail: 'formula.functionList.CHISQ_INV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.CHISQ_INV_RT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.CHISQ_INV_RT.description',
        abstract: 'formula.functionList.CHISQ_INV_RT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CHISQ_INV_RT.functionParameter.number1.name',
                detail: 'formula.functionList.CHISQ_INV_RT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CHISQ_INV_RT.functionParameter.number2.name',
                detail: 'formula.functionList.CHISQ_INV_RT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.CHISQ_TEST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.CHISQ_TEST.description',
        abstract: 'formula.functionList.CHISQ_TEST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CHISQ_TEST.functionParameter.number1.name',
                detail: 'formula.functionList.CHISQ_TEST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CHISQ_TEST.functionParameter.number2.name',
                detail: 'formula.functionList.CHISQ_TEST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.CONFIDENCE_NORM,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.CONFIDENCE_NORM.description',
        abstract: 'formula.functionList.CONFIDENCE_NORM.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CONFIDENCE_NORM.functionParameter.number1.name',
                detail: 'formula.functionList.CONFIDENCE_NORM.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CONFIDENCE_NORM.functionParameter.number2.name',
                detail: 'formula.functionList.CONFIDENCE_NORM.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.CONFIDENCE_T,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.CONFIDENCE_T.description',
        abstract: 'formula.functionList.CONFIDENCE_T.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CONFIDENCE_T.functionParameter.number1.name',
                detail: 'formula.functionList.CONFIDENCE_T.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CONFIDENCE_T.functionParameter.number2.name',
                detail: 'formula.functionList.CONFIDENCE_T.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.CORREL,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.CORREL.description',
        abstract: 'formula.functionList.CORREL.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.CORREL.functionParameter.number1.name',
                detail: 'formula.functionList.CORREL.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.CORREL.functionParameter.number2.name',
                detail: 'formula.functionList.CORREL.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.COUNT,
        aliasFunctionName: 'formula.functionList.COUNT.aliasFunctionName',
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.COUNT.description',
        abstract: 'formula.functionList.COUNT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUNT.functionParameter.value1.name',
                detail: 'formula.functionList.COUNT.functionParameter.value1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUNT.functionParameter.value2.name',
                detail: 'formula.functionList.COUNT.functionParameter.value2.detail',
                example: 'B2:B10',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.COUNTA,
        aliasFunctionName: 'formula.functionList.COUNTA.aliasFunctionName',
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.COUNTA.description',
        abstract: 'formula.functionList.COUNTA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUNTA.functionParameter.number1.name',
                detail: 'formula.functionList.COUNTA.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUNTA.functionParameter.number2.name',
                detail: 'formula.functionList.COUNTA.functionParameter.number2.detail',
                example: 'B2:B10',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.COUNTBLANK,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.COUNTBLANK.description',
        abstract: 'formula.functionList.COUNTBLANK.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUNTBLANK.functionParameter.number1.name',
                detail: 'formula.functionList.COUNTBLANK.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUNTBLANK.functionParameter.number2.name',
                detail: 'formula.functionList.COUNTBLANK.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.COUNTIF,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.COUNTIF.description',
        abstract: 'formula.functionList.COUNTIF.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUNTIF.functionParameter.number1.name',
                detail: 'formula.functionList.COUNTIF.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUNTIF.functionParameter.number2.name',
                detail: 'formula.functionList.COUNTIF.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.COUNTIFS,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.COUNTIFS.description',
        abstract: 'formula.functionList.COUNTIFS.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COUNTIFS.functionParameter.number1.name',
                detail: 'formula.functionList.COUNTIFS.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COUNTIFS.functionParameter.number2.name',
                detail: 'formula.functionList.COUNTIFS.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.COVARIANCE_P,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.COVARIANCE_P.description',
        abstract: 'formula.functionList.COVARIANCE_P.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COVARIANCE_P.functionParameter.number1.name',
                detail: 'formula.functionList.COVARIANCE_P.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COVARIANCE_P.functionParameter.number2.name',
                detail: 'formula.functionList.COVARIANCE_P.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.COVARIANCE_S,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.COVARIANCE_S.description',
        abstract: 'formula.functionList.COVARIANCE_S.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.COVARIANCE_S.functionParameter.number1.name',
                detail: 'formula.functionList.COVARIANCE_S.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.COVARIANCE_S.functionParameter.number2.name',
                detail: 'formula.functionList.COVARIANCE_S.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.DEVSQ,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.DEVSQ.description',
        abstract: 'formula.functionList.DEVSQ.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.DEVSQ.functionParameter.number1.name',
                detail: 'formula.functionList.DEVSQ.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.DEVSQ.functionParameter.number2.name',
                detail: 'formula.functionList.DEVSQ.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.EXPON_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.EXPON_DIST.description',
        abstract: 'formula.functionList.EXPON_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.EXPON_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.EXPON_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.EXPON_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.EXPON_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.F_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.F_DIST.description',
        abstract: 'formula.functionList.F_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.F_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.F_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.F_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.F_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.F_DIST_RT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.F_DIST_RT.description',
        abstract: 'formula.functionList.F_DIST_RT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.F_DIST_RT.functionParameter.number1.name',
                detail: 'formula.functionList.F_DIST_RT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.F_DIST_RT.functionParameter.number2.name',
                detail: 'formula.functionList.F_DIST_RT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.F_INV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.F_INV.description',
        abstract: 'formula.functionList.F_INV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.F_INV.functionParameter.number1.name',
                detail: 'formula.functionList.F_INV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.F_INV.functionParameter.number2.name',
                detail: 'formula.functionList.F_INV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.F_INV_RT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.F_INV_RT.description',
        abstract: 'formula.functionList.F_INV_RT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.F_INV_RT.functionParameter.number1.name',
                detail: 'formula.functionList.F_INV_RT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.F_INV_RT.functionParameter.number2.name',
                detail: 'formula.functionList.F_INV_RT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.F_TEST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.F_TEST.description',
        abstract: 'formula.functionList.F_TEST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.F_TEST.functionParameter.number1.name',
                detail: 'formula.functionList.F_TEST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.F_TEST.functionParameter.number2.name',
                detail: 'formula.functionList.F_TEST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.FISHER,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.FISHER.description',
        abstract: 'formula.functionList.FISHER.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FISHER.functionParameter.number1.name',
                detail: 'formula.functionList.FISHER.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FISHER.functionParameter.number2.name',
                detail: 'formula.functionList.FISHER.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.FISHERINV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.FISHERINV.description',
        abstract: 'formula.functionList.FISHERINV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FISHERINV.functionParameter.number1.name',
                detail: 'formula.functionList.FISHERINV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FISHERINV.functionParameter.number2.name',
                detail: 'formula.functionList.FISHERINV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.FORECAST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.FORECAST.description',
        abstract: 'formula.functionList.FORECAST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FORECAST.functionParameter.number1.name',
                detail: 'formula.functionList.FORECAST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FORECAST.functionParameter.number2.name',
                detail: 'formula.functionList.FORECAST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.FORECAST_ETS,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.FORECAST_ETS.description',
        abstract: 'formula.functionList.FORECAST_ETS.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FORECAST_ETS.functionParameter.number1.name',
                detail: 'formula.functionList.FORECAST_ETS.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FORECAST_ETS.functionParameter.number2.name',
                detail: 'formula.functionList.FORECAST_ETS.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.FORECAST_ETS_CONFINT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.FORECAST_ETS_CONFINT.description',
        abstract: 'formula.functionList.FORECAST_ETS_CONFINT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FORECAST_ETS_CONFINT.functionParameter.number1.name',
                detail: 'formula.functionList.FORECAST_ETS_CONFINT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FORECAST_ETS_CONFINT.functionParameter.number2.name',
                detail: 'formula.functionList.FORECAST_ETS_CONFINT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.FORECAST_ETS_SEASONALITY,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.FORECAST_ETS_SEASONALITY.description',
        abstract: 'formula.functionList.FORECAST_ETS_SEASONALITY.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FORECAST_ETS_SEASONALITY.functionParameter.number1.name',
                detail: 'formula.functionList.FORECAST_ETS_SEASONALITY.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FORECAST_ETS_SEASONALITY.functionParameter.number2.name',
                detail: 'formula.functionList.FORECAST_ETS_SEASONALITY.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.FORECAST_ETS_STAT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.FORECAST_ETS_STAT.description',
        abstract: 'formula.functionList.FORECAST_ETS_STAT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FORECAST_ETS_STAT.functionParameter.number1.name',
                detail: 'formula.functionList.FORECAST_ETS_STAT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FORECAST_ETS_STAT.functionParameter.number2.name',
                detail: 'formula.functionList.FORECAST_ETS_STAT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.FORECAST_LINEAR,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.FORECAST_LINEAR.description',
        abstract: 'formula.functionList.FORECAST_LINEAR.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FORECAST_LINEAR.functionParameter.number1.name',
                detail: 'formula.functionList.FORECAST_LINEAR.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FORECAST_LINEAR.functionParameter.number2.name',
                detail: 'formula.functionList.FORECAST_LINEAR.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.FREQUENCY,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.FREQUENCY.description',
        abstract: 'formula.functionList.FREQUENCY.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.FREQUENCY.functionParameter.number1.name',
                detail: 'formula.functionList.FREQUENCY.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.FREQUENCY.functionParameter.number2.name',
                detail: 'formula.functionList.FREQUENCY.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.GAMMA,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.GAMMA.description',
        abstract: 'formula.functionList.GAMMA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.GAMMA.functionParameter.number1.name',
                detail: 'formula.functionList.GAMMA.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.GAMMA.functionParameter.number2.name',
                detail: 'formula.functionList.GAMMA.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.GAMMA_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.GAMMA_DIST.description',
        abstract: 'formula.functionList.GAMMA_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.GAMMA_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.GAMMA_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.GAMMA_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.GAMMA_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.GAMMA_INV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.GAMMA_INV.description',
        abstract: 'formula.functionList.GAMMA_INV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.GAMMA_INV.functionParameter.number1.name',
                detail: 'formula.functionList.GAMMA_INV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.GAMMA_INV.functionParameter.number2.name',
                detail: 'formula.functionList.GAMMA_INV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.GAMMALN,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.GAMMALN.description',
        abstract: 'formula.functionList.GAMMALN.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.GAMMALN.functionParameter.number1.name',
                detail: 'formula.functionList.GAMMALN.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.GAMMALN.functionParameter.number2.name',
                detail: 'formula.functionList.GAMMALN.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.GAMMALN_PRECISE,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.GAMMALN_PRECISE.description',
        abstract: 'formula.functionList.GAMMALN_PRECISE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.GAMMALN_PRECISE.functionParameter.number1.name',
                detail: 'formula.functionList.GAMMALN_PRECISE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.GAMMALN_PRECISE.functionParameter.number2.name',
                detail: 'formula.functionList.GAMMALN_PRECISE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.GAUSS,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.GAUSS.description',
        abstract: 'formula.functionList.GAUSS.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.GAUSS.functionParameter.number1.name',
                detail: 'formula.functionList.GAUSS.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.GAUSS.functionParameter.number2.name',
                detail: 'formula.functionList.GAUSS.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.GEOMEAN,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.GEOMEAN.description',
        abstract: 'formula.functionList.GEOMEAN.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.GEOMEAN.functionParameter.number1.name',
                detail: 'formula.functionList.GEOMEAN.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.GEOMEAN.functionParameter.number2.name',
                detail: 'formula.functionList.GEOMEAN.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.GROWTH,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.GROWTH.description',
        abstract: 'formula.functionList.GROWTH.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.GROWTH.functionParameter.number1.name',
                detail: 'formula.functionList.GROWTH.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.GROWTH.functionParameter.number2.name',
                detail: 'formula.functionList.GROWTH.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.HARMEAN,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.HARMEAN.description',
        abstract: 'formula.functionList.HARMEAN.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.HARMEAN.functionParameter.number1.name',
                detail: 'formula.functionList.HARMEAN.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.HARMEAN.functionParameter.number2.name',
                detail: 'formula.functionList.HARMEAN.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.HYPGEOM_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.HYPGEOM_DIST.description',
        abstract: 'formula.functionList.HYPGEOM_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.HYPGEOM_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.HYPGEOM_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.HYPGEOM_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.HYPGEOM_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.INTERCEPT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.INTERCEPT.description',
        abstract: 'formula.functionList.INTERCEPT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.INTERCEPT.functionParameter.number1.name',
                detail: 'formula.functionList.INTERCEPT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.INTERCEPT.functionParameter.number2.name',
                detail: 'formula.functionList.INTERCEPT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.KURT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.KURT.description',
        abstract: 'formula.functionList.KURT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.KURT.functionParameter.number1.name',
                detail: 'formula.functionList.KURT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.KURT.functionParameter.number2.name',
                detail: 'formula.functionList.KURT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.LARGE,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.LARGE.description',
        abstract: 'formula.functionList.LARGE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.LARGE.functionParameter.number1.name',
                detail: 'formula.functionList.LARGE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.LARGE.functionParameter.number2.name',
                detail: 'formula.functionList.LARGE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.LINEST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.LINEST.description',
        abstract: 'formula.functionList.LINEST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.LINEST.functionParameter.number1.name',
                detail: 'formula.functionList.LINEST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.LINEST.functionParameter.number2.name',
                detail: 'formula.functionList.LINEST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.LOGEST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.LOGEST.description',
        abstract: 'formula.functionList.LOGEST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.LOGEST.functionParameter.number1.name',
                detail: 'formula.functionList.LOGEST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.LOGEST.functionParameter.number2.name',
                detail: 'formula.functionList.LOGEST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.LOGNORM_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.LOGNORM_DIST.description',
        abstract: 'formula.functionList.LOGNORM_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.LOGNORM_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.LOGNORM_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.LOGNORM_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.LOGNORM_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.LOGNORM_INV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.LOGNORM_INV.description',
        abstract: 'formula.functionList.LOGNORM_INV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.LOGNORM_INV.functionParameter.number1.name',
                detail: 'formula.functionList.LOGNORM_INV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.LOGNORM_INV.functionParameter.number2.name',
                detail: 'formula.functionList.LOGNORM_INV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.MAX,
        aliasFunctionName: 'formula.functionList.MAX.aliasFunctionName',
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.MAX.description',
        abstract: 'formula.functionList.MAX.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MAX.functionParameter.number1.name',
                detail: 'formula.functionList.MAX.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MAX.functionParameter.number2.name',
                detail: 'formula.functionList.MAX.functionParameter.number2.detail',
                example: 'B2:B10',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.MAXA,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.MAXA.description',
        abstract: 'formula.functionList.MAXA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MAXA.functionParameter.number1.name',
                detail: 'formula.functionList.MAXA.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MAXA.functionParameter.number2.name',
                detail: 'formula.functionList.MAXA.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.MAXIFS,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.MAXIFS.description',
        abstract: 'formula.functionList.MAXIFS.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MAXIFS.functionParameter.maxRange.name',
                detail: 'formula.functionList.MAXIFS.functionParameter.maxRange.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MAXIFS.functionParameter.criteriaRange1.name',
                detail: 'formula.functionList.MAXIFS.functionParameter.criteriaRange1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MAXIFS.functionParameter.criteria1.name',
                detail: 'formula.functionList.MAXIFS.functionParameter.criteria1.detail',
                example: '">10"',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MAXIFS.functionParameter.criteriaRange2.name',
                detail: 'formula.functionList.MAXIFS.functionParameter.criteriaRange2.detail',
                example: 'A1:A20',
                require: 0,
                repeat: 1,
            },
            {
                name: 'formula.functionList.MAXIFS.functionParameter.criteria2.name',
                detail: 'formula.functionList.MAXIFS.functionParameter.criteria2.detail',
                example: '"<100"',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.MEDIAN,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.MEDIAN.description',
        abstract: 'formula.functionList.MEDIAN.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MEDIAN.functionParameter.number1.name',
                detail: 'formula.functionList.MEDIAN.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MEDIAN.functionParameter.number2.name',
                detail: 'formula.functionList.MEDIAN.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.MIN,
        aliasFunctionName: 'formula.functionList.MIN.aliasFunctionName',
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.MIN.description',
        abstract: 'formula.functionList.MIN.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MIN.functionParameter.number1.name',
                detail: 'formula.functionList.MIN.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MIN.functionParameter.number2.name',
                detail: 'formula.functionList.MIN.functionParameter.number2.detail',
                example: 'B2:B10',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.MINA,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.MINA.description',
        abstract: 'formula.functionList.MINA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MINA.functionParameter.number1.name',
                detail: 'formula.functionList.MINA.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MINA.functionParameter.number2.name',
                detail: 'formula.functionList.MINA.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.MINIFS,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.MINIFS.description',
        abstract: 'formula.functionList.MINIFS.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MINIFS.functionParameter.number1.name',
                detail: 'formula.functionList.MINIFS.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MINIFS.functionParameter.number2.name',
                detail: 'formula.functionList.MINIFS.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.MODE_MULT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.MODE_MULT.description',
        abstract: 'formula.functionList.MODE_MULT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MODE_MULT.functionParameter.number1.name',
                detail: 'formula.functionList.MODE_MULT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MODE_MULT.functionParameter.number2.name',
                detail: 'formula.functionList.MODE_MULT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.MODE_SNGL,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.MODE_SNGL.description',
        abstract: 'formula.functionList.MODE_SNGL.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.MODE_SNGL.functionParameter.number1.name',
                detail: 'formula.functionList.MODE_SNGL.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.MODE_SNGL.functionParameter.number2.name',
                detail: 'formula.functionList.MODE_SNGL.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.NEGBINOM_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.NEGBINOM_DIST.description',
        abstract: 'formula.functionList.NEGBINOM_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.NEGBINOM_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.NEGBINOM_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NEGBINOM_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.NEGBINOM_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.NORM_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.NORM_DIST.description',
        abstract: 'formula.functionList.NORM_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.NORM_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.NORM_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NORM_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.NORM_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.NORM_INV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.NORM_INV.description',
        abstract: 'formula.functionList.NORM_INV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.NORM_INV.functionParameter.number1.name',
                detail: 'formula.functionList.NORM_INV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NORM_INV.functionParameter.number2.name',
                detail: 'formula.functionList.NORM_INV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.NORM_S_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.NORM_S_DIST.description',
        abstract: 'formula.functionList.NORM_S_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.NORM_S_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.NORM_S_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NORM_S_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.NORM_S_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.NORM_S_INV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.NORM_S_INV.description',
        abstract: 'formula.functionList.NORM_S_INV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.NORM_S_INV.functionParameter.number1.name',
                detail: 'formula.functionList.NORM_S_INV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.NORM_S_INV.functionParameter.number2.name',
                detail: 'formula.functionList.NORM_S_INV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.PEARSON,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.PEARSON.description',
        abstract: 'formula.functionList.PEARSON.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PEARSON.functionParameter.number1.name',
                detail: 'formula.functionList.PEARSON.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PEARSON.functionParameter.number2.name',
                detail: 'formula.functionList.PEARSON.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.PERCENTILE_EXC,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.PERCENTILE_EXC.description',
        abstract: 'formula.functionList.PERCENTILE_EXC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PERCENTILE_EXC.functionParameter.number1.name',
                detail: 'formula.functionList.PERCENTILE_EXC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PERCENTILE_EXC.functionParameter.number2.name',
                detail: 'formula.functionList.PERCENTILE_EXC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.PERCENTILE_INC,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.PERCENTILE_INC.description',
        abstract: 'formula.functionList.PERCENTILE_INC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PERCENTILE_INC.functionParameter.number1.name',
                detail: 'formula.functionList.PERCENTILE_INC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PERCENTILE_INC.functionParameter.number2.name',
                detail: 'formula.functionList.PERCENTILE_INC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.PERCENTRANK_EXC,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.PERCENTRANK_EXC.description',
        abstract: 'formula.functionList.PERCENTRANK_EXC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PERCENTRANK_EXC.functionParameter.number1.name',
                detail: 'formula.functionList.PERCENTRANK_EXC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PERCENTRANK_EXC.functionParameter.number2.name',
                detail: 'formula.functionList.PERCENTRANK_EXC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.PERCENTRANK_INC,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.PERCENTRANK_INC.description',
        abstract: 'formula.functionList.PERCENTRANK_INC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PERCENTRANK_INC.functionParameter.number1.name',
                detail: 'formula.functionList.PERCENTRANK_INC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PERCENTRANK_INC.functionParameter.number2.name',
                detail: 'formula.functionList.PERCENTRANK_INC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.PERMUT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.PERMUT.description',
        abstract: 'formula.functionList.PERMUT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PERMUT.functionParameter.number1.name',
                detail: 'formula.functionList.PERMUT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PERMUT.functionParameter.number2.name',
                detail: 'formula.functionList.PERMUT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.PERMUTATIONA,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.PERMUTATIONA.description',
        abstract: 'formula.functionList.PERMUTATIONA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PERMUTATIONA.functionParameter.number1.name',
                detail: 'formula.functionList.PERMUTATIONA.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PERMUTATIONA.functionParameter.number2.name',
                detail: 'formula.functionList.PERMUTATIONA.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.PHI,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.PHI.description',
        abstract: 'formula.functionList.PHI.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PHI.functionParameter.number1.name',
                detail: 'formula.functionList.PHI.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PHI.functionParameter.number2.name',
                detail: 'formula.functionList.PHI.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.POISSON_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.POISSON_DIST.description',
        abstract: 'formula.functionList.POISSON_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.POISSON_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.POISSON_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.POISSON_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.POISSON_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.PROB,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.PROB.description',
        abstract: 'formula.functionList.PROB.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.PROB.functionParameter.number1.name',
                detail: 'formula.functionList.PROB.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.PROB.functionParameter.number2.name',
                detail: 'formula.functionList.PROB.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.QUARTILE_EXC,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.QUARTILE_EXC.description',
        abstract: 'formula.functionList.QUARTILE_EXC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.QUARTILE_EXC.functionParameter.number1.name',
                detail: 'formula.functionList.QUARTILE_EXC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.QUARTILE_EXC.functionParameter.number2.name',
                detail: 'formula.functionList.QUARTILE_EXC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.QUARTILE_INC,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.QUARTILE_INC.description',
        abstract: 'formula.functionList.QUARTILE_INC.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.QUARTILE_INC.functionParameter.number1.name',
                detail: 'formula.functionList.QUARTILE_INC.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.QUARTILE_INC.functionParameter.number2.name',
                detail: 'formula.functionList.QUARTILE_INC.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.RANK_AVG,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.RANK_AVG.description',
        abstract: 'formula.functionList.RANK_AVG.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.RANK_AVG.functionParameter.number1.name',
                detail: 'formula.functionList.RANK_AVG.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RANK_AVG.functionParameter.number2.name',
                detail: 'formula.functionList.RANK_AVG.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.RANK_EQ,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.RANK_EQ.description',
        abstract: 'formula.functionList.RANK_EQ.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.RANK_EQ.functionParameter.number1.name',
                detail: 'formula.functionList.RANK_EQ.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RANK_EQ.functionParameter.number2.name',
                detail: 'formula.functionList.RANK_EQ.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.RSQ,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.RSQ.description',
        abstract: 'formula.functionList.RSQ.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.RSQ.functionParameter.number1.name',
                detail: 'formula.functionList.RSQ.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.RSQ.functionParameter.number2.name',
                detail: 'formula.functionList.RSQ.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.SKEW,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.SKEW.description',
        abstract: 'formula.functionList.SKEW.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.SKEW.functionParameter.number1.name',
                detail: 'formula.functionList.SKEW.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.SKEW.functionParameter.number2.name',
                detail: 'formula.functionList.SKEW.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.SKEW_P,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.SKEW_P.description',
        abstract: 'formula.functionList.SKEW_P.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.SKEW_P.functionParameter.number1.name',
                detail: 'formula.functionList.SKEW_P.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.SKEW_P.functionParameter.number2.name',
                detail: 'formula.functionList.SKEW_P.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.SLOPE,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.SLOPE.description',
        abstract: 'formula.functionList.SLOPE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.SLOPE.functionParameter.number1.name',
                detail: 'formula.functionList.SLOPE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.SLOPE.functionParameter.number2.name',
                detail: 'formula.functionList.SLOPE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.SMALL,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.SMALL.description',
        abstract: 'formula.functionList.SMALL.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.SMALL.functionParameter.number1.name',
                detail: 'formula.functionList.SMALL.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.SMALL.functionParameter.number2.name',
                detail: 'formula.functionList.SMALL.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.STANDARDIZE,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.STANDARDIZE.description',
        abstract: 'formula.functionList.STANDARDIZE.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.STANDARDIZE.functionParameter.number1.name',
                detail: 'formula.functionList.STANDARDIZE.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.STANDARDIZE.functionParameter.number2.name',
                detail: 'formula.functionList.STANDARDIZE.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.STDEV_P,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.STDEV_P.description',
        abstract: 'formula.functionList.STDEV_P.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.STDEV_P.functionParameter.number1.name',
                detail: 'formula.functionList.STDEV_P.functionParameter.number1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.STDEV_P.functionParameter.number2.name',
                detail: 'formula.functionList.STDEV_P.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.STDEV_S,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.STDEV_S.description',
        abstract: 'formula.functionList.STDEV_S.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.STDEV_S.functionParameter.number1.name',
                detail: 'formula.functionList.STDEV_S.functionParameter.number1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.STDEV_S.functionParameter.number2.name',
                detail: 'formula.functionList.STDEV_S.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.STDEVA,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.STDEVA.description',
        abstract: 'formula.functionList.STDEVA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.STDEVA.functionParameter.value1.name',
                detail: 'formula.functionList.STDEVA.functionParameter.value1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.STDEVA.functionParameter.value2.name',
                detail: 'formula.functionList.STDEVA.functionParameter.value2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.STDEVPA,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.STDEVPA.description',
        abstract: 'formula.functionList.STDEVPA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.STDEVPA.functionParameter.value1.name',
                detail: 'formula.functionList.STDEVPA.functionParameter.value1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.STDEVPA.functionParameter.value2.name',
                detail: 'formula.functionList.STDEVPA.functionParameter.value2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.STEYX,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.STEYX.description',
        abstract: 'formula.functionList.STEYX.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.STEYX.functionParameter.number1.name',
                detail: 'formula.functionList.STEYX.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.STEYX.functionParameter.number2.name',
                detail: 'formula.functionList.STEYX.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.T_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.T_DIST.description',
        abstract: 'formula.functionList.T_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.T_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.T_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.T_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.T_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.T_DIST_2T,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.T_DIST_2T.description',
        abstract: 'formula.functionList.T_DIST_2T.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.T_DIST_2T.functionParameter.number1.name',
                detail: 'formula.functionList.T_DIST_2T.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.T_DIST_2T.functionParameter.number2.name',
                detail: 'formula.functionList.T_DIST_2T.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.T_DIST_RT,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.T_DIST_RT.description',
        abstract: 'formula.functionList.T_DIST_RT.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.T_DIST_RT.functionParameter.number1.name',
                detail: 'formula.functionList.T_DIST_RT.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.T_DIST_RT.functionParameter.number2.name',
                detail: 'formula.functionList.T_DIST_RT.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.T_INV,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.T_INV.description',
        abstract: 'formula.functionList.T_INV.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.T_INV.functionParameter.number1.name',
                detail: 'formula.functionList.T_INV.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.T_INV.functionParameter.number2.name',
                detail: 'formula.functionList.T_INV.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.T_INV_2T,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.T_INV_2T.description',
        abstract: 'formula.functionList.T_INV_2T.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.T_INV_2T.functionParameter.number1.name',
                detail: 'formula.functionList.T_INV_2T.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.T_INV_2T.functionParameter.number2.name',
                detail: 'formula.functionList.T_INV_2T.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.T_TEST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.T_TEST.description',
        abstract: 'formula.functionList.T_TEST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.T_TEST.functionParameter.number1.name',
                detail: 'formula.functionList.T_TEST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.T_TEST.functionParameter.number2.name',
                detail: 'formula.functionList.T_TEST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.TREND,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.TREND.description',
        abstract: 'formula.functionList.TREND.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.TREND.functionParameter.number1.name',
                detail: 'formula.functionList.TREND.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.TREND.functionParameter.number2.name',
                detail: 'formula.functionList.TREND.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.TRIMMEAN,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.TRIMMEAN.description',
        abstract: 'formula.functionList.TRIMMEAN.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.TRIMMEAN.functionParameter.number1.name',
                detail: 'formula.functionList.TRIMMEAN.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.TRIMMEAN.functionParameter.number2.name',
                detail: 'formula.functionList.TRIMMEAN.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.VAR_P,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.VAR_P.description',
        abstract: 'formula.functionList.VAR_P.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.VAR_P.functionParameter.number1.name',
                detail: 'formula.functionList.VAR_P.functionParameter.number1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.VAR_P.functionParameter.number2.name',
                detail: 'formula.functionList.VAR_P.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.VAR_S,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.VAR_S.description',
        abstract: 'formula.functionList.VAR_S.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.VAR_S.functionParameter.number1.name',
                detail: 'formula.functionList.VAR_S.functionParameter.number1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.VAR_S.functionParameter.number2.name',
                detail: 'formula.functionList.VAR_S.functionParameter.number2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.VARA,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.VARA.description',
        abstract: 'formula.functionList.VARA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.VARA.functionParameter.value1.name',
                detail: 'formula.functionList.VARA.functionParameter.value1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.VARA.functionParameter.value2.name',
                detail: 'formula.functionList.VARA.functionParameter.value2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.VARPA,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.VARPA.description',
        abstract: 'formula.functionList.VARPA.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.VARPA.functionParameter.value1.name',
                detail: 'formula.functionList.VARPA.functionParameter.value1.detail',
                example: '1',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.VARPA.functionParameter.value2.name',
                detail: 'formula.functionList.VARPA.functionParameter.value2.detail',
                example: '2',
                require: 0,
                repeat: 1,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.WEIBULL_DIST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.WEIBULL_DIST.description',
        abstract: 'formula.functionList.WEIBULL_DIST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.WEIBULL_DIST.functionParameter.number1.name',
                detail: 'formula.functionList.WEIBULL_DIST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.WEIBULL_DIST.functionParameter.number2.name',
                detail: 'formula.functionList.WEIBULL_DIST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
    {
        functionName: FUNCTION_NAMES_STATISTICAL.Z_TEST,
        functionType: FunctionType.Statistical,
        description: 'formula.functionList.Z_TEST.description',
        abstract: 'formula.functionList.Z_TEST.abstract',
        functionParameter: [
            {
                name: 'formula.functionList.Z_TEST.functionParameter.number1.name',
                detail: 'formula.functionList.Z_TEST.functionParameter.number1.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
            {
                name: 'formula.functionList.Z_TEST.functionParameter.number2.name',
                detail: 'formula.functionList.Z_TEST.functionParameter.number2.detail',
                example: 'A1:A20',
                require: 1,
                repeat: 0,
            },
        ],
    },
];
