name: 📸 Update Snapshots
description: Update snapshots and push a new commit.

runs:
    using: composite
    steps:
        - name: Install Playwright Browsers
          run: pnpm exec playwright install --with-deps chromium

        - name: Build E2E Client
          run: pnpm build:e2e

        - name: Update Snapshots
          run: pnpm exec playwright test --update-snapshots

        - name: Commit Updated Snapshots
          run: |
              git config --global user.email "actions@github.com"
              git config --global user.name "GitHub Actions"

              git add -A
              git commit -m "chore(snapshots): update snapshots" || exit 0
              git push
