name: 🐛 Bug 报告
description: 尽管我们提供了中文 Bug 报告的入口，但还是建议您使用英语描述问题，这可以让更多的人来帮助您。
type: Bug
title: '[Bug] '

body:
    - type: checkboxes
      id: initial-checklist
      attributes:
          label: 在您提交此问题之前，您是否检查了以下内容？
          options:
              - label: 这真的是个问题吗？
                required: true
              - label: 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。
                required: true

    - type: input
      id: affected-versions
      attributes:
          label: 受影响的包和版本
          description: 请使用最新版本的相关包进行测试，以确保您的问题尚未解决。
      validations:
          required: true

    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: 复现链接
          description: |
              **请注意，请务必认真提供复现并详细描述复现步骤，如果您无法提供复现链接，你的问题有可能会被直接关闭。**

              我们提供了 [Vite 在线模板](https://stackblitz.com/edit/univer-sheets-vite) 和 [UMD 在线模板](https://stackblitz.com/edit/univer-sheets-umd)，如果您的问题可以在这个模板中复现，那么请在这里提供复现链接。
              我们也提供了一些其他你可能会用到的 [模板仓库](https://github.com/awesome-univer)，你可以选择其中一个来复现你的问题。
              如果您的问题无法在模板中复现，请提供尽可能详细的复现步骤。
      validations:
          required: true

    - type: textarea
      id: expected-behavior
      attributes:
          label: 预期行为
          description: 本应发生什么？
      validations:
          required: true

    - type: textarea
      id: actual-behavior
      attributes:
          label: 实际行为
          description: 实际发生了什么？
      validations:
          required: true

    - type: dropdown
      id: javascript-runtime
      attributes:
          label: 运行环境
          description: |
              您使用的浏览器是？
          multiple: true
          options:
              - Chrome
              - Safari
              - Firefox
              - Electron
              - 其他 (请在复现步骤中说明)
      validations:
          required: false

    - type: textarea
      id: system-info
      attributes:
          label: 系统信息
          description: 在这里粘贴 `npx envinfo --system --binaries --browsers` 命令的输出结果
