name: 🚀 Feature request
description: Suggest an idea
type: Feature
title: '[Feature] '

body:
    - type: checkboxes
      id: initial-checklist
      attributes:
          label: Initial checklist
          options:
              - label: Is this really a problem?
                required: true
              - label: I have searched the Github Issues for similar issues, but did not find anything.
                required: true

    - type: textarea
      id: problem
      attributes:
          label: Problem
          description: Please describe the problem you are trying to solve here.
      validations:
          required: true
