name: 🚀 新功能请求
description: 尽管我们提供了中文 Feature request 的入口，但还是建议您使用英语描述需求，这可以让更多的人来帮助您。
type: Feature
title: '[Feature] '

body:
    - type: checkboxes
      id: initial-checklist
      attributes:
          label: 初始清单
          options:
              - label: 这真的是个问题吗？
                required: true
              - label: 我已经在 Github Issues 中搜索过了，但没有找到类似的问题。
                required: true

    - type: textarea
      id: problem
      attributes:
          label: 问题
          description: |
              请详细描述您的需求，如果您的描述无法被理解，**那么您的问题可能会被直接关闭**。
              - 您应当清楚地提供需求的背景、目的、以及您希望的解决方案。
              - 如果您有任何的设计稿、流程图、或者其他相关的附件，请在这里提供。
      validations:
          required: true
