/**
 * Copyright 2023-present DreamNum Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { describe, expect, it } from 'vitest';
import type { ISnapshot } from '@univerjs/protocol';
import { getSheetBlocksFromSnapshot, transformSnapshotObjectToWorkbookData, transformSnapshotToWorkbookData, transformWorkbookDataToSnapshot, transformWorkbookDataToSnapshotObject } from '../snapshot-transform';

import type { ILogContext } from '../../log/context';
import type { ISnapshotServerService } from '../snapshot-server.service';
import { textDecoder } from '../snapshot-utils';
import type { ISheetBlockObject } from '../../../types/interfaces/snapshot';
import { SnapshotMetaType } from '../../../types/interfaces/snapshot';
import type { IWorkbookData } from '../../../types/interfaces';
import { LocaleType } from '../../../types/enum';
import { Tools } from '../../../shared/tools';
import { MockSnapshotServerService, testConvertedWorkbookData, testSheetBlocks, testSnapshot, testSnapshotSheetBlocksBuffer, testSnapshotSheetBlocksObject, testSnapshotSheetBlocksString, testWorkbookData } from './snapshot-mock';

/**
 * The Uint8Array converted from the encoded string, and the encoded string converted back is different from the original one, so objects can only be used for comparison.
 * @param snapshot
 * @returns
 */
function transformSnapshotMetaToObject(snapshot: ISnapshot) {
    const workbook = snapshot.workbook;
    if (!workbook) return snapshot;

    // Loop through sheets and convert originalMeta
    Object.keys(workbook.sheets).forEach((sheetKey) => {
        const sheet = workbook.sheets[sheetKey];
        sheet.originalMeta = JSON.parse(textDecoder.decode(sheet.originalMeta)); // Reassign the converted object to originalMeta
    });

    workbook.originalMeta = JSON.parse(textDecoder.decode(workbook.originalMeta)); // Reassign the converted object to originalMeta

    return snapshot;
}

describe('Test snapshot transform', () => {
    it('Function transformWorkbookDataToSnapshot', async () => {
        const context: ILogContext = {
            metadata: undefined,
        };
        const workbookData = testWorkbookData();
        const unitID = workbookData.id;
        const rev = workbookData.rev ?? 0;

        const snapshotService: ISnapshotServerService = new MockSnapshotServerService();

        const { snapshot } = await transformWorkbookDataToSnapshot(context, workbookData, unitID, rev, snapshotService);

        const snapshotData = transformSnapshotMetaToObject(snapshot);

        expect(snapshotData).toStrictEqual(transformSnapshotMetaToObject(testSnapshot()));

        const blocks = await getSheetBlocksFromSnapshot(snapshot, snapshotService);

        expect(blocks).toStrictEqual(testSheetBlocks());
    });
    it('Function transformSnapshotToWorkbookData', () => {
        expect(transformSnapshotToWorkbookData(testSnapshot(), testSheetBlocks())).toStrictEqual(testWorkbookData());
    });

    it('Function transformSnapshotObjectToWorkbookData', () => {
        // string meta
        const { snapshot, sheetBlocks } = testSnapshotSheetBlocksString();
        expect(transformSnapshotObjectToWorkbookData(snapshot, sheetBlocks)).toStrictEqual(testConvertedWorkbookData());

        // object meta
        const { snapshot: snapshotObject, sheetBlocks: sheetBlocksObject } = testSnapshotSheetBlocksObject();
        expect(transformSnapshotObjectToWorkbookData(snapshotObject, sheetBlocksObject)).toStrictEqual(testConvertedWorkbookData());

        // buffer meta
        const { snapshot: snapshotBuffer, sheetBlocks: sheetBlockBuffer } = testSnapshotSheetBlocksBuffer();
        expect(transformSnapshotObjectToWorkbookData(snapshotBuffer, sheetBlockBuffer)).toStrictEqual(testConvertedWorkbookData());
    });

    it('Function transformWorkbookDataToSnapshotObject', async () => {
        const snapshotSheetBlockObject = await transformWorkbookDataToSnapshotObject(testConvertedWorkbookData(), SnapshotMetaType.OBJECT);

        // Because a lot of default data completion actions are done in transformSnapshotObjectToWorkbookData, the data generated by transformWorkbookDataToSnapshotObject will also be more.
        const originSnapshotSheetBlockObject = testSnapshotSheetBlocksObject();

        const originMeta = originSnapshotSheetBlockObject.snapshot.workbook?.originalMeta as Partial<IWorkbookData>;

        originSnapshotSheetBlockObject.snapshot.doc = undefined;
        originSnapshotSheetBlockObject.snapshot.unitID = snapshotSheetBlockObject.snapshot.unitID;
        originSnapshotSheetBlockObject.snapshot.workbook!.rev = snapshotSheetBlockObject.snapshot.rev;
        originSnapshotSheetBlockObject.snapshot.workbook!.creator = '';
        originSnapshotSheetBlockObject.snapshot.workbook!.name = '';
        originMeta.locale = LocaleType.EN_US;

        const sheetBlocks = Tools.deepClone(snapshotSheetBlockObject.sheetBlocks);
        const originSheetBlocks = Tools.deepClone(originSnapshotSheetBlockObject.sheetBlocks);

        snapshotSheetBlockObject.sheetBlocks = {};
        snapshotSheetBlockObject.snapshot.workbook.blockMeta = {};
        originSnapshotSheetBlockObject.sheetBlocks = {};
        if (originSnapshotSheetBlockObject && originSnapshotSheetBlockObject.snapshot && originSnapshotSheetBlockObject.snapshot.workbook) {
            originSnapshotSheetBlockObject.snapshot.workbook.blockMeta = {};
        }

        expect(snapshotSheetBlockObject).toStrictEqual(originSnapshotSheetBlockObject);
        function getData(sheetBlocks: ISheetBlockObject) {
            return Object.keys(sheetBlocks).map((key) => {
                return sheetBlocks[key].data;
            });
        }

        expect(getData(sheetBlocks)).toStrictEqual(getData(originSheetBlocks));
    });
});
