/**
 * Copyright 2023-present DreamNum Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { IFunctionNames } from '../basics/function';
import { FUNCTION_NAMES_DATE } from './date/function-names';
import { FUNCTION_NAMES_ENGINEERING } from './engineering/function-names';
import { FUNCTION_NAMES_FINANCIAL } from './financial/function-names';
import { FUNCTION_NAMES_INFORMATION } from './information/function-names';
import { FUNCTION_NAMES_LOGICAL } from './logical/function-names';
import { FUNCTION_NAMES_LOOKUP } from './lookup/function-names';
import { FUNCTION_NAMES_MATH } from './math/function-names';
import { FUNCTION_NAMES_STATISTICAL } from './statistical/function-names';
import { FUNCTION_NAMES_TEXT } from './text/function-names';
import { FUNCTION_NAMES_WEB } from './web/function-names';

export const NEW_EXCEL_FUNCTIONS = new Set<IFunctionNames>([
    // Trigonometric & Math extensions
    FUNCTION_NAMES_MATH.ACOT,
    FUNCTION_NAMES_MATH.ACOTH,
    FUNCTION_NAMES_MATH.ARABIC,
    FUNCTION_NAMES_MATH.BASE,
    FUNCTION_NAMES_MATH.CEILING_MATH,
    FUNCTION_NAMES_MATH.CEILING_PRECISE,
    FUNCTION_NAMES_MATH.COMBINA,
    FUNCTION_NAMES_MATH.COT,
    FUNCTION_NAMES_MATH.COTH,
    FUNCTION_NAMES_MATH.CSC,
    FUNCTION_NAMES_MATH.CSCH,
    FUNCTION_NAMES_MATH.DECIMAL,
    FUNCTION_NAMES_MATH.FLOOR_MATH,
    FUNCTION_NAMES_MATH.FLOOR_PRECISE,
    FUNCTION_NAMES_MATH.MUNIT,
    FUNCTION_NAMES_MATH.RANDARRAY,
    FUNCTION_NAMES_MATH.SEC,
    FUNCTION_NAMES_MATH.SECH,
    FUNCTION_NAMES_MATH.SEQUENCE,

    // Dynamic array functions
    FUNCTION_NAMES_LOOKUP.CHOOSECOLS,
    FUNCTION_NAMES_LOOKUP.CHOOSEROWS,
    FUNCTION_NAMES_LOOKUP.DROP,
    FUNCTION_NAMES_LOOKUP.EXPAND,
    FUNCTION_NAMES_LOOKUP.FILTER,
    FUNCTION_NAMES_LOOKUP.FORMULATEXT,
    FUNCTION_NAMES_LOOKUP.HSTACK,
    FUNCTION_NAMES_LOOKUP.SORT,
    FUNCTION_NAMES_LOOKUP.SORTBY,
    FUNCTION_NAMES_LOOKUP.TAKE,
    FUNCTION_NAMES_LOOKUP.TOCOL,
    FUNCTION_NAMES_LOOKUP.TOROW,
    FUNCTION_NAMES_LOOKUP.UNIQUE,
    FUNCTION_NAMES_LOOKUP.VSTACK,
    FUNCTION_NAMES_LOOKUP.WRAPCOLS,
    FUNCTION_NAMES_LOOKUP.WRAPROWS,
    FUNCTION_NAMES_LOOKUP.XLOOKUP,
    FUNCTION_NAMES_LOOKUP.XMATCH,

    // Bitwise and complex math
    FUNCTION_NAMES_ENGINEERING.BITAND,
    FUNCTION_NAMES_ENGINEERING.BITLSHIFT,
    FUNCTION_NAMES_ENGINEERING.BITOR,
    FUNCTION_NAMES_ENGINEERING.BITRSHIFT,
    FUNCTION_NAMES_ENGINEERING.BITXOR,
    FUNCTION_NAMES_ENGINEERING.ERF_PRECISE,
    FUNCTION_NAMES_ENGINEERING.ERFC_PRECISE,
    FUNCTION_NAMES_ENGINEERING.IMCOSH,
    FUNCTION_NAMES_ENGINEERING.IMCOT,
    FUNCTION_NAMES_ENGINEERING.IMCSC,
    FUNCTION_NAMES_ENGINEERING.IMCSCH,
    FUNCTION_NAMES_ENGINEERING.IMSEC,
    FUNCTION_NAMES_ENGINEERING.IMSECH,
    FUNCTION_NAMES_ENGINEERING.IMSINH,
    FUNCTION_NAMES_ENGINEERING.IMTAN,

    // Information functions
    FUNCTION_NAMES_INFORMATION.ISFORMULA,
    FUNCTION_NAMES_INFORMATION.SHEET,
    FUNCTION_NAMES_INFORMATION.SHEETS,

    // Logical extensions
    FUNCTION_NAMES_LOGICAL.IFNA,
    FUNCTION_NAMES_LOGICAL.IFS,
    FUNCTION_NAMES_LOGICAL.SWITCH,
    FUNCTION_NAMES_LOGICAL.XOR,

    // Statistical and text extensions
    FUNCTION_NAMES_STATISTICAL.BETA_DIST,
    FUNCTION_NAMES_STATISTICAL.BETA_INV,
    FUNCTION_NAMES_STATISTICAL.BINOM_DIST,
    FUNCTION_NAMES_STATISTICAL.BINOM_DIST_RANGE,
    FUNCTION_NAMES_STATISTICAL.BINOM_INV,
    FUNCTION_NAMES_STATISTICAL.CHISQ_DIST,
    FUNCTION_NAMES_STATISTICAL.CHISQ_DIST_RT,
    FUNCTION_NAMES_STATISTICAL.CHISQ_INV,
    FUNCTION_NAMES_STATISTICAL.CHISQ_INV_RT,
    FUNCTION_NAMES_STATISTICAL.CHISQ_TEST,
    FUNCTION_NAMES_STATISTICAL.CONFIDENCE_NORM,
    FUNCTION_NAMES_STATISTICAL.CONFIDENCE_T,
    FUNCTION_NAMES_STATISTICAL.COVARIANCE_P,
    FUNCTION_NAMES_STATISTICAL.COVARIANCE_S,
    FUNCTION_NAMES_STATISTICAL.EXPON_DIST,
    FUNCTION_NAMES_STATISTICAL.F_DIST,
    FUNCTION_NAMES_STATISTICAL.F_DIST_RT,
    FUNCTION_NAMES_STATISTICAL.F_INV,
    FUNCTION_NAMES_STATISTICAL.F_INV_RT,
    FUNCTION_NAMES_STATISTICAL.F_TEST,
    FUNCTION_NAMES_STATISTICAL.FORECAST_LINEAR,
    FUNCTION_NAMES_STATISTICAL.GAMMA,
    FUNCTION_NAMES_STATISTICAL.GAMMA_DIST,
    FUNCTION_NAMES_STATISTICAL.GAMMA_INV,
    FUNCTION_NAMES_STATISTICAL.GAMMALN_PRECISE,
    FUNCTION_NAMES_STATISTICAL.GAUSS,
    FUNCTION_NAMES_STATISTICAL.HYPGEOM_DIST,
    FUNCTION_NAMES_STATISTICAL.LOGNORM_DIST,
    FUNCTION_NAMES_STATISTICAL.LOGNORM_INV,
    FUNCTION_NAMES_STATISTICAL.MAXIFS,
    FUNCTION_NAMES_STATISTICAL.MINIFS,
    FUNCTION_NAMES_STATISTICAL.MODE_MULT,
    FUNCTION_NAMES_STATISTICAL.MODE_SNGL,
    FUNCTION_NAMES_STATISTICAL.NEGBINOM_DIST,
    FUNCTION_NAMES_STATISTICAL.NORM_DIST,
    FUNCTION_NAMES_STATISTICAL.NORM_INV,
    FUNCTION_NAMES_STATISTICAL.NORM_S_DIST,
    FUNCTION_NAMES_STATISTICAL.NORM_S_INV,
    FUNCTION_NAMES_STATISTICAL.PERCENTILE_EXC,
    FUNCTION_NAMES_STATISTICAL.PERCENTILE_INC,
    FUNCTION_NAMES_STATISTICAL.PERCENTRANK_EXC,
    FUNCTION_NAMES_STATISTICAL.PERCENTRANK_INC,
    FUNCTION_NAMES_STATISTICAL.PERMUTATIONA,
    FUNCTION_NAMES_STATISTICAL.PHI,
    FUNCTION_NAMES_STATISTICAL.POISSON_DIST,
    FUNCTION_NAMES_STATISTICAL.QUARTILE_EXC,
    FUNCTION_NAMES_STATISTICAL.QUARTILE_INC,
    FUNCTION_NAMES_STATISTICAL.RANK_AVG,
    FUNCTION_NAMES_STATISTICAL.RANK_EQ,
    FUNCTION_NAMES_STATISTICAL.SKEW_P,
    FUNCTION_NAMES_STATISTICAL.STDEV_P,
    FUNCTION_NAMES_STATISTICAL.STDEV_S,
    FUNCTION_NAMES_STATISTICAL.T_DIST,
    FUNCTION_NAMES_STATISTICAL.T_DIST_2T,
    FUNCTION_NAMES_STATISTICAL.T_DIST_RT,
    FUNCTION_NAMES_STATISTICAL.T_INV,
    FUNCTION_NAMES_STATISTICAL.T_INV_2T,
    FUNCTION_NAMES_STATISTICAL.T_TEST,
    FUNCTION_NAMES_STATISTICAL.VAR_P,
    FUNCTION_NAMES_STATISTICAL.VAR_S,
    FUNCTION_NAMES_STATISTICAL.WEIBULL_DIST,
    FUNCTION_NAMES_STATISTICAL.Z_TEST,

    // Text and encoding
    FUNCTION_NAMES_TEXT.ARRAYTOTEXT,
    FUNCTION_NAMES_WEB.ENCODEURL,
    FUNCTION_NAMES_TEXT.NUMBERVALUE,
    FUNCTION_NAMES_TEXT.TEXTAFTER,
    FUNCTION_NAMES_TEXT.TEXTBEFORE,
    FUNCTION_NAMES_TEXT.TEXTJOIN,
    FUNCTION_NAMES_TEXT.TEXTSPLIT,
    FUNCTION_NAMES_TEXT.UNICHAR,
    FUNCTION_NAMES_TEXT.UNICODE,
    FUNCTION_NAMES_TEXT.VALUETOTEXT,

    // Date & time
    FUNCTION_NAMES_DATE.DAYS,
    FUNCTION_NAMES_DATE.ISOWEEKNUM,
    FUNCTION_NAMES_FINANCIAL.PDURATION,
    FUNCTION_NAMES_FINANCIAL.RRI,

    FUNCTION_NAMES_LOGICAL.BYCOL,
    FUNCTION_NAMES_LOGICAL.BYROW,
    FUNCTION_NAMES_LOGICAL.MAKEARRAY,
    FUNCTION_NAMES_LOGICAL.MAP,
    FUNCTION_NAMES_LOGICAL.REDUCE,
    FUNCTION_NAMES_LOGICAL.SCAN,
]);
