export const DefaultSheetRightMenuConfig = {
    InsertRow: true,
    InsertColumn: true,
    AddRowTop: true,
    AddRowBottom: true,
    AddColumnLeft: true,
    AddColumnRight: true,
    DeleteRow: true,
    DeleteColumn: true,
    HideRow: true,
    ShowRow: true,
    RowHeight: true,
    HideColumn: true,
    ShowColumn: true,
    ColumnWidth: true,
    DeleteCell: true,
    ClearContent: true,
    Matrix: true,
};
