/**
 * Copyright 2023-present DreamNum Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum FUNCTION_NAMES_MATH {
    ABS = 'ABS',
    ACOS = 'ACOS',
    ACOSH = 'ACOSH',
    ACOT = 'ACOT',
    ACOTH = 'ACOTH',
    AGGREGATE = 'AGGREGATE',
    ARABIC = 'ARABIC',
    ASIN = 'ASIN',
    ASINH = 'ASINH',
    ATAN = 'ATAN',
    ATAN2 = 'ATAN2',
    ATANH = 'ATANH',
    BASE = 'BASE',
    CEILING = 'CEILING',
    CEILING_MATH = 'CEILING.MATH',
    CEILING_PRECISE = 'CEILING.PRECISE',
    COMBIN = 'COMBIN',
    COMBINA = 'COMBINA',
    COS = 'COS',
    COSH = 'COSH',
    COT = 'COT',
    COTH = 'COTH',
    CSC = 'CSC',
    CSCH = 'CSCH',
    DECIMAL = 'DECIMAL',
    DEGREES = 'DEGREES',
    EVEN = 'EVEN',
    EXP = 'EXP',
    FACT = 'FACT',
    FACTDOUBLE = 'FACTDOUBLE',
    FLOOR = 'FLOOR',
    FLOOR_MATH = 'FLOOR.MATH',
    FLOOR_PRECISE = 'FLOOR.PRECISE',
    GCD = 'GCD',
    INT = 'INT',
    ISO_CEILING = 'ISO.CEILING',
    LCM = 'LCM',
    LET = 'LET',
    LN = 'LN',
    LOG = 'LOG',
    LOG10 = 'LOG10',
    MDETERM = 'MDETERM',
    MINVERSE = 'MINVERSE',
    MMULT = 'MMULT',
    MOD = 'MOD',
    MROUND = 'MROUND',
    MULTINOMIAL = 'MULTINOMIAL',
    MUNIT = 'MUNIT',
    ODD = 'ODD',
    PI = 'PI',
    POWER = 'POWER',
    PRODUCT = 'PRODUCT',
    QUOTIENT = 'QUOTIENT',
    RADIANS = 'RADIANS',
    RAND = 'RAND',
    RANDARRAY = 'RANDARRAY',
    RANDBETWEEN = 'RANDBETWEEN',
    ROMAN = 'ROMAN',
    ROUND = 'ROUND',
    ROUNDBANK = 'ROUNDBANK',
    ROUNDDOWN = 'ROUNDDOWN',
    ROUNDUP = 'ROUNDUP',
    SEC = 'SEC',
    SECH = 'SECH',
    SERIESSUM = 'SERIESSUM',
    SEQUENCE = 'SEQUENCE',
    SIGN = 'SIGN',
    SIN = 'SIN',
    SINH = 'SINH',
    SQRT = 'SQRT',
    SQRTPI = 'SQRTPI',
    SUBTOTAL = 'SUBTOTAL',
    SUM = 'SUM',
    SUMIF = 'SUMIF',
    SUMIFS = 'SUMIFS',
    SUMPRODUCT = 'SUMPRODUCT',
    SUMSQ = 'SUMSQ',
    SUMX2MY2 = 'SUMX2MY2',
    SUMX2PY2 = 'SUMX2PY2',
    SUMXMY2 = 'SUMXMY2',
    TAN = 'TAN',
    TANH = 'TANH',
    TRUNC = 'TRUNC',
}
