/**
 * Name set of all action
 */
export enum ACTION_NAMES {
    /** @see src/Command/Action/InsertDataRowAction */
    INSERT_ROW_DATA_ACTION = 'InsertRowDataAction',
    REMOVE_ROW_DATA_ACTION = 'RemoveRowDataAction',
    INSERT_ROW_ACTION = 'InsertRowAction',
    REMOVE_ROW_ACTION = 'RemoveRowAction',
    SET_RANGE_STYLE_ACTION = 'SetRangeStyleAction',
    SET_RANGE_FORMULA_ACTION = 'SetRangeFormulaAction',
    SET_RANGE_FORMAT_ACTION = 'SetRangeFormatAction',
    SET_SELECTION_ACTION = 'SetSelectionActivateAction',
    SET_RANGE_DATA_ACTION = 'SetRangeDataAction',
    SET_RANGE_VALUE_ACTION = 'SetRangeValueAction',
    SET_RANGE_NOTE_ACTION = 'SetRangeNoteAction',
    DELETE_RANGE_ACTION = 'DeleteRangeAction',
    INSERT_SHEET_ACTION = 'InsertSheetAction',
    REMOVE_SHEET_ACTION = 'RemoveSheetAction',
    CLEAR_RANGE_ACTION = 'ClearRangeAction',
    INSERT_RANGE_ACTION = 'InsertRangeAction',
    SET_TAB_COLOR_ACTION = 'SetTabColorAction',
    HIDE_SHEET_ACTION = 'SetWorkSheetHideAction',
    SET_WORKSHEET_ACTIVATE_ACTION = 'SetWorkSheetActivateAction',
    INSERT_COLUMN_ACTION = 'InsertColumnAction',
    INSERT_COLUMN_DATA_ACTION = 'InsertColumnDataAction',
    REMOVE_COLUMN_ACTION = 'RemoveColumnAction',
    REMOVE_COLUMN_DATA_ACTION = 'RemoveColumnDataAction',
    SET_HIDE_ROW_ACTION = 'SetRowHideAction',
    SET_HIDE_COLUMN_ACTION = 'SetColumnHideAction',
    SET_SHOW_ROW_ACTION = 'SetRowShowAction',
    SET_SHOW_COLUMN_ACTION = 'SetColumnShowAction',
    ADD_MERGE_ACTION = 'AddMergeAction',
    REMOVE_MERGE_ACTION = 'RemoveMergeAction',
    SET_WORKSHEET_NAME_ACTION = 'SetWorkSheetNameAction',
    SET_WORKSHEET_STATUS_ACTION = 'SetWorkSheetStatusAction',
    SET_BORDER_ACTION = 'SetBorderAction',
    SET_COLUMN_WIDTH_ACTION = 'SetColumnWidthAction',
    SET_ROW_HEIGHT_ACTION = 'SetRowHeightAction',
    SET_HIDDEN_GRIDLINES_ACTION = 'SetHiddenGridlinesAction',
    SET_FROZEN_COLUMNS_ACTION = 'SetFrozenColumnsAction',
    SET_FROZEN_ROWS_ACTION = 'SetFrozenRowsAction',
    SET_RIGHT_TO_LEFT_ACTION = 'SetRightToLeftAction',
    SET_COLLAPSE_ALL_ROW_GROUPS_ACTION = 'SetCollapseAllRowGroupsAction',
    SET_COLLAPSE_ALL_COLUMN_GROUPS_ACTION = 'SetCollapseAllColumnGroupsAction',
    DELETE_BANDING_ACTION = 'DeleteBandingAction',
    SET_BANDING_ACTION = 'SetBandingAction',
    ADD_BANDING_ACTION = 'AddBandingAction',
    DELETE_NAMED_RANGE_ACTION = 'DeleteNamedRangeAction',
    SET_NAMED_RANGE_ACTION = 'SetNamedRangeAction',
    ADD_NAMED_RANGE_ACTION = 'AddNamedRangeAction',
    SET_SHEET_ORDER_ACTION = 'SetSheetOrderAction',
}
