export enum DOC_ACTION_NAMES {
    INSERT_TEXT_ACTION_NAME = 'InsertTextAction',
    DELETE_TEXT_ACTION_NAME = 'DeleteTextAction',
    CLEAR_TEXT_STYLE_ACTION_NAME = 'ClearTextStyleAction',
    DELETE_PARAGRAPH_ACTION_NAME = 'DeleteParagraphAction',
    INSERT_PARAGRAPH_ACTION_NAME = 'InsertParagraphAction',
    MERGE_PARAGRAPH_ACTION_NAME = 'MergeParagraphAction',
    MOVE_PARAGRAPH_ACTION_NAME = 'MoveParagraphAction',
    SET_TEXT_STYLE_ACTION_NAME = 'SetTextStyleAction',
    SPLIT_PARAGRAPH_ACTION_NAME = 'SplitParagraphAction',
    UPDATE_DOCUMENT_STYLE_ACTION_NAME = 'UpdateDocumentAction',
    UPDATE_PARAGRAPH_STYLE_ACTION_NAME = 'UpdateParagraphAction',
    UPDATE_SECTION_ACTION_NAME = 'UpdateSectionAction',

    DELETE_BULLET_ACTION_NAME = 'DeleteBulletAction',
    DELETE_PARAGRAPH_BULLET_ACTION_NAME = 'DeleteParagraphBulletAction',
    DELETE_SECTION_ACTION_NAME = 'DeleteSectionAction',
    INSERT_BULLET_ACTION_NAME = 'InsertBulletAction',
    INSERT_PARAGRAPH_BULLET_ACTION_NAME = 'InsertParagraphBulletAction',
    INSERT_SECTION_ACTION_NAME = 'InsertSectionAction',
    UPDATE_BULLET_ACTION_NAME = 'UpdateBulletAction',
    UPDATE_PARAGRAPH_BULLET_ACTION_NAME = 'UpdateParagraphBulletAction',

    TEXT_INDEX_ADJUST_ACTION_NAME = 'TextIndexAdjustAction',
}
