/**
 * Copyright 2023-present DreamNum Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { LocaleKey } from '../../locale/types';

export type SymbolCategory = 'mathematics' | 'greek' | 'common';

export interface ISymbolCategory {
    key: SymbolCategory;
    symbols: string[];
    titleKey: LocaleKey;
}

export const SYMBOL_CATEGORIES: ISymbolCategory[] = [
    {
        key: 'mathematics',
        titleKey: 'ui.symbolPicker.mathematics',
        symbols: [
            '+',
            '−',
            '×',
            '÷',
            '≠',
            '≈',
            '<',
            '>',
            '≤',
            '≥',
            '≪',
            '≫',
            '≡',
            '±',
            '%',
            '‰',
            '‱',
            '½',
            '⅓',
            '⅔',
            '¼',
            '¾',
            '¹',
            '²',
            '³',
            'ⁿ',
            '₁',
            '₂',
            '₃',
            '|a|',
            '∟',
            '∠',
            '⊿',
            '△',
            '∥',
            '⊥',
            '∫',
            '∬',
            '∭',
            '∮',
            '∯',
            '∰',
            '∝',
            '∞',
            '∼',
            '≌',
            '∈',
            '∉',
            '⊆',
            '⊂',
            '∅',
            '∩',
            '∪',
            '∧',
            '∨',
            '⋅',
            '⋮',
            '⋰',
            '⋱',
            '⋯',
            '∏',
            '∑',
            '∃',
            '∄',
            '∀',
            '∂',
            '∆',
            '⊙',
            '⊕',
            '%',
        ],
    },
    {
        key: 'greek',
        titleKey: 'ui.symbolPicker.greek',
        symbols: [
            'α',
            'β',
            'γ',
            'δ',
            'ε',
            'ζ',
            'η',
            'θ',
            'ι',
            'κ',
            'λ',
            'μ',
            'ν',
            'ξ',
            'ο',
            'π',
            'ρ',
            'σ',
            'τ',
            'υ',
            'φ',
            'χ',
            'ψ',
            'ω',
            'Α',
            'Β',
            'Γ',
            'Δ',
            'Ε',
            'Ζ',
            'Η',
            'Θ',
            'Ι',
            'Κ',
            'Λ',
            'Μ',
            'Ν',
            'Ξ',
            'Ο',
            'Π',
            'Ρ',
            'Σ',
            'Τ',
            'Υ',
            'Φ',
            'Χ',
            'Ψ',
            'Ω',
        ],
    },
    {
        key: 'common',
        titleKey: 'ui.symbolPicker.common',
        symbols: [
            'kg',
            'mm',
            'cm',
            'm²',
            '°C',
            '°',
            '§',
            '◎',
            '©',
            '®',
            '{',
            '⌜',
            '〚',
            '№',
            '$',
            '¥',
            '@',
            '&',
            '*',
            '|',
            '#',
            '※',
            '√',
            '×',
            '…',
            '①',
            '②',
            '③',
            '↑',
            '↓',
            '←',
            '→',
        ],
    },
];
