/**
 * Copyright 2023-present DreamNum Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum FUNCTION_NAMES_STATISTICAL {
    AVEDEV = 'AVEDEV',
    AVERAGE = 'AVERAGE',
    AVERAGE_WEIGHTED = 'AVERAGE.WEIGHTED',
    AVERAGEA = 'AVERAGEA',
    AVERAGEIF = 'AVERAGEIF',
    AVERAGEIFS = 'AVERAGEIFS',
    BETA_DIST = 'BETA.DIST',
    BETA_INV = 'BETA.INV',
    BINOM_DIST = 'BINOM.DIST',
    BINOM_DIST_RANGE = 'BINOM.DIST.RANGE',
    BINOM_INV = 'BINOM.INV',
    CHISQ_DIST = 'CHISQ.DIST',
    CHISQ_DIST_RT = 'CHISQ.DIST.RT',
    CHISQ_INV = 'CHISQ.INV',
    CHISQ_INV_RT = 'CHISQ.INV.RT',
    CHISQ_TEST = 'CHISQ.TEST',
    CONFIDENCE_NORM = 'CONFIDENCE.NORM',
    CONFIDENCE_T = 'CONFIDENCE.T',
    CORREL = 'CORREL',
    COUNT = 'COUNT',
    COUNTA = 'COUNTA',
    COUNTBLANK = 'COUNTBLANK',
    COUNTIF = 'COUNTIF',
    COUNTIFS = 'COUNTIFS',
    COVARIANCE_P = 'COVARIANCE.P',
    COVARIANCE_S = 'COVARIANCE.S',
    DEVSQ = 'DEVSQ',
    EXPON_DIST = 'EXPON.DIST',
    F_DIST = 'F.DIST',
    F_DIST_RT = 'F.DIST.RT',
    F_INV = 'F.INV',
    F_INV_RT = 'F.INV.RT',
    F_TEST = 'F.TEST',
    FISHER = 'FISHER',
    FISHERINV = 'FISHERINV',
    FORECAST = 'FORECAST',
    FORECAST_ETS = 'FORECAST.ETS',
    FORECAST_ETS_CONFINT = 'FORECAST.ETS.CONFINT',
    FORECAST_ETS_SEASONALITY = 'FORECAST.ETS.SEASONALITY',
    FORECAST_ETS_STAT = 'FORECAST.ETS.STAT',
    FORECAST_LINEAR = 'FORECAST.LINEAR',
    FREQUENCY = 'FREQUENCY',
    GAMMA = 'GAMMA',
    GAMMA_DIST = 'GAMMA.DIST',
    GAMMA_INV = 'GAMMA.INV',
    GAMMALN = 'GAMMALN',
    GAMMALN_PRECISE = 'GAMMALN.PRECISE',
    GAUSS = 'GAUSS',
    GEOMEAN = 'GEOMEAN',
    GROWTH = 'GROWTH',
    HARMEAN = 'HARMEAN',
    HYPGEOM_DIST = 'HYPGEOM.DIST',
    INTERCEPT = 'INTERCEPT',
    KURT = 'KURT',
    LARGE = 'LARGE',
    LINEST = 'LINEST',
    LOGEST = 'LOGEST',
    LOGNORM_DIST = 'LOGNORM.DIST',
    LOGNORM_INV = 'LOGNORM.INV',
    MARGINOFERROR = 'MARGINOFERROR',
    MAX = 'MAX',
    MAXA = 'MAXA',
    MAXIFS = 'MAXIFS',
    MEDIAN = 'MEDIAN',
    MIN = 'MIN',
    MINA = 'MINA',
    MINIFS = 'MINIFS',
    MODE_MULT = 'MODE.MULT',
    MODE_SNGL = 'MODE.SNGL',
    NEGBINOM_DIST = 'NEGBINOM.DIST',
    NORM_DIST = 'NORM.DIST',
    NORM_INV = 'NORM.INV',
    NORM_S_DIST = 'NORM.S.DIST',
    NORM_S_INV = 'NORM.S.INV',
    PEARSON = 'PEARSON',
    PERCENTILE_EXC = 'PERCENTILE.EXC',
    PERCENTILE_INC = 'PERCENTILE.INC',
    PERCENTRANK_EXC = 'PERCENTRANK.EXC',
    PERCENTRANK_INC = 'PERCENTRANK.INC',
    PERMUT = 'PERMUT',
    PERMUTATIONA = 'PERMUTATIONA',
    PHI = 'PHI',
    POISSON_DIST = 'POISSON.DIST',
    PROB = 'PROB',
    QUARTILE_EXC = 'QUARTILE.EXC',
    QUARTILE_INC = 'QUARTILE.INC',
    RANK_AVG = 'RANK.AVG',
    RANK_EQ = 'RANK.EQ',
    RSQ = 'RSQ',
    SKEW = 'SKEW',
    SKEW_P = 'SKEW.P',
    SLOPE = 'SLOPE',
    SMALL = 'SMALL',
    STANDARDIZE = 'STANDARDIZE',
    STDEV_P = 'STDEV.P',
    STDEV_S = 'STDEV.S',
    STDEVA = 'STDEVA',
    STDEVPA = 'STDEVPA',
    STEYX = 'STEYX',
    T_DIST = 'T.DIST',
    T_DIST_2T = 'T.DIST.2T',
    T_DIST_RT = 'T.DIST.RT',
    T_INV = 'T.INV',
    T_INV_2T = 'T.INV.2T',
    T_TEST = 'T.TEST',
    TREND = 'TREND',
    TRIMMEAN = 'TRIMMEAN',
    VAR_P = 'VAR.P',
    VAR_S = 'VAR.S',
    VARA = 'VARA',
    VARPA = 'VARPA',
    WEIBULL_DIST = 'WEIBULL.DIST',
    Z_TEST = 'Z.TEST',
}
