/**
 * Copyright 2023-present DreamNum Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Derived from numfmt 3.2.6 (MIT), commit c2cfdfa01bb1f24df51e985825671eb480daed4c.
// See packages/core/src/shared/numfmt/LICENSE.

// @vitest-environment node

import { numfmtTest } from './test-utils';

numfmtTest('Validity tests', (t) => {
    t.validFormat('" Excellent"', '" Excellent"');
    t.validFormat('" Fair"', '" Fair"');
    t.validFormat('" Good"', '" Good"');
    t.validFormat('" Poor"', '" Poor"');
    t.validFormat('" Very Good"', '" Very Good"');
    t.validFormat('"$"#,##0', '"$"#,##0');
    t.validFormat('"$"#,##0.00', '"$"#,##0.00');
    t.validFormat('"$"#,##0.00_);[Red]\\("$"#,##0.00\\)', '"$"#,##0.00_);[Red]\\("$"#,##0.00\\)');
    t.validFormat('"$"#,##0.00_);\\("$"#,##0.00\\)', '"$"#,##0.00_);\\("$"#,##0.00\\)');
    t.validFormat('"$"#,##0;[Red]\\-"$"#,##0', '"$"#,##0;[Red]\\-"$"#,##0');
    t.validFormat('"$"#,##0_);[Red]\\("$"#,##0\\)', '"$"#,##0_);[Red]\\("$"#,##0\\)');
    t.validFormat('"$"#,##0_);\\("$"#,##0\\)', '"$"#,##0_);\\("$"#,##0\\)');
    t.validFormat('"Haha!"\\ @\\ "Yeah!"', '"Haha!"\\ @\\ "Yeah!"');
    t.validFormat('"TRUE";"TRUE";"FALSE"', '"TRUE";"TRUE";"FALSE"');
    t.validFormat('"True";"True";"False";@', '"True";"True";"False";@');
    t.validFormat('"Years: "0', '"Years: "0');
    t.validFormat('"Yes";"Yes";"No";@', '"Yes";"Yes";"No";@');
    t.validFormat('"kl "hh:mm:ss;@', '"kl "hh:mm:ss;@');
    t.validFormat('"£"#,##0.00', '"£"#,##0.00');
    t.validFormat('"£"#,##0;[Red]\\-"£"#,##0', '"£"#,##0;[Red]\\-"£"#,##0');
    t.validFormat('"€"#,##0.00', '"€"#,##0.00');
    t.validFormat('"€"\\ #,##0.00_-', '"€"\\ #,##0.00_-');
    t.validFormat('"上午/下午 "hh"時"mm"分"ss"秒 "', '"上午/下午 "hh"時"mm"分"ss"秒 "');
    t.validFormat('"￥"#,##0.00;"￥"\\-#,##0.00', '"￥"#,##0.00;"￥"\\-#,##0.00');
    t.validFormat('#', '#');
    t.validFormat('# ?/?', '# ?/?');
    t.validFormat('# ??/??', '# ??/??');
    t.validFormat('#" "?/?', '#" "?/?');
    t.validFormat('#" "??/??', '#" "??/??');
    t.validFormat('#"abded"\\ ??/??', '#"abded"\\ ??/??');
    t.validFormat('###0.00;-###0.00', '###0.00;-###0.00');
    t.validFormat('###0;-###0', '###0;-###0');
    t.validFormat('##0.0E+0', '##0.0E+0');
    t.validFormat('#,##0', '#,##0');
    t.validFormat('#,##0 ;(#,##0)', '#,##0 ;(#,##0)');
    t.validFormat('#,##0 ;[Red](#,##0)', '#,##0 ;[Red](#,##0)');
    t.validFormat('#,##0"р.";[Red]\\-#,##0"р."', '#,##0"р.";[Red]\\-#,##0"р."');
    t.validFormat('#,##0.0', '#,##0.0');
    t.validFormat('#,##0.00', '#,##0.00');
    t.validFormat('#,##0.00 "�"', '#,##0.00 "�"');
    t.validFormat('#,##0.00 €;-#,##0.00 €', '#,##0.00 €;-#,##0.00 €');
    t.validFormat('#,##0.00"р.";[Red]\\-#,##0.00"р."', '#,##0.00"р.";[Red]\\-#,##0.00"р."');
    t.validFormat('#,##0.000', '#,##0.000');
    t.validFormat('#,##0.0000', '#,##0.0000');
    t.validFormat('#,##0.00000', '#,##0.00000');
    t.validFormat('#,##0.000000', '#,##0.000000');
    t.validFormat('#,##0.0000000', '#,##0.0000000');
    t.validFormat('#,##0.00000000', '#,##0.00000000');
    t.validFormat('#,##0.000000000', '#,##0.000000000');
    t.validFormat('#,##0.00000000;[Red]#,##0.00000000', '#,##0.00000000;[Red]#,##0.00000000');
    t.validFormat('#,##0.0000_ ', '#,##0.0000_ ');
    t.validFormat('#,##0.000_ ', '#,##0.000_ ');
    t.validFormat('#,##0.000_);\\(#,##0.000\\)', '#,##0.000_);\\(#,##0.000\\)');
    t.validFormat('#,##0.00;(#,##0.00)', '#,##0.00;(#,##0.00)');
    t.validFormat('#,##0.00;(#,##0.00);0.00', '#,##0.00;(#,##0.00);0.00');
    t.validFormat('#,##0.00;[Red](#,##0.00)', '#,##0.00;[Red](#,##0.00)');
    t.validFormat('#,##0.00;[Red]\\(#,##0.00\\)', '#,##0.00;[Red]\\(#,##0.00\\)');
    t.validFormat('#,##0.00;\\(#,##0.00\\)', '#,##0.00;\\(#,##0.00\\)');
    t.validFormat('#,##0.00[$₹-449]_);\\(#,##0.00[$₹-449]\\)', '#,##0.00[$₹-449]_);\\(#,##0.00[$₹-449]\\)');
    t.validFormat('#,##0.00\\ "р."', '#,##0.00\\ "р."');
    t.validFormat('#,##0.00\\ "р.";[Red]\\-#,##0.00\\ "р."', '#,##0.00\\ "р.";[Red]\\-#,##0.00\\ "р."');
    t.validFormat('#,##0.00\\ [$€-407]', '#,##0.00\\ [$€-407]');
    t.validFormat('#,##0.00\\ [$€-40C]', '#,##0.00\\ [$€-40C]');
    t.validFormat('#,##0.00_);\\(#,##0.00\\)', '#,##0.00_);\\(#,##0.00\\)');
    t.validFormat('#,##0.00_р_.;[Red]\\-#,##0.00_р_.', '#,##0.00_р_.;[Red]\\-#,##0.00_р_.');
    t.validFormat('#,##0.00_р_.;\\-#,##0.00_р_.', '#,##0.00_р_.;\\-#,##0.00_р_.');
    t.validFormat('#,##0.0;[Red]#,##0.0', '#,##0.0;[Red]#,##0.0');
    t.validFormat('#,##0.0_ ;\\-#,##0.0\\ ', '#,##0.0_ ;\\-#,##0.0\\ ');
    t.validFormat('#,##0.0_);[Red]\\(#,##0.0\\)', '#,##0.0_);[Red]\\(#,##0.0\\)');
    t.validFormat('#,##0.0_);\\(#,##0.0\\)', '#,##0.0_);\\(#,##0.0\\)');
    t.validFormat('#,##0;\\-#,##0;0', '#,##0;\\-#,##0;0');
    t.validFormat('#,##0\\ "р.";[Red]\\-#,##0\\ "р."', '#,##0\\ "р.";[Red]\\-#,##0\\ "р."');
    t.validFormat('#,##0\\ "р.";\\-#,##0\\ "р."', '#,##0\\ "р.";\\-#,##0\\ "р."');
    t.validFormat('#,##0\\ ;[Red]\\(#,##0\\)', '#,##0\\ ;[Red]\\(#,##0\\)');
    t.validFormat('#,##0\\ ;\\(#,##0\\)', '#,##0\\ ;\\(#,##0\\)');
    t.validFormat('#,##0_ ', '#,##0_ ');
    t.validFormat('#,##0_ ;[Red]\\-#,##0\\ ', '#,##0_ ;[Red]\\-#,##0\\ ');
    t.validFormat('#,##0_);[Red]\\(#,##0\\)', '#,##0_);[Red]\\(#,##0\\)');
    t.validFormat('#,##0_р_.;[Red]\\-#,##0_р_.', '#,##0_р_.;[Red]\\-#,##0_р_.');
    t.validFormat('#,##0_р_.;\\-#,##0_р_.', '#,##0_р_.;\\-#,##0_р_.');
    t.validFormat('#.0000,,', '#.0000,,');
    t.validFormat('#0', '#0');
    t.validFormat('#0.00', '#0.00');
    t.validFormat('#0.0000', '#0.0000');
    t.validFormat('#\\ ?/10', '#\\ ?/10');
    t.validFormat('#\\ ?/2', '#\\ ?/2');
    t.validFormat('#\\ ?/4', '#\\ ?/4');
    t.validFormat('#\\ ?/8', '#\\ ?/8');
    t.validFormat('#\\ ?/?', '#\\ ?/?');
    t.validFormat('#\\ ??/100', '#\\ ??/100');
    t.validFormat('#\\ ??/100;[Red]\\(#\\ ??/16\\)', '#\\ ??/100;[Red]\\(#\\ ??/16\\)');
    t.validFormat('#\\ ??/16', '#\\ ??/16');
    t.validFormat('#\\ ??/??', '#\\ ??/??');
    t.validFormat('#\\ ??/?????????', '#\\ ??/?????????');
    t.validFormat('#\\ ???/???', '#\\ ???/???');
    t.validFormat('**\\ #,###,#00,000.00,**', '**\\ #,###,#00,000.00,**');
    t.validFormat('0', '0');
    t.validFormat('0"abde".0"??"000E+00', '0"abde".0"??"000E+00');
    t.validFormat('0%', '0%');
    t.validFormat('0.0', '0.0');
    t.validFormat('0.0%', '0.0%');
    t.validFormat('0.00', '0.00');
    t.validFormat('0.00"°"', '0.00"°"');
    t.validFormat('0.00%', '0.00%');
    t.validFormat('0.000', '0.000');
    t.validFormat('0.000%', '0.000%');
    t.validFormat('0.0000', '0.0000');
    t.validFormat('0.000000', '0.000000');
    t.validFormat('0.00000000', '0.00000000');
    t.validFormat('0.000000000', '0.000000000');
    t.validFormat('0.000000000%', '0.000000000%');
    t.validFormat('0.00000000000', '0.00000000000');
    t.validFormat('0.000000000000000', '0.000000000000000');
    t.validFormat('0.00000000E+00', '0.00000000E+00');
    t.validFormat('0.0000E+00', '0.0000E+00');
    t.validFormat('0.00;[Red]0.00', '0.00;[Red]0.00');
    t.validFormat('0.00E+00', '0.00E+00');
    t.validFormat('0.00_);[Red]\\(0.00\\)', '0.00_);[Red]\\(0.00\\)');
    t.validFormat('0.00_);\\(0.00\\)', '0.00_);\\(0.00\\)');
    t.validFormat('0.0_ ', '0.0_ ');
    t.validFormat('00.00.00.000', '00.00.00.000');
    t.validFormat('00.000%', '00.000%');
    t.validFormat('0000', '0000');
    t.validFormat('00000', '00000');
    t.validFormat('00000000', '00000000');
    t.validFormat('000000000', '000000000');
    t.validFormat('00000\\-0000', '00000\\-0000');
    t.validFormat('00000\\-00000', '00000\\-00000');
    t.validFormat('000\\-00\\-0000', '000\\-00\\-0000');
    t.validFormat('0;[Red]0', '0;[Red]0');
    t.validFormat('0\\-00000\\-00000\\-0', '0\\-00000\\-00000\\-0');
    t.validFormat('0_);[Red]\\(0\\)', '0_);[Red]\\(0\\)');
    t.validFormat('0_);\\(0\\)', '0_);\\(0\\)');
    t.validFormat('@', '@');
    t.validFormat('A/P', 'A/P');
    t.validFormat('AM/PM', 'AM/PM');
    t.validFormat('AM/PMh"時"mm"分"ss"秒";@', 'AM/PMh"時"mm"分"ss"秒";@');
    t.validFormat('D', 'D');
    t.validFormat('DD', 'DD');
    t.validFormat('DD/MM/YY;@', 'DD/MM/YY;@');
    t.validFormat('DD/MM/YYYY', 'DD/MM/YYYY');
    t.validFormat('DD/MM/YYYY;@', 'DD/MM/YYYY;@');
    t.validFormat('DDD', 'DDD');
    t.validFormat('DDDD', 'DDDD');
    t.validFormat('DDDD", "MMMM\\ DD", "YYYY', 'DDDD", "MMMM\\ DD", "YYYY');
    t.validFormat('GENERAL', 'GENERAL');
    t.validFormat('General', 'General');
    t.validFormat('H', 'H');
    t.validFormat('H:MM:SS\\ AM/PM', 'H:MM:SS\\ AM/PM');
    t.validFormat('HH:MM', 'HH:MM');
    t.validFormat('HH:MM:SS\\ AM/PM', 'HH:MM:SS\\ AM/PM');
    t.validFormat('HHM', 'HHM');
    t.validFormat('HHMM', 'HHMM');
    t.validFormat('HH[MM]', 'HH[MM]');
    t.validFormat('HH[M]', 'HH[M]');
    t.validFormat('M/D/YYYY', 'M/D/YYYY');
    t.validFormat('M/D/YYYY\\ H:MM', 'M/D/YYYY\\ H:MM');
    t.validFormat('MM/DD/YY', 'MM/DD/YY');
    t.validFormat('S', 'S');
    t.validFormat('SS', 'SS');
    t.validFormat('YY', 'YY');
    t.validFormat('YYM', 'YYM');
    t.validFormat('YYMM', 'YYMM');
    t.validFormat('YYMMM', 'YYMMM');
    t.validFormat('YYMMMM', 'YYMMMM');
    t.validFormat('YYMMMMM', 'YYMMMMM');
    t.validFormat('YYYY', 'YYYY');
    t.validFormat('YYYY-MM-DD HH:MM:SS', 'YYYY-MM-DD HH:MM:SS');
    t.validFormat('YYYY\\-MM\\-DD', 'YYYY\\-MM\\-DD');
    t.validFormat('[$$-409]#,##0', '[$$-409]#,##0');
    t.validFormat('[$$-409]#,##0.00', '[$$-409]#,##0.00');
    t.validFormat('[$$-409]#,##0.00_);[Red]\\([$$-409]#,##0.00\\)', '[$$-409]#,##0.00_);[Red]\\([$$-409]#,##0.00\\)');
    t.validFormat('[$$-C09]#,##0.00', '[$$-C09]#,##0.00');
    t.validFormat('[$-100042A]h:mm:ss\\ AM/PM;@', '[$-100042A]h:mm:ss\\ AM/PM;@');
    t.validFormat('[$-1010409]0.000%', '[$-1010409]0.000%');
    t.validFormat('[$-1010409]General', '[$-1010409]General');
    t.validFormat('[$-1010409]d/m/yyyy\\ h:mm\\ AM/PM;@', '[$-1010409]d/m/yyyy\\ h:mm\\ AM/PM;@');
    t.validFormat('[$-1010409]dddd, mmmm dd, yyyy', '[$-1010409]dddd, mmmm dd, yyyy');
    t.validFormat('[$-1010409]m/d/yyyy', '[$-1010409]m/d/yyyy');
    t.validFormat('[$-1409]h:mm:ss\\ AM/PM;@', '[$-1409]h:mm:ss\\ AM/PM;@');
    t.validFormat('[$-2000000]h:mm:ss;@', '[$-2000000]h:mm:ss;@');
    t.validFormat('[$-2010401]d/mm/yyyy\\ h:mm\\ AM/PM;@', '[$-2010401]d/mm/yyyy\\ h:mm\\ AM/PM;@');
    t.validFormat('[$-4000439]h:mm:ss\\ AM/PM;@', '[$-4000439]h:mm:ss\\ AM/PM;@');
    t.validFormat('[$-4010439]d/m/yyyy\\ h:mm\\ AM/PM;@', '[$-4010439]d/m/yyyy\\ h:mm\\ AM/PM;@');
    t.validFormat('[$-409]AM/PM\\ hh:mm:ss;@', '[$-409]AM/PM\\ hh:mm:ss;@');
    t.validFormat('[$-409]d/m/yyyy\\ hh:mm;@', '[$-409]d/m/yyyy\\ hh:mm;@');
    t.validFormat('[$-409]d\\-mmm;@', '[$-409]d\\-mmm;@');
    t.validFormat('[$-409]d\\-mmm\\-yy;@', '[$-409]d\\-mmm\\-yy;@');
    t.validFormat('[$-409]d\\-mmm\\-yyyy;@', '[$-409]d\\-mmm\\-yyyy;@');
    t.validFormat('[$-409]dd/mm/yyyy\\ hh:mm;@', '[$-409]dd/mm/yyyy\\ hh:mm;@');
    t.validFormat('[$-409]dd\\-mmm\\-yy;@', '[$-409]dd\\-mmm\\-yy;@');
    t.validFormat('[$-409]h:mm:ss\\ AM/PM;@', '[$-409]h:mm:ss\\ AM/PM;@');
    t.validFormat('[$-409]h:mm\\ AM/PM;@', '[$-409]h:mm\\ AM/PM;@');
    t.validFormat('[$-409]m/d/yy\\ h:mm\\ AM/PM;@', '[$-409]m/d/yy\\ h:mm\\ AM/PM;@');
    t.validFormat('[$-409]mmm\\-yy;@', '[$-409]mmm\\-yy;@');
    t.validFormat('[$-409]mmmm\\ d\\,\\ yyyy;@', '[$-409]mmmm\\ d\\,\\ yyyy;@');
    t.validFormat('[$-409]mmmm\\-yy;@', '[$-409]mmmm\\-yy;@');
    t.validFormat('[$-409]mmmmm;@', '[$-409]mmmmm;@');
    t.validFormat('[$-409]mmmmm\\-yy;@', '[$-409]mmmmm\\-yy;@');
    t.validFormat('[$-40E]h\\ "óra"\\ m\\ "perckor"\\ AM/PM;@', '[$-40E]h\\ "óra"\\ m\\ "perckor"\\ AM/PM;@');
    t.validFormat('[$-412]AM/PM\\ h"시"\\ mm"분"\\ ss"초";@', '[$-412]AM/PM\\ h"시"\\ mm"분"\\ ss"초";@');
    t.validFormat('[$-41C]h:mm:ss\\.AM/PM;@', '[$-41C]h:mm:ss\\.AM/PM;@');
    t.validFormat('[$-449]hh:mm:ss\\ AM/PM;@', '[$-449]hh:mm:ss\\ AM/PM;@');
    t.validFormat('[$-44E]hh:mm:ss\\ AM/PM;@', '[$-44E]hh:mm:ss\\ AM/PM;@');
    t.validFormat('[$-44F]hh:mm:ss\\ AM/PM;@', '[$-44F]hh:mm:ss\\ AM/PM;@');
    t.validFormat('[$-D000409]h:mm\\ AM/PM;@', '[$-D000409]h:mm\\ AM/PM;@');
    t.validFormat('[$-D010000]d/mm/yyyy\\ h:mm\\ "น.";@', '[$-D010000]d/mm/yyyy\\ h:mm\\ "น.";@');
    t.validFormat('[$-F400]h:mm:ss\\ AM/PM', '[$-F400]h:mm:ss\\ AM/PM');
    t.validFormat('[$-F800]dddd\\,\\ mmmm\\ dd\\,\\ yyyy', '[$-F800]dddd\\,\\ mmmm\\ dd\\,\\ yyyy');
    t.validFormat('[$AUD]\\ #,##0.00', '[$AUD]\\ #,##0.00');
    t.validFormat('[$RD$-1C0A]#,##0.00;[Red]\\-[$RD$-1C0A]#,##0.00', '[$RD$-1C0A]#,##0.00;[Red]\\-[$RD$-1C0A]#,##0.00');
    t.validFormat('[$SFr.-810]\\ #,##0.00_);[Red]\\([$SFr.-810]\\ #,##0.00\\)', '[$SFr.-810]\\ #,##0.00_);[Red]\\([$SFr.-810]\\ #,##0.00\\)');
    t.validFormat('[$£-809]#,##0.00;[Red][$£-809]#,##0.00', '[$£-809]#,##0.00;[Red][$£-809]#,##0.00');
    t.validFormat('[$¥-411]#,##0.00', '[$¥-411]#,##0.00');
    t.validFormat('[$¥-804]#,##0.00', '[$¥-804]#,##0.00');
    t.validFormat('[<0]"";0%', '[<0]"";0%');
    t.validFormat('[<=9999999]###\\-####;\\(###\\)\\ ###\\-####', '[<=9999999]###\\-####;\\(###\\)\\ ###\\-####');
    t.validFormat('[=0]?;#,##0.00', '[=0]?;#,##0.00');
    t.validFormat('[=0]?;0%', '[=0]?;0%');
    t.validFormat('[=0]?;[<4.16666666666667][hh]:mm:ss;[hh]:mm', '[=0]?;[<4.16666666666667][hh]:mm:ss;[hh]:mm');
    t.validFormat('[>999999]#,,"M";[>999]#,"K";#', '[>999999]#,,"M";[>999]#,"K";#');
    t.validFormat('[>999999]#.000,,"M";[>999]#.000,"K";#.000', '[>999999]#.000,,"M";[>999]#.000,"K";#.000');
    t.validFormat("[>=100000]0.000\\ \\\";[Red]0.000\\ \\<\\ \\>\\ \\\"\\ \\&\\ \\'\\ ", "[>=100000]0.000\\ \\\";[Red]0.000\\ \\<\\ \\>\\ \\\"\\ \\&\\ \\'\\ ");
    t.validFormat('[>=100000]0.000\\ \\<;[Red]0.000\\ \\>', '[>=100000]0.000\\ \\<;[Red]0.000\\ \\>');
    t.validFormat('[BLACK]@', '[BLACK]@');
    t.validFormat('[BLUE]GENERAL', '[BLUE]GENERAL');
    t.validFormat('[Black]@', '[Black]@');
    t.validFormat('[Blue]General', '[Blue]General');
    t.validFormat('[CYAN]@', '[CYAN]@');
    t.validFormat('[Cyan]@', '[Cyan]@');
    t.validFormat('[DBNum1][$-804]AM/PMh"时"mm"分";@', '[DBNum1][$-804]AM/PMh"时"mm"分";@');
    t.validFormat('[DBNum1][$-804]General', '[DBNum1][$-804]General');
    t.validFormat('[DBNum1][$-804]h"时"mm"分";@', '[DBNum1][$-804]h"时"mm"分";@');
    t.validFormat('[$-1004]dddd\\,\\ d\\ mmmm\\,\\ yyyy;@', '[$-1004]dddd\\,\\ d\\ mmmm\\,\\ yyyy;@');
    t.validFormat('[$-101040D]d\\ mmmm\\ yyyy;@', '[$-101040D]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-101042A]d\\ mmmm\\ yyyy;@', '[$-101042A]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-140C]dddd\\ "YeahWoo!"\\ ddd\\ mmmm\\ yyyy;@', '[$-140C]dddd\\ "YeahWoo!"\\ ddd\\ mmmm\\ yyyy;@');
    t.validFormat('[$-2C0A]dddd\\ d" de "mmmm" de "yyyy;@', '[$-2C0A]dddd\\ d" de "mmmm" de "yyyy;@');
    t.validFormat('[$-402]dd\\ mmmm\\ yyyy\\ "г.";@', '[$-402]dd\\ mmmm\\ yyyy\\ "г.";@');
    t.validFormat('[$-403]dddd\\,\\ d" / "mmmm" / "yyyy;@', '[$-403]dddd\\,\\ d" / "mmmm" / "yyyy;@');
    t.validFormat('[$-405]d\\.\\ mmmm\\ yyyy;@', '[$-405]d\\.\\ mmmm\\ yyyy;@');
    t.validFormat('[$-408]d\\ mmmm\\ yyyy;@', '[$-408]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-409]d\\-mmm;@', '[$-409]d\\-mmm;@');
    t.validFormat('[$-409]d\\-mmm\\-yy;@', '[$-409]d\\-mmm\\-yy;@');
    t.validFormat('[$-409]d\\-mmm\\-yyyy;@', '[$-409]d\\-mmm\\-yyyy;@');
    t.validFormat('[$-409]dd\\-mmm\\-yy;@', '[$-409]dd\\-mmm\\-yy;@');
    t.validFormat('[$-409]mmm\\-yy;@', '[$-409]mmm\\-yy;@');
    t.validFormat('[$-409]mmmm\\ d\\,\\ yyyy;@', '[$-409]mmmm\\ d\\,\\ yyyy;@');
    t.validFormat('[$-409]mmmm\\-yy;@', '[$-409]mmmm\\-yy;@');
    t.validFormat('[$-40B]d\\.\\ mmmm\\t\\a\\ yyyy;@', '[$-40B]d\\.\\ mmmm\\t\\a\\ yyyy;@');
    t.validFormat('[$-40C]d/mmm/yyyy;@', '[$-40C]d/mmm/yyyy;@');
    t.validFormat('[$-40E]yyyy/\\ mmmm\\ d\\.;@', '[$-40E]yyyy/\\ mmmm\\ d\\.;@');
    t.validFormat('[$-40F]dd\\.\\ mmmm\\ yyyy;@', '[$-40F]dd\\.\\ mmmm\\ yyyy;@');
    t.validFormat('[$-410]d\\ mmmm\\ yyyy;@', '[$-410]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-415]d\\ mmmm\\ yyyy;@', '[$-415]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-416]d\\ \\ mmmm\\,\\ yyyy;@', '[$-416]d\\ \\ mmmm\\,\\ yyyy;@');
    t.validFormat('[$-418]d\\ mmmm\\ yyyy;@', '[$-418]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-41A]d\\.\\ mmmm\\ yyyy\\.;@', '[$-41A]d\\.\\ mmmm\\ yyyy\\.;@');
    t.validFormat('[$-41B]d\\.\\ mmmm\\ yyyy;@', '[$-41B]d\\.\\ mmmm\\ yyyy;@');
    t.validFormat('[$-41D]"den "\\ d\\ mmmm\\ yyyy;@', '[$-41D]"den "\\ d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-420]dddd\\,\\ dd\\ mmmm\\,\\ yyyy;@', '[$-420]dddd\\,\\ dd\\ mmmm\\,\\ yyyy;@');
    t.validFormat('[$-421]dd\\ mmmm\\ yyyy;@', '[$-421]dd\\ mmmm\\ yyyy;@');
    t.validFormat('[$-424]dddd\\,\\ d\\.\\ mmmm\\ yyyy;@', '[$-424]dddd\\,\\ d\\.\\ mmmm\\ yyyy;@');
    t.validFormat('[$-425]dddd\\,\\ d\\.\\ mmmm\\ yyyy;@', '[$-425]dddd\\,\\ d\\.\\ mmmm\\ yyyy;@');
    t.validFormat('[$-426]dddd\\,\\ yyyy". gada "d\\.\\ mmmm;@', '[$-426]dddd\\,\\ yyyy". gada "d\\.\\ mmmm;@');
    t.validFormat('[$-427]yyyy\\ "m."\\ mmmm\\ d\\ "d.";@', '[$-427]yyyy\\ "m."\\ mmmm\\ d\\ "d.";@');
    t.validFormat('[$-42B]dddd\\,\\ d\\ mmmm\\ yyyy;@', '[$-42B]dddd\\,\\ d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-42C]d\\ mmmm\\ yyyy;@', '[$-42C]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-42D]yyyy"(e)ko"\\ mmmm"ren"\\ d"a";@', '[$-42D]yyyy"(e)ko"\\ mmmm"ren"\\ d"a";@');
    t.validFormat('[$-42F]dddd\\,\\ dd\\ mmmm\\ yyyy;@', '[$-42F]dddd\\,\\ dd\\ mmmm\\ yyyy;@');
    t.validFormat('[$-437]yyyy\\ \\წ\\ლ\\ი\\ს\\ dd\\ mm\\,\\ dddd;@', '[$-437]yyyy\\ \\წ\\ლ\\ი\\ს\\ dd\\ mm\\,\\ dddd;@');
    t.validFormat('[$-438]d\\.\\ mmmm\\ yyyy;@', '[$-438]d\\.\\ mmmm\\ yyyy;@');
    t.validFormat('[$-43F]d\\ mmmm\\ yyyy\\ "ж.";@', '[$-43F]d\\ mmmm\\ yyyy\\ "ж.";@');
    t.validFormat('[$-444]d\\ mmmm\\ yyyy;@', '[$-444]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-449]dd\\ mmmm\\ yyyy;@', '[$-449]dd\\ mmmm\\ yyyy;@');
    t.validFormat('[$-44E]d\\ mmmm\\ yyyy;@', '[$-44E]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-44F]dd\\ mmmm\\ yyyy\\ dddd;@', '[$-44F]dd\\ mmmm\\ yyyy\\ dddd;@');
    t.validFormat('[$-457]dd\\ mmmm\\ yyyy;@', '[$-457]dd\\ mmmm\\ yyyy;@');
    t.validFormat('[$-813]dddd\\ d\\ mmmm\\ yyyy;@', '[$-813]dddd\\ d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-81A]dddd\\,\\ d\\.\\ mmmm\\ yyyy;@', '[$-81A]dddd\\,\\ d\\.\\ mmmm\\ yyyy;@');
    t.validFormat('[$-82C]d\\ mmmm\\ yyyy;@', '[$-82C]d\\ mmmm\\ yyyy;@');
    t.validFormat('[$-843]yyyy\\ "й""и""л"\\ d/mmmm;@', '[$-843]yyyy\\ "й""и""л"\\ d/mmmm;@');
    t.validFormat('[$-C07]dddd\\,\\ dd\\.\\ mmmm\\ yyyy;@', '[$-C07]dddd\\,\\ dd\\.\\ mmmm\\ yyyy;@');
    t.validFormat('[$-FC19]yyyy\\,\\ dd\\ mmmm;@', '[$-FC19]yyyy\\,\\ dd\\ mmmm;@');
    t.validFormat('[$-FC22]d\\ mmmm\\ yyyy" р.";@', '[$-FC22]d\\ mmmm\\ yyyy" р.";@');
    t.validFormat('[$-FC23]d\\ mmmm\\ yyyy;@', '[$-FC23]d\\ mmmm\\ yyyy;@');
    t.validFormat('[GREEN]#,###', '[GREEN]#,###');
    t.validFormat('[Green]#,###', '[Green]#,###');
    t.validFormat('[HH]', '[HH]');
    t.validFormat('[$-2060401]d/mm/yyyy\\ h:mm\\ AM/PM;@', '[$-2060401]d/mm/yyyy\\ h:mm\\ AM/PM;@');
    t.validFormat('[$-2060401]d\\ mmmm\\ yyyy;@', '[$-2060401]d\\ mmmm\\ yyyy;@');
    t.validFormat('[H]', '[H]');
    t.validFormat('[$-411]gggyy"年"m"月"d"日"\\ dddd;@', '[$-411]gggyy"年"m"月"d"日"\\ dddd;@');
    t.validFormat('[MAGENTA]0.00', '[MAGENTA]0.00');
    t.validFormat('[Magenta]0.00', '[Magenta]0.00');
    t.validFormat('[RED]#.##', '[RED]#.##');
    t.validFormat('[Red]#.##', '[Red]#.##');
    t.validFormat('[Red][<-25]General;[Blue][>25]General;[Green]General;[Yellow]General\\ ', '[Red][<-25]General;[Blue][>25]General;[Green]General;[Yellow]General\\ ');
    t.validFormat('[Red][<=-25]General;[Blue][>=25]General;[Green]General;[Yellow]General', '[Red][<=-25]General;[Blue][>=25]General;[Green]General;[Yellow]General');
    t.validFormat('[Red][<>50]General;[Blue]000', '[Red][<>50]General;[Blue]000');
    t.validFormat('[Red][=50]General;[Blue]000', '[Red][=50]General;[Blue]000');
    t.validFormat('[SS]', '[SS]');
    t.validFormat('[S]', '[S]');
    t.validFormat('[DBNum1][$-404]y"年"m"月"d"日";@', '[DBNum1][$-404]y"年"m"月"d"日";@');
    t.validFormat('[WHITE]0.0', '[WHITE]0.0');
    t.validFormat('[White]0.0', '[White]0.0');
    t.validFormat('[YELLOW]@', '[YELLOW]@');
    t.validFormat('[Yellow]@', '[Yellow]@');
    t.validFormat('[h]', '[h]');
    t.validFormat('[h]:mm:ss', '[h]:mm:ss');
    t.validFormat('[h]:mm:ss;@', '[h]:mm:ss;@');
    t.validFormat('[h]\\.mm" Uhr ";@', '[h]\\.mm" Uhr ";@');
    t.validFormat('[hh]', '[hh]');
    t.validFormat('[s]', '[s]');
    t.validFormat('[ss]', '[ss]');
    t.validFormat('\\#\\r\\e\\c', '\\#\\r\\e\\c');
    t.validFormat('\\$#,##0_);[Red]"($"#,##0\\)', '\\$#,##0_);[Red]"($"#,##0\\)');
    t.validFormat('\\$0.00', '\\$0.00');
    t.validFormat('\\C\\O\\B\\ \\o\\n\\ @', '\\C\\O\\B\\ \\o\\n\\ @');
    t.validFormat('\\C\\R\\O\\N\\T\\A\\B\\ \\o\\n\\ @', '\\C\\R\\O\\N\\T\\A\\B\\ \\o\\n\\ @');
    t.validFormat('\\R\\e\\s\\u\\l\\t\\ \\o\\n\\ @', '\\R\\e\\s\\u\\l\\t\\ \\o\\n\\ @');
    t.validFormat('\\S\\Q\\L\\ \\:\\ @', '\\S\\Q\\L\\ \\:\\ @');
    t.validFormat('\\S\\Q\\L\\ \\R\\e\\q\\u\\e\\s\\t\\ \\f\\o\\r\\ @', '\\S\\Q\\L\\ \\R\\e\\q\\u\\e\\s\\t\\ \\f\\o\\r\\ @');
    t.validFormat('\\c\\c\\c?????0"aaaa"0"bbbb"000000.00%', '\\c\\c\\c?????0"aaaa"0"bbbb"000000.00%');
    t.validFormat('\\u\\n\\t\\i\\l\\ h:mm;@', '\\u\\n\\t\\i\\l\\ h:mm;@');
    t.validFormat('_ "￥"* #,##0.00_ "Positive";_ "￥"* \\-#,##0.00_ ;_ "￥"* "-"??_ "Negtive";_ @_ \\ "Zero"', '_ "￥"* #,##0.00_ "Positive";_ "￥"* \\-#,##0.00_ ;_ "￥"* "-"??_ "Negtive";_ @_ \\ "Zero"');
    t.validFormat('_ * #,##0.00_)[$﷼-429]_ ;_ * \\(#,##0.00\\)[$﷼-429]_ ;_ * "-"??_)[$﷼-429]_ ;_ @_ ', '_ * #,##0.00_)[$﷼-429]_ ;_ * \\(#,##0.00\\)[$﷼-429]_ ;_ * "-"??_)[$﷼-429]_ ;_ @_ ');
    t.validFormat('_ * #,##0_ ;_ * \\-#,##0_ ;[Red]_ * "-"_ ;_ @_ ', '_ * #,##0_ ;_ * \\-#,##0_ ;[Red]_ * "-"_ ;_ @_ ');
    t.validFormat('_("$"* #,##0.00_);_("$"* \\(#,##0.00\\);_("$"* "-"??_);_(@_)', '_("$"* #,##0.00_);_("$"* \\(#,##0.00\\);_("$"* "-"??_);_(@_)');
    t.validFormat('_("$"* #,##0_);_("$"* \\(#,##0\\);_("$"* "-"??_);_(@_)', '_("$"* #,##0_);_("$"* \\(#,##0\\);_("$"* "-"??_);_(@_)');
    t.validFormat('_("$"* #,##0_);_("$"* \\(#,##0\\);_("$"* "-"_);_(@_)', '_("$"* #,##0_);_("$"* \\(#,##0\\);_("$"* "-"_);_(@_)');
    t.validFormat('_(* #,##0.0000_);_(* \\(#,##0.0000\\);_(* "-"??_);_(@_)', '_(* #,##0.0000_);_(* \\(#,##0.0000\\);_(* "-"??_);_(@_)');
    t.validFormat('_(* #,##0.000_);_(* \\(#,##0.000\\);_(* "-"??_);_(@_)', '_(* #,##0.000_);_(* \\(#,##0.000\\);_(* "-"??_);_(@_)');
    t.validFormat('_(* #,##0.00_);_(* \\(#,##0.00\\);_(* "-"??_);_(@_)', '_(* #,##0.00_);_(* \\(#,##0.00\\);_(* "-"??_);_(@_)');
    t.validFormat('_(* #,##0.0_);_(* \\(#,##0.0\\);_(* "-"??_);_(@_)', '_(* #,##0.0_);_(* \\(#,##0.0\\);_(* "-"??_);_(@_)');
    t.validFormat('_(* #,##0_);_(* \\(#,##0\\);_(* "-"??_);_(@_)', '_(* #,##0_);_(* \\(#,##0\\);_(* "-"??_);_(@_)');
    t.validFormat('_(* #,##0_);_(* \\(#,##0\\);_(* "-"_);_(@_)', '_(* #,##0_);_(* \\(#,##0\\);_(* "-"_);_(@_)');
    t.validFormat('_([$ANG]\\ * #,##0.0_);_([$ANG]\\ * \\(#,##0.0\\);_([$ANG]\\ * "-"?_);_(@_)', '_([$ANG]\\ * #,##0.0_);_([$ANG]\\ * \\(#,##0.0\\);_([$ANG]\\ * "-"?_);_(@_)');
    t.validFormat('_-"€"\\ * #,##0.00_-;_-"€"\\ * #,##0.00\\-;_-"€"\\ * "-"??_-;_-@_-', '_-"€"\\ * #,##0.00_-;_-"€"\\ * #,##0.00\\-;_-"€"\\ * "-"??_-;_-@_-');
    t.validFormat('_-* #,##0.00" TL"_-;\\-* #,##0.00" TL"_-;_-* \\-??" TL"_-;_-@_-', '_-* #,##0.00" TL"_-;\\-* #,##0.00" TL"_-;_-* \\-??" TL"_-;_-@_-');
    t.validFormat('_-* #,##0.00" €"_-;\\-* #,##0.00" €"_-;_-* \\-??" €"_-;_-@_-', '_-* #,##0.00" €"_-;\\-* #,##0.00" €"_-;_-* \\-??" €"_-;_-@_-');
    t.validFormat('_-* #,##0.00\\ "р."_-;\\-* #,##0.00\\ "р."_-;_-* "-"??\\ "р."_-;_-@_-', '_-* #,##0.00\\ "р."_-;\\-* #,##0.00\\ "р."_-;_-* "-"??\\ "р."_-;_-@_-');
    t.validFormat('_-* #,##0.00\\ "€"_-;\\-* #,##0.00\\ "€"_-;_-* "-"??\\ "€"_-;_-@_-', '_-* #,##0.00\\ "€"_-;\\-* #,##0.00\\ "€"_-;_-* "-"??\\ "€"_-;_-@_-');
    t.validFormat('_-* #,##0.00\\ [$€-407]_-;\\-* #,##0.00\\ [$€-407]_-;_-* \\-??\\ [$€-407]_-;_-@_-', '_-* #,##0.00\\ [$€-407]_-;\\-* #,##0.00\\ [$€-407]_-;_-* \\-??\\ [$€-407]_-;_-@_-');
    t.validFormat('_-* #,##0.0\\ _F_-;\\-* #,##0.0\\ _F_-;_-* "-"??\\ _F_-;_-@_-', '_-* #,##0.0\\ _F_-;\\-* #,##0.0\\ _F_-;_-* "-"??\\ _F_-;_-@_-');
    t.validFormat('_-* #,##0\\ "€"_-;\\-* #,##0\\ "€"_-;_-* "-"\\ "€"_-;_-@_-', '_-* #,##0\\ "€"_-;\\-* #,##0\\ "€"_-;_-* "-"\\ "€"_-;_-@_-');
    t.validFormat('_-* #,##0_-;\\-* #,##0_-;_-* "-"??_-;_-@_-', '_-* #,##0_-;\\-* #,##0_-;_-* "-"??_-;_-@_-');
    t.validFormat('_-\\$* #,##0.0_ ;_-\\$* \\-#,##0.0\\ ;_-\\$* "-"?_ ;_-@_ ', '_-\\$* #,##0.0_ ;_-\\$* \\-#,##0.0\\ ;_-\\$* "-"?_ ;_-@_ ');
    t.validFormat('d', 'd');
    t.validFormat('d-mmm', 'd-mmm');
    t.validFormat('d-mmm-yy', 'd-mmm-yy');
    t.validFormat('d/m', 'd/m');
    t.validFormat('d/m/yy;@', 'd/m/yy;@');
    t.validFormat('d/m/yyyy;@', 'd/m/yyyy;@');
    t.validFormat('d/mm/yy;@', 'd/mm/yy;@');
    t.validFormat('d/mm/yyyy;@', 'd/mm/yyyy;@');
    t.validFormat('d\\-mmm', 'd\\-mmm');
    t.validFormat('d\\-mmm\\-yyyy', 'd\\-mmm\\-yyyy');
    t.validFormat('dd', 'dd');
    t.validFormat('dd"-"mmm"-"yyyy', 'dd"-"mmm"-"yyyy');
    t.validFormat('dd/m/yyyy', 'dd/m/yyyy');
    t.validFormat('dd/mm/yy', 'dd/mm/yy');
    t.validFormat('dd/mm/yy;@', 'dd/mm/yy;@');
    t.validFormat('dd/mm/yy\\ hh:mm', 'dd/mm/yy\\ hh:mm');
    t.validFormat('dd/mm/yyyy', 'dd/mm/yyyy');
    t.validFormat('dd/mm/yyyy\\ hh:mm:ss', 'dd/mm/yyyy\\ hh:mm:ss');
    t.validFormat('dd/mmm', 'dd/mmm');
    t.validFormat('dd\\-mm\\-yy', 'dd\\-mm\\-yy');
    t.validFormat('dd\\-mmm\\-yy', 'dd\\-mmm\\-yy');
    t.validFormat('dd\\-mmm\\-yyyy\\ hh:mm:ss.000', 'dd\\-mmm\\-yyyy\\ hh:mm:ss.000');
    t.validFormat('dd\\/mm\\/yy', 'dd\\/mm\\/yy');
    t.validFormat('dd\\/mm\\/yyyy', 'dd\\/mm\\/yyyy');
    t.validFormat('ddd', 'ddd');
    t.validFormat('dddd', 'dddd');
    t.validFormat('dddd, mmmm dd, yyyy', 'dddd, mmmm dd, yyyy');
    t.validFormat('h', 'h');
    t.validFormat('h"时"mm"分"ss"秒";@', 'h"时"mm"分"ss"秒";@');
    t.validFormat('h"時"mm"分"ss"秒";@', 'h"時"mm"分"ss"秒";@');
    t.validFormat('h:mm', 'h:mm');
    t.validFormat('h:mm AM/PM', 'h:mm AM/PM');
    t.validFormat('h:mm:ss', 'h:mm:ss');
    t.validFormat('h:mm:ss AM/PM', 'h:mm:ss AM/PM');
    t.validFormat('h:mm:ss;@', 'h:mm:ss;@');
    t.validFormat('h:mm;@', 'h:mm;@');
    t.validFormat('h\\.mm" Uhr ";@', 'h\\.mm" Uhr ";@');
    t.validFormat('h\\.mm" h";@', 'h\\.mm" h";@');
    t.validFormat('h\\.mm" u.";@', 'h\\.mm" u.";@');
    t.validFormat('hh":"mm AM/PM', 'hh":"mm AM/PM');
    t.validFormat('hh:mm:ss', 'hh:mm:ss');
    t.validFormat('hh:mm:ss\\ AM/PM', 'hh:mm:ss\\ AM/PM');
    t.validFormat('hh\\.mm" h";@', 'hh\\.mm" h";@');
    t.validFormat('hhm', 'hhm');
    t.validFormat('hhmm', 'hhmm');
    t.validFormat('m"月"d"日"', 'm"月"d"日"');
    t.validFormat('m/d/yy', 'm/d/yy');
    t.validFormat('m/d/yy h:mm', 'm/d/yy h:mm');
    t.validFormat('m/d/yy;@', 'm/d/yy;@');
    t.validFormat('m/d/yy\\ h:mm', 'm/d/yy\\ h:mm');
    t.validFormat('m/d/yy\\ h:mm;@', 'm/d/yy\\ h:mm;@');
    t.validFormat('m/d/yyyy', 'm/d/yyyy');
    t.validFormat('m/d/yyyy;@', 'm/d/yyyy;@');
    t.validFormat('m/d/yyyy\\ h:mm:ss;@', 'm/d/yyyy\\ h:mm:ss;@');
    t.validFormat('m/d;@', 'm/d;@');
    t.validFormat('m\\/d\\/yyyy', 'm\\/d\\/yyyy');
    t.validFormat('mm/dd', 'mm/dd');
    t.validFormat('mm/dd/yy', 'mm/dd/yy');
    t.validFormat('mm/dd/yy;@', 'mm/dd/yy;@');
    t.validFormat('mm/dd/yyyy', 'mm/dd/yyyy');
    t.validFormat('mm:ss', 'mm:ss');
    t.validFormat('mm:ss.0;@', 'mm:ss.0;@');
    t.validFormat('mmm d, yyyy', 'mmm d, yyyy');
    t.validFormat('mmm" "d", "yyyy', 'mmm" "d", "yyyy');
    t.validFormat('mmm-yy', 'mmm-yy');
    t.validFormat('mmm-yy;@', 'mmm-yy;@');
    t.validFormat('mmm/yy', 'mmm/yy');
    t.validFormat('mmm\\-yy', 'mmm\\-yy');
    t.validFormat('mmm\\-yy;@', 'mmm\\-yy;@');
    t.validFormat('mmm\\-yyyy', 'mmm\\-yyyy');
    t.validFormat('mmmm\\ d\\,\\ yyyy', 'mmmm\\ d\\,\\ yyyy');
    t.validFormat('mmmm\\ yyyy', 'mmmm\\ yyyy');
    t.validFormat('mmss.0', 'mmss.0');
    t.validFormat('s', 's');
    t.validFormat('ss', 'ss');
    t.validFormat('yy', 'yy');
    t.validFormat('yy/mm/dd', 'yy/mm/dd');
    t.validFormat('yy\\.mm\\.dd', 'yy\\.mm\\.dd');
    t.validFormat('yym', 'yym');
    t.validFormat('yymm', 'yymm');
    t.validFormat('yymmm', 'yymmm');
    t.validFormat('yymmmm', 'yymmmm');
    t.validFormat('yymmmmm', 'yymmmmm');
    t.validFormat('yyyy', 'yyyy');
    t.validFormat('yyyy"년"\\ m"월"\\ d"일";@', 'yyyy"년"\\ m"월"\\ d"일";@');
    t.validFormat('yyyy-m-d h:mm AM/PM', 'yyyy-m-d h:mm AM/PM');
    t.validFormat('yyyy-mm-dd', 'yyyy-mm-dd');
    t.validFormat('yyyy/mm/dd', 'yyyy/mm/dd');
    t.validFormat('yyyy\\-m\\-d\\ hh:mm:ss', 'yyyy\\-m\\-d\\ hh:mm:ss');
    t.validFormat('yyyy\\-mm\\-dd', 'yyyy\\-mm\\-dd');
    t.validFormat('yyyy\\-mm\\-dd;@', 'yyyy\\-mm\\-dd;@');
    t.validFormat('yyyy\\-mm\\-dd\\ h:mm', 'yyyy\\-mm\\-dd\\ h:mm');
    t.validFormat('yyyy\\-mm\\-dd\\Thh:mm', 'yyyy\\-mm\\-dd\\Thh:mm');
    t.validFormat('yyyy\\-mm\\-dd\\Thhmmss.000', 'yyyy\\-mm\\-dd\\Thhmmss.000');
});
