import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const EXAMPLES_ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.resolve(EXAMPLES_ROOT, 'src');
const PUBLIC_DIR = path.resolve(EXAMPLES_ROOT, 'public');
const GENERATED_DEMOS_FILE = path.resolve(SRC_DIR, 'demos.ts');

const DEMO_MAIN_ENTRY_NAMES = ['main.ts', 'main.tsx'] as const;
const DEMO_EXTRA_ENTRY_NAMES = ['worker.ts', 'worker.tsx'] as const;
const IGNORED_PUBLIC_ENTRIES = new Set(['favicon.svg', 'index.html']);

export const IS_CI = !!process.env.CI;

const ESBUILD_SCRIPT = IS_CI
    ? ''
    : `
        <script>
            new EventSource('/esbuild').addEventListener('change', () => {
                console.info('reload--');
                location.reload();
            });
        </script>`;

const indexTemplate = `<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <title>Univer</title>

        <link rel="icon" type="image/x-icon" href="../favicon.svg" />
        <link rel="stylesheet" href="./main.css" />
        <style>
            html,
            body {
                height: 100%;
                margin: 0;
                font-family: Arial;
            }
        </style>${ESBUILD_SCRIPT}
    </head>

    <body style="overflow: hidden">
        <div id="app" style="height: 100%"></div>

        <script type="module" src="./main.js"></script>
    </body>
</html>
`;

export interface IDemoDefinition {
    dir: string;
    entryPoints: string[];
    href: `./${string}/`;
    title: string;
}

function formatDemoTitle(dir: string) {
    const wordOverrides: Record<string, string> = {
        docs: 'Docs',
        s: 'S',
        ui: 'UI',
        webcomponent: 'Web Component',
    };

    return dir
        .split('-')
        .filter(Boolean)
        .map((segment) => wordOverrides[segment] ?? `${segment[0].toUpperCase()}${segment.slice(1)}`)
        .join(' ');
}

function getDemoEntryFiles(exampleDir: string) {
    const entries: string[] = [];

    for (const entryName of DEMO_MAIN_ENTRY_NAMES) {
        if (fs.existsSync(path.resolve(exampleDir, entryName))) {
            entries.push(entryName);
            break;
        }
    }

    if (!entries.length) {
        return entries;
    }

    for (const entryName of DEMO_EXTRA_ENTRY_NAMES) {
        if (fs.existsSync(path.resolve(exampleDir, entryName))) {
            entries.push(entryName);
        }
    }

    return entries;
}

export function discoverDemos() {
    return fs.readdirSync(SRC_DIR)
        .sort((left, right) => left.localeCompare(right))
        .map((dir): IDemoDefinition | null => {
            const exampleDir = path.resolve(SRC_DIR, dir);

            if (!fs.statSync(exampleDir).isDirectory()) {
                return null;
            }

            const entryFiles = getDemoEntryFiles(exampleDir);

            if (!entryFiles.length) {
                return null;
            }

            return {
                dir,
                title: formatDemoTitle(dir),
                href: `./${dir}/`,
                entryPoints: entryFiles.map((entryFile) => `./src/${dir}/${entryFile}`),
            };
        })
        .filter((demo): demo is IDemoDefinition => demo !== null);
}

function filterDemos(demos: IDemoDefinition[], selectedDirs?: string[]): IDemoDefinition[] {
    return selectedDirs ? demos.filter((demo) => selectedDirs.includes(demo.dir)) : demos;
}

function syncDemoHtml(demos: IDemoDefinition[]) {
    fs.mkdirSync(PUBLIC_DIR, { recursive: true });

    const activeDemoDirs = new Set(demos.map((demo) => demo.dir));

    fs.readdirSync(PUBLIC_DIR).forEach((entry) => {
        if (IGNORED_PUBLIC_ENTRIES.has(entry)) {
            return;
        }

        const entryPath = path.resolve(PUBLIC_DIR, entry);

        if (!fs.statSync(entryPath).isDirectory()) {
            return;
        }

        if (activeDemoDirs.has(entry)) {
            return;
        }

        if (fs.existsSync(path.resolve(entryPath, 'index.html'))) {
            fs.rmSync(entryPath, { force: true, recursive: true });
        }
    });

    demos.forEach((demo) => {
        const targetDir = path.resolve(PUBLIC_DIR, demo.dir);
        fs.mkdirSync(targetDir, { recursive: true });
        fs.writeFileSync(path.resolve(targetDir, 'index.html'), indexTemplate);
    });
}

function syncDemosModule(demos: IDemoDefinition[]) {
    const demoImports = demos.map(({ dir, href, title }) => ({ dir, href, title }));

    const content = `${[
        '/**',
        ' * This file is auto-generated by `./scripts/sync-demos.mts`.',
        ' */',
        `export const demos = ${JSON.stringify(demoImports, null, 4)} as const;`,
        '',
        'export type Demo = (typeof demos)[number];',
        '',
    ].join('\n')}`;

    fs.writeFileSync(GENERATED_DEMOS_FILE, content);
}

export function getDemoEntryPoints(selectedDirs?: string[]) {
    const demos = filterDemos(discoverDemos(), selectedDirs);
    return ['./src/main.tsx', ...demos.flatMap((demo) => demo.entryPoints)];
}

export function syncDemoArtifacts(selectedDirs?: string[]) {
    const demos = filterDemos(discoverDemos(), selectedDirs);
    syncDemoHtml(demos);
    syncDemosModule(demos);

    return {
        demos,
        entryPoints: ['./src/main.tsx', ...demos.flatMap((demo) => demo.entryPoints)],
    };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    syncDemoArtifacts();
}
