name: 🧪 CI Test

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read
    pull-requests: write

env:
    TURBO_TELEMETRY_DISABLED: '1'

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  persist-credentials: false

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: 🩺 Run test
              run: pnpm coverage

            - name: 🧬 Report coverage
              uses: codecov/codecov-action@v7
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    eslint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  persist-credentials: false

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: 🌡️ Run ESLint
              run: pnpm lint --quiet

    typecheck:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  persist-credentials: false

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: 🧼 Type checking
              run: pnpm typecheck
