name: 📤 Preview Deploy

on:
    workflow_run:
        workflows:
            - 🎬 Setup
        types:
            - completed

concurrency:
    group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.ref }}
    cancel-in-progress: true

permissions:
    contents: write
    pull-requests: write
    actions: read

jobs:
    setup:
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_repository.full_name == github.repository }}
        runs-on: ubuntu-latest

        outputs:
            id: ${{ steps.pr.outputs.value }}
            ref: ${{ steps.ref.outputs.value }}
            repo: ${{ steps.repo.outputs.value }}
            state: ${{ steps.state.outputs.value }}

        steps:
            # Get PR id from artifact
            - name: download pr artifact
              uses: dawidd6/action-download-artifact@v9
              with:
                  workflow: ${{ github.event.workflow_run.workflow_id }}
                  run_id: ${{ github.event.workflow_run.id }}
                  name: pr-id

            - name: get PR id
              id: pr
              run: echo "value=$(<pr-id.txt)" >> $GITHUB_OUTPUT

            # Get PR ref from artifact
            - name: download pr artifact
              uses: dawidd6/action-download-artifact@v9
              with:
                  workflow: ${{ github.event.workflow_run.workflow_id }}
                  run_id: ${{ github.event.workflow_run.id }}
                  name: pr-ref

            - name: get PR ref
              id: ref
              run: echo "value=$(<pr-ref.txt)" >> $GITHUB_OUTPUT

            # Get PR repo from artifact
            - name: download pr artifact
              uses: dawidd6/action-download-artifact@v9
              with:
                  workflow: ${{ github.event.workflow_run.workflow_id }}
                  run_id: ${{ github.event.workflow_run.id }}
                  name: pr-repo

            - name: get PR repo
              id: repo
              run: echo "value=$(<pr-repo.txt)" >> $GITHUB_OUTPUT

            # Get PR state from artifact
            - name: download pr state artifact
              uses: dawidd6/action-download-artifact@v9
              with:
                  workflow: ${{ github.event.workflow_run.workflow_id }}
                  run_id: ${{ github.event.workflow_run.id }}
                  name: pr-state

            - name: get PR state
              id: state
              run: echo "value=$(<pr-state.txt)" >> $GITHUB_OUTPUT

    prepare:
        runs-on: ubuntu-latest
        needs: [setup]
        if: ${{ needs.setup.outputs.id != '' && needs.setup.outputs.state != 'closed' }}

        steps:
            # ================= Create Comment =================
            - name: 🧽 Find And Delete Comment
              uses: peter-evans/find-comment@v2
              if: ${{ needs.setup.outputs.id != '' }}
              id: fc
              with:
                  issue-number: ${{ needs.setup.outputs.id }}
                  comment-author: 'github-actions[bot]'
                  body-includes: View Deployment

            - name: 📝 Create or update comment
              uses: peter-evans/create-or-update-comment@v3
              if: ${{ needs.setup.outputs.id != '' }}
              with:
                  comment-id: ${{ steps.fc.outputs.comment-id }}
                  issue-number: ${{ needs.setup.outputs.id }}
                  body: |
                      ## View Deployment

                      [#${{ github.run_id }}](https://github.com/dream-num/univer/actions/runs/${{ github.run_id }})

                      <p align="center">
                        🥐 🍔 🥓 🥗 🥘 🌯 🍚 🍛 🍖 🍭 🍧 🍝 🥪 🥖 🍪 <br />
                        Still cooking, please come back later <br />
                        🥙 🥮 🥨 🌭 🍦 🍙 🍕 🍰 🍮 🍜 🍡 🍱 🍿 🍕 🥟
                      </p>
                  edit-mode: replace

    build-and-deploy:
        runs-on: ubuntu-latest
        needs: [setup]
        if: ${{ needs.setup.outputs.id != '' }}

        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  repository: ${{ needs.setup.outputs.repo }}
                  ref: ${{ needs.setup.outputs.ref }}
                  persist-credentials: false

            - name: Setup pnpm
              uses: pnpm/action-setup@v6
              with:
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24.3.0
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Get commit message
              id: commit-message
              run: echo "value=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

            - name: Prepare dist directory
              run: mkdir -p dist

            #  ================= Deploy Demo =================
            - name: 📦 Build demo
              if: ${{ needs.setup.outputs.state != 'closed' }}
              run: pnpm build:demo

            - name: Copy demo to workspace
              if: ${{ needs.setup.outputs.state != 'closed' }}
              run: cp -r ./examples/local/* dist

            - name: 📦 Build react16 demo
              if: ${{ needs.setup.outputs.state != 'closed' }}
              run: |
                  pnpm use:react16
                  pnpm build:demo

            - name: Copy react16 demo
              if: ${{ needs.setup.outputs.state != 'closed' }}
              run: |
                  mkdir -p dist/react16
                  cp -r ./examples/local/* dist/react16

            # ================= Deploy Storybook =================
            - name: 📦 Build storybook
              if: ${{ needs.setup.outputs.state != 'closed' }}
              run: pnpm storybook:build

            - name: Copy storybook
              if: ${{ needs.setup.outputs.state != 'closed' }}
              run: |
                  mkdir -p dist/storybook
                  cp -r ./common/storybook/storybook-static/* dist/storybook

            # ================= Deploy PR Preview =================
            - name: 🚀 Deploy to GitHub Pages (preview)
              uses: rossjrw/pr-preview-action@v1
              with:
                  source-dir: ./dist
                  preview-branch: gh-pages
                  umbrella-dir: pr-preview
                  pr-number: ${{ needs.setup.outputs.id }}
                  comment: false
                  action: ${{ needs.setup.outputs.state == 'closed' && 'remove' || 'deploy' }}

    notify:
        runs-on: ubuntu-latest
        needs: [setup, build-and-deploy]
        if: ${{ needs.setup.outputs.id != '' && needs.setup.outputs.state != 'closed' }}

        steps:
            # ================= Create Comment =================
            - name: 🧽 Find And Delete Comment
              uses: peter-evans/find-comment@v2
              if: ${{ needs.setup.outputs.id != '' }}
              id: fc
              with:
                  issue-number: ${{ needs.setup.outputs.id }}
                  comment-author: 'github-actions[bot]'
                  body-includes: View Deployment

            - name: 📝 Create or update comment
              uses: peter-evans/create-or-update-comment@v3
              if: ${{ needs.setup.outputs.id != '' }}
              with:
                  comment-id: ${{ steps.fc.outputs.comment-id }}
                  issue-number: ${{ needs.setup.outputs.id }}
                  body: |
                      ## View Deployment
                      | 📑 Demo (React@19) | Demo (React@16) | 📚 Storybook |
                      | --- | --- | --- |
                      | [🔗 Preview link](https://dream-num.github.io/univer/pr-preview/pr-${{ needs.setup.outputs.id }}/) | [🔗 Preview link](https://dream-num.github.io/univer/pr-preview/pr-${{ needs.setup.outputs.id }}/react16/) | [🔗 Preview link](https://dream-num.github.io/univer/pr-preview/pr-${{ needs.setup.outputs.id }}/storybook/) |
                  edit-mode: replace
