name: 🍰 Release

on:
    push:
        tags:
            - 'v*.*.*'
            - 'v*.*.*-alpha.*'
            - 'v*.*.*-beta.*'
            - 'v*.*.*-rc.*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

env:
    TURBO_TELEMETRY_DISABLED: '1'

jobs:
    prepare:
        if: github.repository == 'dream-num/univer'
        runs-on: ubuntu-latest

        outputs:
            release_type: ${{ steps.release-type.outputs.value }}

        steps:
            - name: 🚚 Get release type
              id: release-type
              env:
                  REF_NAME: ${{ github.ref_name }}
              run: |
                  if [[ "$REF_NAME" =~ -(alpha|beta|rc)\. ]]; then
                      extracted_type="${BASH_REMATCH[1]}"
                      echo "value=$extracted_type" >> "$GITHUB_OUTPUT"
                  else
                      echo "value=stable" >> "$GITHUB_OUTPUT"
                  fi

    release-npm:
        needs: [prepare]
        if: github.repository == 'dream-num/univer'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  ref: ${{ github.ref_name }}
                  persist-credentials: false

            - name: Install pnpm
              uses: pnpm/action-setup@v6
              with:
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24.3.0
                  registry-url: https://registry.npmjs.org

            - name: 🚚 Install dependencies and build
              run: |
                  pnpm install
                  pnpm build

            - name: 🐙 Publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true
                  RELEASE_TYPE: ${{ needs.prepare.outputs.release_type }}
              run: |
                  if [[ "$RELEASE_TYPE" == "stable" ]]; then
                      pnpm publish --access public -r --no-git-checks
                  else
                      pnpm publish --access public --tag "$RELEASE_TYPE" -r --no-git-checks
                  fi
